---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= BlueXP backup and recovery 대한 자주 묻는 질문
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 구축

* BlueXP 백업 및 복구 미리보기 버전을 사용하려면 라이선스가 필요합니까?*

다음과 같은 라이센스 유형을 사용할 수 있습니다.

* 30일 무료 평가판을 신청하십시오.


* BlueXP backup and recovery 어떻게 활성화하나요?* BlueXP backup and recovery 별도의 활성화가 필요하지 않습니다. 백업 및 복구 옵션은 BlueXP 왼쪽 탐색 메뉴에서 자동으로 활성화됩니다.

이 서비스를 이용하려면 등록하거나 NetApp 영업 담당자에게 연락하여 이 서비스를 체험해 보십시오. BlueXP Connector를 사용하면 서비스에 적합한 기능이 여기에 포함됩니다.

BlueXP backup and recovery 시작하려면 초기 랜딩 페이지에서 "워크로드 검색 시작"을 클릭합니다.

* BlueXP backup and recovery 표준, 제한 및 비공개 모드에서 사용할 수 있나요?* 현재 BlueXP backup and recovery 미리 보기 버전은 표준 모드에서만 사용할 수 있습니다. 많은 관심 부탁드립니다.

모든 BlueXP  서비스에서 이러한 모드에 대한 설명은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드"^].



== 액세스

* BlueXP backup and recovery URL은 무엇인가요?* URL의 경우 브라우저에 다음을 입력하여 BlueXP  콘솔에 액세스합니다. https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^]

* 액세스 권한은 어떻게 처리됩니까? * 조직 관리자만 서비스를 시작하고 워크로드를 검색할 수 있습니다(리소스 사용을 커밋하는 작업이 포함되므로). 이후 상호 작용은 모든 역할에 의해 수행될 수 있습니다.

* 어떤 장치 해상도가 가장 좋습니까? * BlueXP backup and recovery 에 권장되는 장치 해상도는 1920x1080 이상입니다.

* 어떤 브라우저를 사용해야 합니까? * 모든 최신 브라우저가 작동합니다.



== 다른 서비스와의 상호 작용

* BlueXP backup and recovery NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?* 예, BlueXP backup and recovery ONTAP 에서 설정된 스냅샷 일정을 검색합니다.

* BlueXP backup and recovery 사용하여 정책을 설정하는 경우 향후 변경은 이 서비스에서만 해야 합니까?* BlueXP backup and recovery 서비스에서 정책을 변경하는 것이 좋습니다.



== 워크로드

* 워크로드를 구성하는 요소는 무엇입니까? * 워크로드는 Preview 2025 버전용 애플리케이션입니다. 워크로드에는 단일 애플리케이션 인스턴스에서 사용하는 모든 볼륨이 포함됩니다. 예를 들어, mssql3.host.com에 배포된 Microsoft SQL Server DB 인스턴스는 데이터와 로그에 대해 각각 vol1과 vol2를 가질 수 있습니다. 이러한 볼륨은 함께 해당 DB 인스턴스의 특정 인스턴스에 대한 워크로드를 구성합니다.

* BlueXP backup and recovery 어떤 워크로드를 지원합니까?*

Preview 2025 버전의 경우 BlueXP backup and recovery 다음 작업 부하를 식별할 수 있습니다. Microsoft SQL Server 애플리케이션.

* "보호된" 워크로드란 무엇입니까? * BlueXP backup and recovery 에서는 기본 감지 정책이 활성화된 경우 워크로드가 "보호됨" 상태로 표시됩니다.

* "위험" 워크로드란 무엇입니까? * 워크로드에 기본 감지 정책이 활성화되어 있지 않으면 백업 및 스냅샷 정책을 활성화한 경우에도 "위험에 처해 있습니다."

*새로운 워크로드가 추가되었지만 아직 나타나지 않음* 환경에 새로운 워크로드를 추가한 경우 검색을 다시 시작하고 해당 새로운 리소스를 보호하기 위해 보호 정책을 적용합니다.



== 보호 정책

* BlueXP backup and recovery NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?*

네, BlueXP backup and recovery ONTAP 에 설정된 스냅샷 일정을 검색하고 검색된 워크로드에서 ARP 및 FPolicy가 활성화되어 있는지 여부를 검색합니다. 대시보드의 처음에 표시되는 정보는 다른 NetApp 솔루션 및 제품에서 집계됩니다.

* BlueXP backup and recovery SnapCenter 에 이미 만들어진 정책을 인식합니까?*

네, SnapCenter 에서 관리되는 워크로드가 있는 경우 해당 제품에서 관리하는 정책이 BlueXP backup and recovery 로 적용됩니다.

* SnapCenter 에서 가져온 정책을 수정할 수 있나요?*

네, BlueXP backup and recovery 내에서 SnapCenter 가 관리하던 정책을 수정할 수 있습니다.

* ONTAP 의 정책(ARP, FPolicy, 스냅샷 등 시스템 관리자에서 이미 활성화됨)이 있는 경우 BlueXP backup and recovery 에서 해당 정책이 변경됩니까?*

아니요. BlueXP backup and recovery ONTAP 의 기존 탐지 정책(ARP, FPolicy 설정)을 수정하지 않습니다.

* BlueXP backup and recovery 에 가입한 후 SnapCenter 에 새로운 정책을 추가하면 어떻게 되나요?*

BlueXP backup and recovery SnapCenter 에서 생성된 모든 새로운 정책을 인식합니다.

* ONTAP에서 정책을 변경할 수 있습니까? *

네, BlueXP backup and recovery 에서 ONTAP 의 정책을 변경할 수 있습니다. BlueXP backup and recovery 에서 새 정책을 생성하여 워크로드에 적용할 수도 있습니다. 이 작업을 수행하면 기존 ONTAP 정책이 BlueXP backup and recovery 에서 생성된 정책으로 대체됩니다.
