---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: BlueXP backup and recovery 사용하면 보호 정책으로 보호한 애플리케이션을 복원할 수 있습니다. 
---
= Kubernetes 애플리케이션 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recovery 사용하면 보호 정책으로 보호한 애플리케이션을 복원할 수 있습니다. 애플리케이션을 복원하려면 해당 애플리케이션의 보호 상태가 "보호됨"이어야 하며, 관련 보호 정책이 있어야 합니다. 로컬 스냅샷, 보조 스냅샷, 그리고 객체 저장소 백업으로 구성된 복원 지점을 사용하여 애플리케이션을 복원합니다. 로컬, 보조 또는 객체 저장소 아카이브를 사용하여 애플리케이션을 복원할 수 있습니다.

.필수 BlueXP 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["BlueXP backup and recovery 액세스 역할에 대해 알아보세요"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^] .

.단계
. BlueXP backup and recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 워크로드를 선택하고 워크로드의 호스트 열에서 *보기*를 선택합니다.
. 애플리케이션 목록에서 복원하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *보기 및 복원*을 선택하세요.
+
복원 지점 목록이 나타납니다.

. 사용하려는 복원 지점에 대한 작업 메뉴를 열고 *복원*을 선택합니다.


[discrete]
===== 일반 설정

. 복원할 소스(로컬, 보조 또는 개체 저장소)를 선택합니다.
. *클러스터* 목록에서 대상 클러스터를 선택합니다.
. 복원 대상 네임스페이스(원래 또는 새 네임스페이스)를 선택합니다.
+
다른 클러스터와 원래 네임스페이스로 복원하는 것은 지원되지 않습니다.

. 다음 * 을 선택합니다.


[discrete]
===== 리소스 선택

. 애플리케이션과 관련된 모든 리소스를 복원할지 아니면 필터를 사용하여 복원할 특정 리소스를 선택할지 선택하세요.


[role="tabbed-block"]
====
.모든 리소스 복원
--
. Restore all resources * 를 선택합니다.
. 다음 * 을 선택합니다.


--
.특정 리소스 복원
--
. *선택적 리소스*를 선택하세요.
. 리소스 필터의 동작을 선택하세요. *포함*을 선택하면 선택한 리소스가 복원됩니다. *제외*를 선택하면 선택한 리소스가 복원되지 않습니다.
. 리소스 선택을 위한 필터를 정의하는 규칙을 추가하려면 *규칙 추가*를 선택하세요. 리소스를 필터링하려면 최소 하나 이상의 규칙이 필요합니다.
+
각 규칙은 리소스 네임스페이스, 레이블, 그룹, 버전, 종류 등의 기준으로 필터링할 수 있습니다.

. 각 규칙을 저장하려면 *저장*을 선택하세요.
. 필요한 규칙을 모두 추가한 후 *검색*을 선택하면 필터 기준과 일치하는 백업 아카이브에서 사용 가능한 리소스를 확인할 수 있습니다.
. 결과에 만족하면 *다음*을 선택하세요.


--
====
[discrete]
===== 목적지 설정

. 기본 저장소 클래스 또는 다른 저장소 클래스로 복원할지 선택합니다.
. 선택적으로, 다른 저장소 클래스로 복원하도록 선택한 경우 각 소스 저장소 클래스와 일치하는 대상 저장소 클래스를 선택하십시오. 대상 저장소 클래스는 대상 클러스터에서 사용 가능해야 합니다.
. Restore * 를 선택합니다.

