---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: BlueXP backup and recovery 사용하면 워크로드 호스트 정보, 데이터베이스 정보 및 인스턴스 정보를 관리할 수 있습니다. 인벤토리의 보호 설정을 확인, 편집 및 삭제할 수 있습니다. 
---
= Kubernetes 애플리케이션 추가 및 보호
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recovery 사용하면 워크로드 호스트 정보, 데이터베이스 정보 및 인스턴스 정보를 관리할 수 있습니다. 인벤토리의 보호 설정을 확인, 편집 및 삭제할 수 있습니다.

.필수 BlueXP 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["BlueXP backup and recovery 액세스 역할에 대해 알아보세요"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^] .



== 새로운 Kubernetes 애플리케이션 추가 및 보호

쿠버네티스 애플리케이션을 보호하는 첫 번째 단계는 BlueXP backup and recovery 내에 애플리케이션을 생성하는 것입니다. 애플리케이션을 생성하면 BlueXP 쿠버네티스 클러스터에서 실행 중인 애플리케이션을 인식하게 됩니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. *신청서 만들기*를 선택하세요.
. 애플리케이션의 이름을 입력하세요.
. 보호하려는 리소스를 검색하려면 다음 필드 중 하나를 선택하세요.
+
** 연관된 클러스터
** 연관된 네임스페이스
** 리소스 유형
** 라벨 선택기


. 선택적으로, 클러스터 수준에서 범위가 지정되고 애플리케이션에 포함되지 않는 리소스를 선택하려면 *클러스터 범위 리소스*를 선택합니다. 이러한 리소스를 포함하면 애플리케이션을 생성할 때 해당 리소스가 애플리케이션에 추가됩니다.
. 검색 기준에 맞는 리소스를 찾으려면 *검색*을 선택하세요.
. BlueXP 검색 기준과 일치하는 리소스 목록을 표시합니다.
. 보호하려는 리소스가 목록에 포함되어 있으면 *다음*을 선택합니다.
. *정책* 영역에서 애플리케이션을 보호하기 위한 기존 보호 정책을 선택하거나 새 정책을 만듭니다.
. *Prescripts and postscripts* 영역에서 백업 작업 전후에 실행할 Prescripts 또는 Postscripts 실행 후크를 활성화하고 구성합니다. Prescripts 또는 Postscripts를 활성화하려면 최소 하나 이상의 link:br-use-manage-execution-hook-templates.html["실행 후크 템플릿"] .
. Create * 를 선택합니다.


.결과
애플리케이션이 생성되어 쿠버네티스 인벤토리의 *애플리케이션* 탭에 있는 애플리케이션 목록에 나타납니다. BlueXP 설정에 따라 애플리케이션을 보호하며, 백업 및 복구의 *모니터링* 영역에서 진행 상황을 모니터링할 수 있습니다.



== 기존 Kubernetes 애플리케이션 보호

이미 추가한 Kubernetes 애플리케이션에서 보호 정책을 활성화합니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. 애플리케이션 목록에서 보호하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. protect * 를 선택합니다.
. *정책* 영역에서 애플리케이션을 보호하기 위한 기존 보호 정책을 선택하거나 새 정책을 만듭니다.
. *Prescripts and postscripts* 영역에서 백업 작업 전 또는 후에 실행할 Prescript 또는 Postscript 실행 후크를 활성화하고 구성합니다. 실행 후크 유형, 사용하는 템플릿, 인수 및 레이블 선택기를 구성할 수 있습니다.
. 완료 * 를 선택합니다.


.결과
BlueXP 사용자 설정에 따라 애플리케이션을 보호하고, 백업 및 복구의 *모니터링* 영역에서 진행 상황을 모니터링할 수 있습니다.



== 지금 Kubernetes 애플리케이션을 백업하세요

향후 백업 및 스냅샷을 위한 기준을 설정하거나 최신 데이터가 보호되도록 Kubernetes 애플리케이션의 백업을 수동으로 생성합니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. 애플리케이션 목록에서 백업하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *지금 백업*을 선택하세요.
. 올바른 애플리케이션 이름이 선택되었는지 확인하세요.
. 정책 목록에서 보호 정책을 선택하세요.
. 백업 * 을 선택합니다.

