---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: BlueXP backup and recovery 사용하면 워크로드 호스트 정보, 데이터베이스 정보 및 인스턴스 정보를 관리할 수 있습니다. 인벤토리의 보호 설정을 확인, 편집 및 삭제할 수 있습니다. 
---
= Kubernetes 애플리케이션 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recovery 사용하면 Kubernetes 애플리케이션과 관련 리소스를 관리할 수 있습니다. Kubernetes 애플리케이션의 보호 설정을 생성, 확인, 편집 및 삭제할 수 있습니다.

.필수 BlueXP 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["BlueXP backup and recovery 액세스 역할에 대해 알아보세요"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^] .



== Kubernetes 애플리케이션 편집

애플리케이션과 연결된 리소스가 변경된 경우 기존 Kubernetes 애플리케이션의 설정을 수정할 수 있습니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. 애플리케이션 목록에서 편집하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. 편집 * 을 선택합니다.
. 이름이나 포함된 리소스 등 애플리케이션 정의에 필요한 변경 사항을 적용합니다.
. 완료되면 *다음*을 선택하세요.
. 보호 설정에 필요한 변경 사항을 적용합니다.
. 완료되면 *완료*를 선택하세요.




== Kubernetes 애플리케이션 보호 해제

더 이상 보호하고 싶지 않은 애플리케이션의 보호를 해제할 수 있습니다. 애플리케이션 보호를 해제하면 BlueXP backup and recovery 해당 애플리케이션의 보호를 중단하지만, 관련된 모든 백업과 스냅샷은 만료될 때까지 보관됩니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. 애플리케이션 목록에서 보호를 해제할 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *보호 해제*를 선택하세요.
. 공지사항을 읽고 준비가 되면 *보호 해제*를 선택하세요.




== Kubernetes 애플리케이션 삭제

더 이상 필요하지 않은 애플리케이션은 삭제할 수 있습니다. 애플리케이션을 삭제하면 BlueXP backup and recovery 해당 애플리케이션 보호를 중단하고, 사용자가 선택한 경우 연결된 모든 백업 및 스냅샷도 삭제됩니다.

.단계
. BlueXP backup and recovery 에서 *인벤토리* > *애플리케이션*을 선택합니다.
. 애플리케이션 목록에서 삭제하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. 삭제 * 를 선택합니다.
. 선택적으로, *스냅샷 및 백업 삭제*를 활성화하여 애플리케이션의 모든 스냅샷과 백업을 제거합니다.
+

CAUTION: 이렇게 하면 해당 스냅샷과 백업을 사용하여 애플리케이션을 더 이상 복원할 수 없습니다.

. 작업을 확인하고 *삭제*를 선택하세요.

