---
sidebar: sidebar 
permalink: concept-clone-cloud-native-oracle-concepts.html 
keywords: cloud native, application data, clone, Cloud Manager, BlueXP, Oracle database, Oracle, clone limitations, clone methods, clone naming scheme, requirements, clone specification file 
summary: 데이터베이스를 클론 복제하기 전에 클론 개념을 이해해야 합니다. 
---
= 클론 개념 및 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
데이터베이스 백업을 사용하여 Oracle 데이터베이스를 소스 데이터베이스 호스트 또는 대체 호스트에 복제할 수 있습니다. 운영 스토리지 시스템에서 백업을 클론 복제할 수 있습니다.

데이터베이스를 클론 복제하기 전에 클론 개념을 이해하고 모든 요구 사항이 충족되었는지 확인해야 합니다.



== Oracle 데이터베이스 클론 생성 요구 사항

Oracle 데이터베이스를 복제하기 전에 필수 구성 요소가 완료되었는지 확인해야 합니다.

* 데이터베이스 백업을 만들어야 합니다. 클론 생성 작업을 성공적으로 수행하려면 온라인 데이터 및 로그 백업을 성공적으로 생성해야 합니다.
* ASM_diskstring 매개 변수에서 다음을 구성해야 합니다.
+
** AFD: * ASMFD를 사용하는 경우
** ORCL: * ASMlib를 사용하는 경우
** /dev/<exact_device_location> ASMUDEV를 사용하는 경우


* 대체 호스트에서 클론을 생성하는 경우 대체 호스트는 다음 요구 사항을 충족해야 합니다.
+
** 대체 호스트에 플러그인을 설치해야 합니다.
** Oracle 소프트웨어는 대체 호스트에 설치해야 합니다.
** iSCSI SAN 스토리지에 상주하는 데이터베이스를 클론 생성하는 경우 클론 호스트에서 스토리지에서 LUN을 검색할 수 있어야 합니다. 대체 호스트에 클론을 생성하는 경우 스토리지와 대체 호스트 간에 iSCSI 세션이 설정되었는지 확인합니다.
** 소스 데이터베이스가 ASM 데이터베이스인 경우:
+
*** ASM 인스턴스는 클론이 수행될 호스트에서 실행 중이어야 합니다.
*** 클론 데이터베이스의 아카이브 로그 파일을 전용 ASM 디스크 그룹에 배치하려면 클론 작업 전에 ASM 디스크 그룹을 프로비저닝해야 합니다.
*** 데이터 디스크 그룹의 이름은 구성할 수 있지만 클론이 수행될 호스트의 다른 ASM 디스크 그룹에서 해당 이름을 사용하지 않도록 해야 합니다.
*** ASM 디스크 그룹에 상주하는 데이터 파일은 클론 워크플로우의 일부로 프로비저닝됩니다.








== 제한 사항

* Qtree에 상주하는 데이터베이스의 복제는 지원되지 않습니다.
* 복제된 데이터베이스 백업은 지원되지 않습니다.




== 복제 방법

기본 방법을 사용하거나 클론 사양 파일을 사용하여 클론을 생성할 수 있습니다.



=== 기본 방법을 사용하여 클론을 생성합니다

소스 데이터베이스와 선택한 백업을 기반으로 기본 구성으로 클론을 생성할 수 있습니다.

* 데이터베이스 매개 변수, 홈 및 OS 사용자는 기본적으로 소스 데이터베이스를 사용합니다.
* 데이터 파일 경로는 선택한 명명 체계에 따라 이름이 지정됩니다.
* 사전 스크립트, 사후 스크립트 및 SQL 문을 지정할 수 없습니다.
* 복구 옵션은 기본적으로 취소까지 * 이며 * 복구를 위해 데이터 백업과 연결된 로그 백업을 사용합니다




=== 사양 파일을 사용하여 클론을 생성합니다

클론 사양 파일에서 구성을 정의하고 이를 사용하여 데이터베이스를 복제할 수 있습니다. 사양 파일을 다운로드하여 요구 사항에 맞게 수정한 다음 파일을 업로드할 수 있습니다. link:task-clone-cloud-native-oracle-data.html["자세한 정보"].

사양 파일에 정의되어 있고 수정할 수 있는 다양한 매개변수는 다음과 같습니다.

|===
| 매개 변수 | 설명 


 a| 
control_files.(제어 파일
 a| 
클론 데이터베이스에 대한 제어 파일의 위치입니다.

제어 파일 수는 소스 데이터베이스와 동일합니다. 제어 파일 경로를 재정의하려면 다른 제어 파일 경로를 제공할 수 있습니다. 파일 시스템 또는 ASM 디스크 그룹이 호스트에 있어야 합니다.



 a| 
REDO_LOGS 를 선택합니다
 a| 
REDO 로그의 위치, 크기, REDO 그룹 수입니다.

데이터베이스를 복제하려면 최소 2개의 REDO 로그 그룹이 필요합니다. redo 로그 파일 경로를 재정의하려면 redo 로그 파일 경로를 소스 데이터베이스와 다른 파일 시스템으로 사용자 지정할 수 있습니다. 파일 시스템이나 ASM 디스크 그룹이 호스트에 있어야 합니다.



 a| 
ORACLE_VERSION
 a| 
타겟 호스트에 있는 Oracle의 버전입니다.



 a| 
ORACLE_HOME
 a| 
타겟 호스트의 Oracle Home입니다.



 a| 
archive_log_mode를 활성화합니다
 a| 
클론 데이터베이스의 아카이브 로그 모드를 제어합니다



 a| 
database_parameters 를 선택합니다
 a| 
복제된 데이터베이스에 대한 데이터베이스 매개 변수입니다



 a| 
sql_statements 를 참조하십시오
 a| 
클론 생성 후 데이터베이스에서 실행할 SQL 문입니다



 a| 
OS_USER_DETAIL
 a| 
타겟 클론 데이터베이스의 Oracle OS 사용자입니다



 a| 
database_port 를 선택합니다
 a| 
호스트에서 OS 인증이 비활성화된 경우 데이터베이스와 통신하는 데 사용되는 포트입니다.



 a| 
ASM_PORT
 a| 
create clone input에 자격 증명이 제공된 경우 ASM 데이터베이스와 통신하는 데 사용되는 포트입니다.



 a| 
skip_recovery 를 선택합니다
 a| 
복구 작업을 수행하지 않습니다.



 a| 
SCN 까지
 a| 
데이터베이스를 지정된 SCN(시스템 변경 번호)까지 복구합니다.



 a| 
종료 시간
 a| 
데이터베이스를 지정된 날짜 및 시간까지 복구합니다.

허용되는 형식은 _mm/dd/yyyy hh:mm:ss_입니다.



 a| 
취소 시까지(_C)
 a| 
클론 생성을 위해 선택한 데이터 백업과 연결된 로그 백업을 마운트하여 복구합니다.

로그 파일이 없거나 손상될 때까지 복제된 데이터베이스가 복구됩니다.



 a| 
log_paths 를 참조하십시오
 a| 
복제된 데이터베이스를 복구하는 데 사용할 아카이브 로그 경로의 추가 위치입니다.



 a| 
source_location을 선택합니다
 a| 
소스 데이터베이스 호스트의 디스크 그룹 또는 마운트 지점의 위치입니다.



 a| 
clone_location을 선택합니다
 a| 
소스 위치에 해당하는 타겟 호스트에서 생성해야 하는 디스크 그룹 또는 마운트 지점의 위치입니다.



 a| 
location_type을 입력합니다
 a| 
ASM_diskgroup 또는 마운트 지점이 될 수 있습니다.

이 값은 파일을 다운로드할 때 자동으로 채워집니다. 이 매개 변수를 편집하면 안 됩니다.



 a| 
pre_script(사전 스크립트)
 a| 
클론을 생성하기 전에 타겟 호스트에서 실행할 스크립트입니다.



 a| 
post_script 를 입력합니다
 a| 
클론을 생성한 후 타겟 호스트에서 실행할 스크립트입니다.



 a| 
경로
 a| 
클론 호스트에 있는 스크립트의 절대 경로입니다.

스크립트는 /var/opt/snapcenter/spl/scripts 또는 이 경로 내의 폴더에 저장해야 합니다.



 a| 
시간 초과
 a| 
타겟 호스트에서 실행 중인 스크립트에 대해 지정된 시간 초과 시간입니다.



 a| 
인수
 a| 
스크립트에 지정된 인수입니다.

|===


== 클론 명명 체계

클론 명명 체계는 클론 생성된 데이터베이스의 마운트 지점 및 디스크 그룹 이름을 정의합니다. 동일한 * 또는 * 자동 생성 * 을 선택할 수 있습니다.



=== 동일한 명명 체계

클론 명명 체계를 * 동일 * 으로 선택하면 마운트 지점의 위치와 클론 생성된 데이터베이스의 디스크 그룹 이름이 소스 데이터베이스와 동일합니다.

예를 들어, 소스 데이터베이스의 마운트 지점이 _/NetApp_sourcedb/data_1, +Data1_DG_인 경우 클론 복제된 데이터베이스의 마운트 지점은 SAN의 NFS 및 ASM에 대해 동일하게 유지됩니다.

* 제어 파일 및 redo 파일의 수와 경로 같은 구성은 소스와 동일합니다.
+

NOTE: REDO 로그 또는 제어 파일 경로가 비 데이터 볼륨에 있는 경우 사용자는 ASM 디스크 그룹 또는 마운트 지점을 타겟 호스트에 프로비저닝해야 합니다.

* Oracle OS 사용자 및 Oracle 버전은 소스 데이터베이스와 동일합니다.
* 클론 스토리지 볼륨 이름은 sourceVolNameSCS_Clone_CurrentTimeStampNumber 형식으로 지정됩니다.
+
예를 들어 소스 데이터베이스의 볼륨 이름이 _sourceVolName_인 경우 복제된 볼륨 이름은 _sourceVolNameSCS_Clone_1661420020304608825_가 됩니다.

+

NOTE: CurrentTimeStamNumber _ 는 볼륨 이름의 고유성을 제공합니다.





=== 자동으로 생성된 명명 체계

클론 생성 스키마를 * Auto-Generated * 로 선택하면 마운트 지점의 위치와 클론 데이터베이스의 디스크 그룹 이름에 접미사가 추가됩니다.

* 기본 클론 방법을 선택한 경우 접미사가 * 클론 SID * 가 됩니다.
* 지정 파일 방법을 선택한 경우 접미사는 클론 사양 파일을 다운로드하는 동안 지정된 * 접미사 * 가 됩니다.


예를 들어 소스 데이터베이스의 마운트 지점이 _/netapp_sourcedb/data_1_이고 * 클론 SID * 또는 * 접미사 * 가 _HR_인 경우 복제된 데이터베이스의 마운트 지점은 _/netapp_sourcedb/data_1_HR_입니다.

* 제어 파일 및 redo 로그 파일 수는 소스와 동일합니다.
* 모든 REDO 로그 파일 및 제어 파일은 복제된 데이터 마운트 지점 중 하나 또는 데이터 ASM 디스크 그룹에 위치합니다.
* 클론 스토리지 볼륨 이름은 sourceVolNameSCS_Clone_CurrentTimeStampNumber 형식으로 지정됩니다.
+
예를 들어 소스 데이터베이스의 볼륨 이름이 _sourceVolName_인 경우 복제된 볼륨 이름은 _sourceVolNameSCS_Clone_1661420020304608825_가 됩니다.

+

NOTE: CurrentTimeStamNumber _ 는 볼륨 이름의 고유성을 제공합니다.

* NAS 마운트 지점의 형식은 _SourceNASMountPoint_suffix_입니다.
* ASM 디스크 그룹의 형식은 _SourceDiskgroup_suffix_입니다.
+

NOTE: 클론 diskgroup의 문자 수가 25보다 크면 _SC_hashcode_suffix_가 됩니다.





== 데이터베이스 매개 변수

다음 데이터베이스 매개 변수의 값은 클론 명명 체계와 관계없이 소스 데이터베이스의 값과 동일합니다.

* log_archive_format 을 참조하십시오
* audit_trail을 선택합니다
* 프로세스
* pga_aggregate_target 을 선택합니다
* remote_login_passwordfile 을 참조하십시오
* undo_tablespace 를 선택합니다
* open_cursors
* SGA_TARGET
* db_block_size를 입력합니다


다음 데이터베이스 매개 변수의 값은 클론 SID를 기반으로 접미사와 함께 추가됩니다.

* audit_file_dest={sourcedatabase_parametervalue}_suffix입니다
* log_archive_dest_1={sourcedatabase_oraclehome}_suffix




== 클론별 정의 정의 정의 지정 및 PS에 대해 지원되는 사전 정의된 환경 변수입니다

데이터베이스를 복제하는 동안 처방과 PS를 실행할 때 지원되는 미리 정의된 환경 변수를 사용할 수 있습니다.

* sc_original_SID는 소스 데이터베이스의 SID를 지정합니다. 이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다. 예: NFSB32
* sc_original_host는 소스 호스트의 이름을 지정합니다. 이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다. 예: asmrac1.gdl.englab.netapp.com
* SC_ORACLE_HOME은 대상 데이터베이스의 Oracle 홈 디렉토리 경로를 지정합니다. 예: /ora01/app/oracle/product/18.1.0/db_1
* sc_backup_name은 백업의 이름을 지정합니다. 이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다. 예:
+
** 데이터베이스가 ARCHIVELOG 모드에서 실행되지 않는 경우: data@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** 데이터베이스가 ARCHIVELOG 모드에서 실행 중인 경우: data@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|log@RG2_scspr2417819002_07-20-2021_12.16.48.48.98.9267_1, RG2_12.919002_16.7_27_2267_2021-48.27_2267_207_2021


* sc_original_os_user 소스 데이터베이스의 운영 체제 소유자를 지정합니다. 예: Oracle
* sc_original_OS_group은 소스 데이터베이스의 운영 체제 그룹을 지정합니다. 예: oinstall
* SC_TARGET_SID는 복제된 데이터베이스의 SID를 지정합니다. PDB 복제 워크플로우의 경우 이 매개 변수의 값은 사전 정의되지 않습니다. 이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다. 예: clonedb
* SC_TARGET_HOST는 데이터베이스를 복제할 호스트의 이름을 지정합니다. 이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다. 예: asmrac1.gdl.englab.netapp.com
* SC_TARGET_OS_USER는 복제된 데이터베이스의 운영 체제 소유자를 지정합니다. PDB 복제 워크플로우의 경우 이 매개 변수의 값은 사전 정의되지 않습니다. 예: Oracle
* SC_TARGET_OS_GROUP은 복제된 데이터베이스의 운영 체제 그룹을 지정합니다. PDB 복제 워크플로우의 경우 이 매개 변수의 값은 사전 정의되지 않습니다. 예: oinstall
* SC_TARGET_DB_PORT는 복제된 데이터베이스의 데이터베이스 포트를 지정합니다. PDB 복제 워크플로우의 경우 이 매개 변수의 값은 사전 정의되지 않습니다. 예: 1521




=== 지원되는 구분 기호

* @는 데이터를 데이터베이스 이름과 분리하고 값을 키와 분리하는 데 사용됩니다. 예: data@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
* 는 SC_BACKUP_NAME 매개 변수에 대해 서로 다른 두 엔터티 간에 데이터를 분리하는 데 사용됩니다. 예: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
* , 은 같은 키에 대한 변수 집합을 구분하는 데 사용됩니다. 예: data@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | log@RG2_scspr2417819002_07-20-2021_12.16.4267_1, RG2_scprsprs2417819002_07-21-21-2021_12.48.9267_1, squ2287_2407_2407_2427_2407_24222_242267_42.722_242267_1

