---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 운영 환경, BlueXP 커넥터, BlueXP 계정의 준비 상태를 확인하여 BlueXP backup and recovery 시작하세요. BlueXP backup and recovery 사용하려면 다음 전제 조건이 필요합니다. 
---
= BlueXP backup and recovery 필수 구성 요소
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
운영 환경, BlueXP 커넥터, BlueXP 계정의 준비 상태를 확인하여 BlueXP backup and recovery 시작하세요. BlueXP backup and recovery 사용하려면 다음 전제 조건이 필요합니다.



== ONTAP 9.8 이상

온프레미스 ONTAP 인스턴스에서 ONTAP One 라이선스를 활성화해야 합니다.



== 개체 스토리지에 대한 백업의 경우

백업 대상으로 개체 스토리지를 사용하려면 AWS S3, Microsoft Azure Blob, StorageGRID 또는 ONTAP 계정과 적절한 액세스 권한이 구성되어 있어야 합니다.

* link:prev-ontap-protect-overview.html["ONTAP 볼륨 데이터를 보호합니다"]
* link:br-use-mssql-protect-overview.html["Microsoft SQL Server 데이터베이스를 보호하세요"]
* link:prev-vmware-protect-overview.html["가상 머신 워크로드 보호"]




== BlueXP 에서

* BlueXP 사용자는 Microsoft SQL Server 워크로드에 대한 작업을 수행하는 데 필요한 역할과 권한을 보유해야 합니다. 리소스를 검색하려면 BlueXP backup and recovery 역할(Super admin)이 있어야 합니다. 자세한 내용은 다음을 참조하세요. link:reference-roles.html["BlueXP backup and recovery 역할 기반 기능 액세스"] BlueXP backup and recovery 작업을 수행하는 데 필요한 역할과 권한에 대한 자세한 내용은 다음을 참조하세요.
* 온프레미스 ONTAP 클러스터 또는 Cloud Volumes ONTAP 에 연결되는 활성 BlueXP 커넥터가 하나 이상 있는 BlueXP 조직입니다. 아래 *초기 미리보기 설정 프로세스*를 참조하세요.
* NetApp 온프레미스 ONTAP 또는 Cloud Volumes ONTAP 클러스터가 있는 BlueXP 작업 환경이 하나 이상 있어야 합니다.
* BlueXP 커넥터
+
 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["BlueXP  커넥터를 구성하는 방법에 대해 알아봅니다"]및 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["표준 BlueXP 요구사항"^]을 참조하십시오.

+
** Preview 버전에서는 커넥터에 Ubuntu 22.04 LTS 운영 체제가 필요합니다.






=== BlueXP를 설정합니다

다음 단계는 BlueXP 와 BlueXP backup and recovery 서비스를 설정하는 것입니다.

 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["표준 BlueXP 요구사항"^]검토.



=== BlueXP Connector를 생성합니다

이 서비스를 체험하려면 NetApp 제품 팀에 문의하세요. BlueXP Connector를 사용하면 서비스에 적합한 기능이 여기에 포함됩니다.

서비스를 사용하기 전에 BlueXP 에서 커넥터를 생성하려면 에 설명된 BlueXP  설명서를 참조하십시오. https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["BlueXP Connector를 생성하는 방법"^]

.BlueXP 커넥터를 설치할 위치
복원 작업을 완료하려면 다음 위치에 커넥터를 설치할 수 있습니다.

ifdef::aws[]

* Amazon S3의 경우 커넥터를 사내에 배포할 수 있습니다.


endif::aws[]

ifdef::azure[]

* Azure Blob의 경우 커넥터를 온프레미스에 배포할 수 있습니다.


endif::azure[]

ifdef::gcp[]

endif::gcp[]

* StorageGRID 의 경우, 인터넷 접속 여부와 관계없이 커넥터를 사내에 배포해야 합니다.
* ONTAP S3의 경우 커넥터를 온프레미스(인터넷 액세스 유무에 관계없이) 또는 클라우드 공급자 환경에 배포할 수 있습니다



NOTE: "온프레미스 ONTAP 시스템"에 대한 참조에는 FAS 및 AFF 시스템이 포함됩니다.



== Microsoft SQL Server 호스트 요구 사항

SQL Server 워크로드에 BlueXP backup and recovery 사용하려면 다음과 같은 호스트 시스템, 공간 및 크기 조정 전제 조건이 필요합니다.

[cols="33,66a"]
|===
| 항목 | 요구 사항 


| 운영 체제  a| 
Microsoft Windows 지원되는 버전에 대한 최신 정보는 다음을 참조하세요.  https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 상호 운용성 매트릭스 툴"^] .



| Microsoft SQL Server 버전  a| 
2012 이상 버전은 VMware Virtual Machine File System(VMFS) 및 VMware Virtual Machine Disk(VMDK) NFS를 지원합니다.



| SnapCenter 서버 버전  a| 
SnapCenter 에서 BlueXP backup and recovery 로 기존 데이터를 가져오려면 SnapCenter Server 버전 5.0 이상이 필요합니다.


NOTE: 이미 SnapCenter 가 있는 경우 SnapCenter 에서 가져오기 전에 먼저 필수 구성 요소를 충족했는지 확인하세요. 을 link:concept-start-prereq-snapcenter-import.html["SnapCenter 에서 리소스를 가져오기 위한 전제 조건"]참조하십시오.



| SQL Server 호스트의 플러그인에 대한 최소 RAM  a| 
1GB



| SQL Server 호스트의 플러그인에 대한 최소 설치 및 로그 공간  a| 
5GB

충분한 디스크 공간을 할당하고 로그 폴더의 저장 공간 사용량을 모니터링하십시오. 필요한 로그 공간은 수행되는 백업 횟수와 데이터 보호 작업 빈도에 따라 달라집니다. 공간이 충분하지 않으면 작업에 대한 로그가 생성되지 않습니다.



| 필요한 소프트웨어 패키지  a| 
* ASP.NET Core Runtime 8.0.12 호스팅 번들(및 모든 후속 8.0.x 패치)
* PowerShell 코어 7.4.2


지원되는 버전에 대한 최신 정보는 를 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 상호 운용성 매트릭스 툴"^]참조하십시오.

|===