---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp BlueXP backup and recovery 통해 VMware 워크로드를 보호하세요. 
---
= BlueXP backup and recovery 와 함께 사용할 SnapCenter Plug-in for VMware vSphere 등록
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
데이터스토어와 가상 머신이 표시되도록 BlueXP 백업 및 복구에서 VMware vSphere 호스트용 SnapCenter 플러그인을 등록해야 합니다. 관리 액세스 권한이 있는 사용자만 VMware vSphere 호스트용 SnapCenter 플러그인을 등록할 수 있습니다.

[]
====
*참고* BlueXP backup and recovery 워크로드로 전환하려면 다음을 참조하세요. link:br-start-switch-ui.html["다양한 BlueXP backup and recovery 워크로드로 전환"] .

====
.단계
. BlueXP UI에서 *보호* > *백업 및 복구* > *가상 머신*을 선택합니다.
. *설정* 드롭다운에서 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.
. * SnapCenter Plug-in for VMware vSphere 등록*을 선택합니다.
. 다음 세부 정보를 지정합니다.
+
.. VMware vSphere용 SnapCenter 플러그인 필드에서 VMware vSphere 호스트용 SnapCenter 플러그인의 FQDN 또는 IP 주소를 지정합니다.
.. 포트 필드에서 VMware vSphere 호스트용 SnapCenter 플러그인이 실행되고 있는 포트 번호를 지정합니다.
+
기본 8144 포트에서 실행 중인 온프레미스 SnapCenter Plug-in for VMware vSphere 호스트와 클라우드 공급자(Amazon Web Services, Microsoft Azure, Google Cloud Platform) 또는 온프레미스에서 실행 가능한 BlueXP Connector 인스턴스 간에 통신이 열려 있는지 확인해야 합니다.

.. 사용자 이름 및 암호 필드에서 관리자 역할을 가진 vCenter 사용자의 자격 증명을 지정합니다.


. Register * 를 선택합니다.


* 완료 후 *

등록된 SnapCenter Plug-in for VMware vSphere 사용하여 보호되는 모든 데이터 저장소와 가상 머신을 보려면 *백업 및 복구* > *가상 머신*을 선택하세요.
