---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp BlueXP backup and recovery 통해 VMware 워크로드를 보호하세요. 
---
= BlueXP backup and recovery 에서 데이터 저장소를 백업하기 위한 정책을 만듭니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 백업 및 복구에서 사용 가능한 다음 사전 정의된 정책 중 하나를 사용하거나 정책을 만들 수 있습니다.

[]
====
*참고* BlueXP backup and recovery 워크로드로 전환하려면 다음을 참조하세요. link:br-start-switch-ui.html["다양한 BlueXP backup and recovery 워크로드로 전환"] .

====
.시작하기 전에
* 미리 정의된 정책을 편집하지 않으려면 정책을 만들어야 합니다.
* 오브젝트 저장소에서 아카이브 스토리지로 백업을 이동하려면 ONTAP 9.10.1 이상을 실행해야 하며 Amazon Web Services 또는 Microsoft Azure가 클라우드 공급자가 되어야 합니다.
* 각 클라우드 공급자에 대해 아카이브 액세스 계층을 구성해야 합니다.


.이 작업에 대해
BlueXP에서 다음과 같은 사전 정의된 정책을 사용할 수 있습니다.

|===
| 정책 이름 | 라벨 | 보존 값 


 a| 
1년 일별 LTR(장기 보존)
 a| 
매일
 a| 
366



 a| 
5년 일일 LTR
 a| 
매일
 a| 
1830



 a| 
7년 주간 LTR
 a| 
매주
 a| 
370



 a| 
10년 월간 LTR
 a| 
매월
 a| 
120

|===
.단계
. 가상 머신 페이지의 설정 드롭다운 목록에서 * 정책 * 을 선택합니다.
. Create policy * 를 선택합니다.
. 정책 세부 정보 섹션에서 정책 이름을 지정합니다.
. 보존 섹션에서 보존 유형 중 하나를 선택하고 보존할 백업 수를 지정합니다.
. 백업 스토리지 소스로 운영 또는 2차 를 선택합니다.
. (선택 사항) 비용 최적화를 위해 일정 일 후에 오브젝트 저장소에서 아카이브 스토리지로 백업을 이동하려면 * Tier Backups to Archival * 확인란을 선택하고 백업을 아카이빙해야 하는 일 수를 입력합니다.
. Create * 를 선택합니다.
+

NOTE: 데이터 저장소와 연결된 정책은 편집하거나 삭제할 수 없습니다.


