---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: '"프라이빗 모드"라고 하는 인터넷 액세스가 없는 사이트에서 BlueXP 백업 및 복구를 사용하는 경우, BlueXP 백업 및 복구 구성 데이터는 백업이 저장되는 StorageGRID 또는 ONTAP S3 버킷에 백업됩니다. 향후 BlueXP 커넥터 호스트 시스템에 문제가 있을 경우 새 커넥터를 배포하고 중요한 BlueXP 백업 및 복구 데이터를 복원할 수 있습니다.' 
---
= 어두운 사이트에서 BlueXP 백업 및 복구 데이터를 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
"프라이빗 모드"라고 하는 인터넷 액세스가 없는 사이트에서 BlueXP 백업 및 복구를 사용하는 경우, BlueXP 백업 및 복구 구성 데이터는 백업이 저장되는 StorageGRID 또는 ONTAP S3 버킷에 백업됩니다. 향후 BlueXP 커넥터 호스트 시스템에 문제가 있을 경우 새 커넥터를 배포하고 중요한 BlueXP 백업 및 복구 데이터를 복원할 수 있습니다.

BlueXP Connector가 클라우드 공급업체에 배포되거나 인터넷에 액세스할 수 있는 자체 호스트 시스템에 구축된 SaaS 환경에서 BlueXP 백업 및 복구를 사용하는 경우 중요한 모든 BlueXP 백업 및 복구 구성 데이터가 클라우드에서 백업 및 보호됩니다. Connector에 문제가 있는 경우 새 Connector를 생성하고 작업 환경을 추가하면 백업 세부 정보가 자동으로 복원됩니다.

다음 두 가지 유형의 데이터가 백업됩니다.

* BlueXP 백업 및 복구 데이터베이스 - 모든 볼륨, 백업 파일, 백업 정책 및 구성 정보 목록이 포함되어 있습니다.
* 인덱싱된 카탈로그 파일 - 복원하려는 볼륨 데이터를 찾을 때 검색 및 복원 기능에 사용되는 자세한 인덱스를 포함합니다.


이 데이터는 자정에 하루에 한 번 백업되며 각 파일의 최대 30개 사본이 보존됩니다. 커넥터가 여러 온-프레미스 ONTAP 작업 환경을 관리하는 경우 BlueXP 백업 및 복구 파일은 먼저 활성화된 작업 환경의 버킷에 위치합니다.


TIP: 볼륨 데이터는 BlueXP 백업 및 복구 데이터베이스 또는 인덱싱된 카탈로그 파일에 포함되지 않습니다.



== BlueXP 백업 및 복구 데이터를 새 커넥터로 복원합니다

온-프레미스 커넥터에 심각한 장애가 발생한 경우 새 커넥터를 설치한 다음 BlueXP 백업 및 복구 데이터를 새 커넥터에 복원해야 합니다.

BlueXP 백업 및 복구 시스템을 작동 상태로 되돌리기 위해 수행해야 하는 4가지 작업은 다음과 같습니다.

* 새 BlueXP 커넥터를 설치합니다
* BlueXP 백업 및 복구 데이터베이스를 복원합니다
* 인덱싱된 카탈로그 파일을 복원합니다
* 모든 온프레미스 ONTAP 시스템과 StorageGRID 시스템을 BlueXP UI로 재검색합니다


시스템이 정상적으로 작동하는지 확인한 후에는 새 백업 파일을 생성하는 것이 좋습니다.

.필요한 것
백업 파일이 저장되는 StorageGRID 또는 ONTAP S3 버킷에서 최신 데이터베이스 및 인덱스 백업에 액세스해야 합니다.

* BlueXP 백업 및 복구 MySQL 데이터베이스 파일
+
이 파일은 버킷의 다음 위치에 있습니다 `netapp-backup-<GUID>/mysql_backup/`, 그리고 이름은 이다 `CBS_DB_Backup_<day>_<month>_<year>.sql`.

* 인덱싱된 카탈로그 백업 zip 파일
+
이 파일은 버킷의 다음 위치에 있습니다 `netapp-backup-<GUID>/catalog_backup/`, 그리고 이름은 이다 `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`.





=== 새로운 온프레미스 Linux 호스트에 새 커넥터를 설치합니다

새 BlueXP 커넥터를 설치할 때 원래 커넥터에 설치한 것과 동일한 소프트웨어 릴리스를 다운로드해야 합니다. BlueXP 백업 및 복구 데이터베이스 구조를 정기적으로 변경하면 새 소프트웨어 릴리스가 원래 데이터베이스 백업과 호환되지 않을 수 있습니다. 가능합니다 https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#upgrade-the-connector-on-prem-without-internet-access["백업 데이터베이스를 복원한 후 Connector 소프트웨어를 최신 버전으로 업그레이드합니다"^].

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["새로운 사내 Linux 호스트에 BlueXP 커넥터를 설치합니다"^]
. 방금 만든 관리자 자격 증명을 사용하여 BlueXP에 로그인합니다.




=== BlueXP 백업 및 복구 데이터베이스를 복원합니다

. 백업 위치에서 새 커넥터 호스트로 MySQL 백업을 복사합니다. 아래의 예제 파일 이름 "CBS_DB_Backup_23_05_2023.sql"을 사용합니다.
. 다음 명령을 사용하여 MySQL Docker 컨테이너에 백업을 복사합니다.
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. 다음 명령을 사용하여 MySQL 컨테이너 셸을 입력합니다.
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. 컨테이너 셸에서 "env"를 배포합니다.
. MySQL DB 패스워드가 필요합니다. 따라서 "mysql_root_password" 키의 값을 복사합니다.
. 다음 명령을 사용하여 BlueXP 백업 및 복구 MySQL DB를 복원합니다.
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. 다음 SQL 명령을 사용하여 BlueXP 백업 및 복구 MySQL DB가 올바르게 복원되었는지 확인합니다.
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
암호를 입력합니다.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
표시된 볼륨이 원래 환경에 있던 볼륨과 동일한지 확인합니다.





=== 인덱싱된 카탈로그 파일을 복원합니다

. 인덱싱된 카탈로그 백업 zip 파일을 복사합니다. 예제 파일 이름 "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip"을 백업 위치에서 "/opt/application/NetApp/CBS" 폴더의 새 커넥터 호스트로 사용합니다.
. 다음 명령을 사용하여 "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip" 파일의 압축을 풉니다.
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. ls * 명령을 실행하여 "catalogdb1" 폴더가 하위 폴더 아래에 "changes" 및 "snapshots"와 함께 생성되었는지 확인하십시오.




=== ONTAP 클러스터와 StorageGRID 시스템에 대해 알아보십시오

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["온프레미스 ONTAP 작업 환경을 모두 살펴보십시오"^] 이전 환경에서 사용할 수 있었습니다. 여기에는 S3 서버로 사용한 ONTAP 시스템이 포함됩니다.
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID 시스템에 대해 알아보십시오"^].




=== StorageGRID 환경 세부 정보를 설정합니다

을 사용하여 원래 커넥터 설정에 설정했던 ONTAP 작업 환경과 연관된 StorageGRID 시스템의 세부 정보를 추가합니다 https://docs.netapp.com/us-en/bluexp-automation/index.html["BlueXP API"^].

데이터를 StorageGRID에 백업하는 각 ONTAP 시스템에 대해 이러한 단계를 수행해야 합니다.

. 다음 OAuth/token API를 사용하여 인증 토큰을 추출합니다.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
이 API는 다음과 같은 응답을 반환합니다. 아래와 같이 인증 토큰을 검색할 수 있습니다.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Tenancy/external/resource API를 사용하여 작업 환경 ID와 X-Agent-ID를 추출합니다.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
이 API는 다음과 같은 응답을 반환합니다. "resourceIdentifier" 아래의 값은 _WorkingEnvironment ID_를 나타내며 "AGENTID" 아래의 값은 _x-agent-id_를 나타냅니다.

. 작업 환경과 관련된 StorageGRID 시스템의 세부 정보로 BlueXP 백업 및 복구 데이터베이스를 업데이트합니다. 아래와 같이 StorageGRID의 정규화된 도메인 이름과 액세스 키 및 스토리지 키를 입력해야 합니다.
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== BlueXP 백업 및 복구 설정을 확인합니다

. 각 ONTAP 작업 환경을 선택하고 오른쪽 패널의 백업 및 복구 서비스 옆에 있는 * 백업 보기 * 를 클릭합니다.
+
볼륨에 대해 생성된 모든 백업을 볼 수 있어야 합니다.

. 복원 대시보드의 검색 및 복원 섹션에서 * 인덱싱 설정 * 을 클릭합니다.
+
인덱싱된 카탈로그 기능이 활성화된 작업 환경이 이전에 활성화된 상태로 유지되는지 확인합니다.

. Search & Restore 페이지에서 몇 가지 카탈로그 검색을 실행하여 인덱싱된 카탈로그 복원이 성공적으로 완료되었는지 확인합니다.

