---
sidebar: sidebar 
permalink: reference-google-backup-tiers.html 
keywords: google, storage classes, archive 
summary: Cloud Backup은 하나의 Google 아카이브 스토리지 클래스와 대부분의 영역을 지원합니다. 
---
= Google 아카이브 스토리지 클래스 및 복원 검색 시간
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup은 하나의 Google 아카이브 스토리지 클래스와 대부분의 영역을 지원합니다.



== Cloud Backup에 지원되는 Google 아카이브 스토리지 클래스입니다

백업 파일이 처음 생성되면 파일이 _Standard_storage에 저장됩니다. 이 계층은 자주 액세스하지 않는 데이터를 저장하는 데 최적화되어 있지만 이를 즉시 액세스할 수도 있습니다.

사내 클러스터에서 ONTAP 9.12.1 이상을 사용하는 경우 추가 비용 최적화를 위해 특정 일(일반적으로 30일 이상) 후에 클라우드 백업 UI의 _Archive_storage에 이전 백업을 계층화하도록 선택할 수 있습니다. 이 계층의 데이터는 높은 검색 비용이 필요하므로 이러한 아카이브 백업 파일에서 데이터를 복원해야 하는 빈도를 고려해야 합니다. 에 대한 섹션을 참조하십시오 <<아카이브 스토리지에서 데이터 복원,아카이브 스토리지에서 데이터 복원>>.

이러한 유형의 수명주기 규칙을 사용하여 Cloud Backup을 구성할 때는 Google 계정에서 버킷을 설정할 때 라이프사이클 규칙을 구성하지 않아야 합니다.

https://cloud.google.com/storage/docs/storage-classes["Google 스토리지 클래스에 대해 알아보십시오"^].



== 아카이브 스토리지에서 데이터 복원

아카이브 스토리지에 오래된 백업 파일을 저장하는 것은 표준 스토리지에 비해 훨씬 저렴하지만, 복원 작업을 위해 아카이브 스토리지에 있는 백업 파일의 데이터에 액세스하는 데는 시간이 약간 더 오래 걸리고 비용이 더 많이 듭니다.

Google Archive에서 데이터를 복원하는 데 비용이 얼마나 드나요?:: 지역별 Google Cloud Storage에 대한 자세한 가격을 보려면 를 방문하십시오 https://cloud.google.com/storage/pricing["Google Cloud Storage 가격 페이지"^].
Google Archive에 보관된 개체를 복원하는 데 시간이 얼마나 걸립니까?:: 총 복원 시간을 구성하는 두 가지 부분이 있습니다.
+
--
* * 검색 시간 *: 아카이브에서 백업 파일을 검색하여 표준 저장소에 저장하는 시간입니다. 이를 "재수화" 시간이라고도 합니다. 다른 클라우드 공급자가 제공하는 "가장 사용 빈도가 낮은" 스토리지 솔루션과 달리 밀리초 이내에 데이터에 액세스할 수 있습니다.
* * 복원 시간 *: 표준 저장소의 백업 파일에서 데이터를 복원하는 시간입니다. 이 시간은 아카이브 계층을 사용하지 않을 때 표준 스토리지에서 직접 수행하는 일반적인 복원 작업과 다르지 않습니다.


--

