---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, backup, restore, backup and recovery 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== ONTAP 볼륨에 대한 백업 및 복구 제한 사항

* BlueXP  백업 및 복구 Cloud Volume ONTAP를 AWS 중국 지역(베이징 및 Ningxia 포함)의 오브젝트 저장소에 백업하지만, 먼저 ID 및 액세스 관리(IAM) 정책을 수동으로 수정해야 할 수 있습니다.
+
AWS에서 커넥터를 생성하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["AWS에 커넥터 설치"^]참조하십시오.

+
블로그 게시물에 대한 자세한 내용은 을 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["BlueXP  백업 및 복구 기능 블로그 2023년 5월"^]참조하십시오.

* BlueXP  백업 및 복구는 Microsoft Azure 중국 지역을 지원하지 않습니다.
+
Azure에서 커넥터를 만드는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-bluexp.html["Azure에 커넥터 설치"^]참조하십시오.

* BlueXP  백업 및 복구는 FlexCache 볼륨의 백업을 지원하지 않습니다.




=== 복제 제한 사항

* 복제를 위해 한 번에 하나의 FlexGroup 볼륨만 선택할 수 있습니다. 각 FlexGroup 볼륨에 대해 백업을 별도로 활성화해야 합니다.
+
FlexVol 볼륨에는 제한이 없습니다. 작업 환경에서 모든 FlexVol 볼륨을 선택하고 동일한 백업 정책을 할당할 수 있습니다.

* 에서 지원되는 기능은 다음과 같습니다 https://docs.netapp.com/us-en/bluexp-replication/index.html["BlueXP 복제 서비스"]하지만 BlueXP 백업 및 복구의 복제 기능을 사용할 때는 그렇지 않습니다.
+
** 볼륨 A에서 볼륨 B로, 볼륨 B에서 볼륨 C로 복제가 수행되는 다중 구간 구성에는 지원되지 않습니다 볼륨 A에서 볼륨 B로의 복제가 지원됩니다
** ONTAP 시스템의 경우 FSx에서 데이터를 복제하거나 FSx에서 데이터를 복제할 수 없습니다.
** 볼륨의 일회성 복제를 생성하는 기능은 지원되지 않습니다.


* 온프레미스 ONTAP 시스템에서 복제를 생성할 때 대상 Cloud Volumes ONTAP 시스템의 ONTAP 버전이 9.8, 9.9 또는 9.11인 경우 미러 볼트 정책만 허용됩니다.




=== 오브젝트로 백업 제한 사항

* 데이터를 백업할 때 BlueXP  백업 및 복구에서는 NVE(NetApp Volume Encryption)가 유지되지 않습니다. 즉, 데이터가 타겟으로 전송되는 동안 NVE 볼륨의 암호화된 데이터는 해독되고 암호화가 유지되지 않습니다.
+
이러한 암호화 유형에 대한 설명은 을 https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["NetApp 볼륨 암호화 구성 개요"^]참조하십시오.



* SnapMirror 정책의 스케줄을 사용하여 SnapMirror 대상 볼륨에 장기 보존 스냅샷이 설정된 경우, 스냅샷이 대상 볼륨에 직접 생성됩니다. 이 경우 BlueXP  백업 및 복구를 사용하여 이러한 볼륨을 백업하지 마십시오. 이러한 스냅샷은 객체 스토리지로 이동하지 않습니다.
* 정책에 할당된 볼륨이 없을 때 백업 정책을 생성하거나 편집하는 경우 보존되는 백업의 수는 최대 1018개입니다. 정책에 볼륨을 할당한 후 정책을 편집하여 최대 4000개의 백업을 생성할 수 있습니다.
* 데이터 보호(DP) 볼륨 백업 시:
+
** SnapMirror 레이블 'app_consistent' 및 'all_source_snapshot'과의 관계는 클라우드에 백업되지 않습니다.
** 사용된 SnapMirror 레이블과 관계없이 SnapMirror 대상 볼륨에 스냅샷의 로컬 복사본을 생성하는 경우 이러한 스냅샷은 백업으로 클라우드로 이동하지 않습니다. 이때 BlueXP 백업 및 복구를 위해 소스 DP 볼륨에 원하는 레이블이 있는 스냅샷 정책을 생성해야 합니다.


* FlexGroup 볼륨 백업은 아카이브 스토리지로 이동할 수 없습니다.
* FlexGroup 볼륨 백업은 클러스터에서 ONTAP 9.13.1 이상을 실행하는 경우 DataLock 및 랜섬웨어 보호를 사용할 수 있습니다.
* SVM-DR 볼륨 백업은 다음 제한 사항으로 지원됩니다.
+
** 백업은 ONTAP 보조 백업에서만 지원됩니다.
** 볼륨에 적용되는 스냅샷 정책은 일별, 주별, 월별 등을 포함하여 BlueXP 백업 및 복구에서 인식하는 정책 중 하나여야 합니다 기본 "sm_created" 정책(* 미러 모든 스냅샷 * 에 사용됨)이 인식되지 않으며 백업할 수 있는 볼륨 목록에 DP 볼륨이 표시되지 않습니다.
** SVM-DR과 볼륨 백업 및 복구는 소스 또는 대상에서 백업을 수행하는 경우 완전히 독립적으로 작동합니다. 유일한 제한은 SVM-DR이 SnapMirror 클라우드 관계를 복제하지 않는다는 것입니다. SVM이 2차 위치에서 온라인 상태가 될 때 DR 시나리오에서는 SnapMirror 클라우드 관계를 수동으로 업데이트해야 합니다.




* MetroCluster 지원:
+
** ONTAP 9.12.1 GA 이상을 사용하는 경우 기본 시스템에 연결되면 백업이 지원됩니다. 전체 백업 구성이 보조 시스템으로 전송되므로 전환 후 클라우드 백업이 자동으로 계속됩니다. 2차 시스템에 백업을 설정할 필요가 없습니다(사실상 백업 설정이 제한됨).
** ONTAP 9.12.0 이하 버전을 사용하는 경우 ONTAP 보조 시스템에서만 백업이 지원됩니다.
** 현재 FlexGroup 볼륨의 백업은 지원되지 않습니다.


* 데이터 보호 볼륨에서 * 지금 백업 * 버튼을 사용한 임시 볼륨 백업이 지원되지 않습니다.
* SM-BC 구성은 지원되지 않습니다.
* ONTAP는 단일 볼륨에서 여러 오브젝트 저장소로의 SnapMirror 관계 팬아웃을 지원하지 않습니다. 따라서 BlueXP 백업 및 복구에서는 이 구성을 지원하지 않습니다.
* 현재 오브젝트 저장소의 WORM/Compliance 모드는 Amazon S3, Azure 및 StorageGRID에서 지원됩니다. 이를 DataLock 기능이라고 하며 클라우드 공급자 인터페이스를 사용하지 않고 BlueXP 백업 및 복구 설정을 사용하여 관리해야 합니다.




=== 복구 제한 사항

특별히 호출되지 않는 한 검색 및 복원과 찾아보기 및 복원 방법 모두에 이러한 제한 사항이 적용됩니다.

* Browse & Restore는 한 번에 최대 100개의 개별 파일을 복원할 수 있습니다.
* Search & Restore는 한 번에 하나의 파일을 복원할 수 있습니다.
* ONTAP 9.13.0 이상을 사용하는 경우 찾아보기 및 복원, 검색 및 복원 기능을 사용하여 폴더 내의 모든 파일 및 하위 폴더와 함께 폴더를 복원할 수 있습니다.
+
9.11.1보다 크고 9.13.0 이전 버전의 ONTAP를 사용하는 경우, 복원 작업은 선택한 폴더와 하위 폴더 또는 하위 폴더의 파일이 아닌 해당 폴더의 파일만 복원할 수 있습니다.

+
9.11.1 이전의 ONTAP 버전을 사용하는 경우 폴더 복원이 지원되지 않습니다.

* 디렉토리/폴더 복구는 클러스터가 ONTAP 9.13.1 이상을 실행하는 경우에만 아카이브 스토리지에 상주하는 데이터에 지원됩니다.
* 디렉토리/폴더 복구는 클러스터가 ONTAP 9.13.1 이상을 실행하는 경우에만 DataLock을 사용하여 보호되는 데이터에 대해 지원됩니다.
* 디렉토리/폴더 복구는 현재 복제 및/또는 로컬 스냅샷에서 지원되지 않습니다.
* FlexGroup 볼륨에서 FlexVol 볼륨으로 또는 FlexVol 볼륨을 FlexGroup 볼륨으로 복원하는 것은 지원되지 않습니다.
* 복원 중인 파일은 대상 볼륨의 언어와 동일한 언어를 사용해야 합니다. 언어가 동일하지 않으면 오류 메시지가 나타납니다.
* Azure 아카이브 스토리지에서 StorageGRID 시스템으로 데이터를 복원할 때는 _High_restore 우선 순위가 지원되지 않습니다.
* DP 볼륨을 백업한 다음 이 볼륨에 대한 SnapMirror 관계를 해제하기로 결정한 경우, SnapMirror 관계를 삭제하거나 SnapMirror 방향을 반대로 바꾸지 않는 한 해당 볼륨에 파일을 복원할 수 없습니다.
* 빠른 복구 제한 사항:
+
** 대상 위치는 ONTAP 9.13.0 이상을 사용하는 Cloud Volumes ONTAP 시스템이어야 합니다.
** 아카이브 스토리지에 있는 백업에서는 지원되지 않습니다.
** FlexGroup 볼륨은 클라우드 백업이 생성된 소스 시스템에서 ONTAP 9.12.1 이상을 실행 중인 경우에만 지원됩니다.
** SnapLock 볼륨은 클라우드 백업을 생성한 소스 시스템에서 ONTAP 9.11.0 이상을 실행 중인 경우에만 지원됩니다.



