---
sidebar: sidebar 
permalink: reference-prereq-protect-cloud-native-app-data.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in, BlueXP 
summary: 백업을 생성하기 전에 사전 요구 사항을 완료합니다. 
---
= 필수 구성 요소
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에 액세스하고, BlueXP 계정을 만들고, 작업 환경과 커넥터를 만들고, Oracle용 SnapCenter 플러그인을 구축해야 합니다.



== BlueXP에 액세스합니다

당신은 해야 한다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["BlueXP에 로그인합니다"^]를 선택한 다음 를 설정합니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["NetApp 계정"^].



== ONTAP 작업 환경을 위한 FSx를 생성합니다

데이터베이스가 호스팅되는 ONTAP 작업 환경을 위한 Amazon FSx를 생성해야 합니다. 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["ONTAP용 Amazon FSx를 시작하십시오"] 및 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["ONTAP 작업 환경을 위한 Amazon FSx를 생성하고 관리합니다"].

BlueXP 또는 AWS를 사용하여 NetApp FSx를 생성할 수 있습니다. AWS를 사용하여 생성한 경우 BlueXP에서 ONTAP 시스템용 FSx를 검색해야 합니다.



== 커넥터를 작성합니다

계정 관리자는 AWS에 Connector를 구축하여 BlueXP가 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있도록 해야 합니다.

자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["BlueXP에서 AWS에 커넥터 생성"].

* FSx 작업 환경과 Oracle 데이터베이스를 모두 관리하려면 동일한 커넥터를 사용해야 합니다.
* FSx 작업 환경과 Oracle 데이터베이스가 동일한 VPC에 있는 경우 동일한 VPC에 커넥터를 배포할 수 있습니다.
* FSx 작업 환경과 Oracle 데이터베이스가 서로 다른 VPC에 있는 경우:
+
** FSx에 NAS(NFS) 워크로드가 구성되어 있는 경우 두 VPC 중 하나에 커넥터를 생성할 수 있습니다.
** SAN 워크로드만 구성되어 있고 NAS(NFS) 워크로드를 사용할 계획이 없는 경우 FSx 시스템이 생성되는 VPC에 커넥터를 생성해야 합니다.
+

NOTE: NAS(NFS) 워크로드를 사용하려면 Oracle 데이터베이스 VPC와 FSx VPC 간에 전송 게이트웨이가 있어야 합니다. 부동 IP 주소인 NFS IP 주소는 전송 게이트웨이를 통해서만 다른 VPC에서 액세스할 수 있습니다. VPC를 피해서 유동 IP 주소에 액세스할 수 없습니다.





커넥터를 만든 후 * Storage * > * Canvas * > * My Working Environments * > * Add Working Environment * 를 클릭하고 화면의 지시에 따라 작업 환경을 추가합니다. Oracle 데이터베이스 호스트 및 FSx 작업 환경에 대한 커넥터와 연결이 있는지 확인합니다. 커넥터는 FSx 작업 환경의 클러스터 관리 IP 주소에 연결할 수 있어야 합니다.


IMPORTANT: 커넥터를 작성한 후 * 커넥터 > 커넥터 관리 * 를 클릭하고 커넥터 이름을 선택한 다음 커넥터 ID를 복사합니다.



== Oracle용 SnapCenter 플러그인 구축

각 Oracle 데이터베이스 호스트에 Oracle용 SnapCenter 플러그인을 구축해야 합니다. Oracle 호스트에 SSH 키 기반 인증이 활성화되어 있는지 여부에 따라 플러그인 구축 방법 중 하나를 따를 수 있습니다.


NOTE: 각 Oracle 데이터베이스 호스트에 Java 8이 설치되어 있고 JAVA_HOME 변수가 적절하게 설정되어 있는지 확인합니다.



=== SSH 키 기반 인증을 사용한 플러그인 구축

Oracle 호스트에 SSH 키 기반 인증이 설정되어 있는 경우 다음 단계를 수행하여 플러그인을 구축할 수 있습니다. 단계를 수행하기 전에 커넥터에 대한 SSH 연결이 활성화되어 있는지 확인합니다.

. 커넥터 VM에 비 루트 사용자로 로그인합니다.
. 기본 마운트 경로를 가져옵니다. 'SUDO Docker 볼륨 ls | grep scs_cloud_volume | awk {'print$2'} | xargs sudo Docker 볼륨 검사 | grep mountpoint'
. 플러그인을 배포하십시오.
+
'sudo<base_mount_path>/scripts/oracle_plugin_copy_and_install.sh -- host <host_name>--sshkey <ssh_key_file>--username <user_name>--port <ssh_port>--pluginport <plugin_port>--installdir <install_dir>'입니다

+
** host_name 은 Oracle 호스트의 이름이며 필수 매개 변수입니다.
** SSH_KEY_FILE은 Oracle 호스트에 연결하는 데 사용되는 SSH 키이며 필수 매개 변수입니다.
** user_name: Oracle 호스트에 대한 SSH 권한이 있는 사용자로, 이 매개 변수는 선택 사항입니다. 기본값은 EC2-user입니다.
** SSH_PORT: Oracle 호스트의 SSH 포트이며 이는 선택적 매개 변수입니다. 기본값은 22입니다
** plugin_port: 플러그인에서 사용하는 포트로, 이 매개 변수는 선택 사항입니다. 기본값은 8145입니다
** install_dir: 플러그인이 배포될 디렉터리이며 선택적 매개 변수입니다. 기본값은 /opt입니다.




예: sudo/var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh -- host xxx.xx.x.x -- sshkey/netapp-ssh.ppk



=== 플러그인의 수동 배포

Oracle 호스트에서 SSH 키 기반 인증이 활성화되지 않은 경우 다음 수동 단계를 수행하여 플러그인을 구축해야 합니다.

. Connector VM에 로그인합니다.
. SnapCenter Linux 호스트 플러그인 바이너리를 다운로드합니다. S UDO Docker Exec - IT cloudmanager_scs_cloud curl-X get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. 기본 마운트 경로를 가져옵니다. 'SUDO Docker 볼륨 ls | grep scs_cloud_volume | awk {'print$2'} | xargs sudo Docker 볼륨 검사 | grep mountpoint'
. 다운로드한 플러그인의 바이너리 경로를 가져옵니다. sudo ls <base_mount_path>$(sudo docker PS | grep-Po "cloudmanager_scs_cloud:. *? "|SED-e's/ *$/'|cut-F2-d":")/SC-Linux-host-plugin/snapcenter_linux_host_plugin_scs.bin'
. SCP 또는 다른 대체 방법을 사용하여 각 Oracle 데이터베이스 호스트에 _snapcenter_linux_host_plugin_scs.bin_을 복사합니다.
. Oracle 데이터베이스 호스트에서 다음 명령을 실행하여 바이너리에 대한 실행 권한을 활성화합니다. 'chmod + x snapcenter_linux_host_plugin_scs.bin'
. Oracle 플러그인을 루트 사용자로 구축합니다. (./snapcenter_linux_host_plugin_scs.bin - 나는 침묵을 지켰다
. 플러그인 호스트의 커넥터 VM의 _/var/opt/snapcenter/spl/etc/_에서 _certificate.p12_from_<base_mount_path>/client/certificate/_path를 _ /var/opt/snapcenter/spl/etc/_로 복사합니다.
+
.. /var/opt/snapcenter/spl/etc_로 이동하고 keytool 명령을 실행하여 인증서를 가져옵니다. keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype jks -srcstorephass SnapCenter -deststorephass SnapCenter -srcalalas agentcert -alias destagentcert -not프롬프트
.. SPL을 다시 시작합니다:'stemctl restart SPL'



