---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: Azure NetApp Files 작업 환경과 커넥터를 작성합니다 
---
= Azure NetApp Files를 구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP를 사용하면 Azure NetApp Files 작업 환경을 만들어 볼륨 및 추가 데이터 서비스를 추가하고 관리해야 합니다. 또한 Azure에서 Connector를 만들어 BlueXP가 퍼블릭 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있도록 해야 합니다.



== Azure NetApp Files 작업 환경을 생성합니다

데이터베이스가 호스팅되는 Azure NetApp Files 작업 환경을 만들어야 합니다. 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Azure NetApp Files에 대해 자세히 알아보십시오"] 및 link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Azure NetApp Files 작업 환경을 만듭니다"].



== 커넥터를 작성합니다

BlueXP 계정 관리자는 Azure에 Connector를 배포하여 BlueXP가 공용 클라우드 환경 내의 리소스와 프로세스를 관리할 수 있도록 해야 합니다.

자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["BlueXP에서 Azure에 커넥터를 만듭니다"].

* 커넥터에서 데이터베이스 호스트로의 연결이 있는지 확인합니다.
* 동일한 VNet(가상 네트워크)에 Azure NetApp Files 작업 환경과 데이터베이스가 있는 경우 동일한 VNET에 커넥터를 배포할 수 있습니다.
* Azure NetApp Files 작업 환경과 데이터베이스가 서로 다른 VNets에 있고 Azure NetApp Files에 NAS(NFS) 워크로드가 구성되어 있는 경우 VNets 중 하나에 커넥터를 생성할 수 있습니다.


커넥터를 만든 후 * Storage * > * Canvas * > * My Working Environments * > * Add Working Environment * 를 클릭하여 작업 환경을 추가합니다.
