---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: 인터넷에 연결되지 않은 사이트에서 Cloud Backup을 사용하는 경우 BlueXP Connector 호스트 시스템에 문제가 있을 경우 중요한 Cloud Backup 파일을 정기적으로 백업해야 합니다. 그러면 새 Connector를 구축하고 중요한 Cloud Backup 데이터를 복원할 수 있습니다. 
---
= 어두운 사이트에서 Cloud Backup 데이터를 백업 및 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
인터넷에 연결되지 않은 사이트에서 Cloud Backup을 사용하는 경우 BlueXP Connector 호스트 시스템에 문제가 있을 경우 중요한 Cloud Backup 파일을 정기적으로 백업해야 합니다. 그러면 새 Connector를 구축하고 중요한 Cloud Backup 데이터를 복원할 수 있습니다.

BlueXP Connector가 클라우드 공급업체에 구축하거나 인터넷에 액세스할 수 있는 자체 호스트 시스템에 구축된 SaaS 환경에서 Cloud Backup을 사용하는 경우 중요한 Cloud Backup 구성 데이터가 모두 백업되고 클라우드에 저장됩니다. 인터넷에 액세스할 수 없는 사이트에서 Cloud Backup을 사용하는 경우, "다크 사이트"라고도 하는 이 Cloud Backup 정보는 로컬 Connector 시스템에만 저장됩니다.

이 항목에서는 중요한 클라우드 백업 데이터를 연결된 StorageGRID 시스템에 백업하는 방법에 대해 설명합니다. 또한 필요한 경우 새 커넥터에 데이터를 복원하는 방법에 대해서도 설명합니다.


NOTE: 항상 최신 데이터에 액세스할 수 있도록 이 Cloud Backup 데이터를 정기적으로 백업하도록 계획해야 합니다.



== 중요한 Cloud Backup 데이터를 백업합니다

백업해야 하는 데이터 유형은 두 가지입니다.

* Cloud Backup 데이터베이스
* 인덱싱된 카탈로그 파일(검색 및 복원 기능에 사용됨)


Cloud Backup 데이터베이스 또는 인덱싱된 카탈로그 파일에 볼륨 데이터가 포함되지 않은 경우



=== Cloud Backup 데이터베이스를 백업합니다

Cloud Backup 데이터베이스에는 모든 볼륨, 백업 파일, 백업 정책 및 구성 정보 목록이 포함되어 있습니다.

.단계
. 적절한 자격 증명을 사용하여 커넥터 호스트 시스템에 로그인합니다.
. 다음 명령을 입력하여 MySQL 컨테이너 셸을 입력합니다.
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. 컨테이너 셸에서 "env"를 배포합니다.
. MySQL DB 패스워드가 필요합니다. 따라서 "mysql_root_password" 키의 값을 복사합니다.
. 다음 명령을 입력하여 Cloud Backup MySQL DB를 백업합니다.
+
[source, cli]
----
mysqldump --user root --password -p cloud_backup --result-file=mysql.dump.cloud_backup.sql
----
. 다음 명령을 입력하여 MySQL Docker 컨테이너에서 MySQL DB 백업을 복사합니다.
+
[source, cli]
----
docker cp ds_mysql_1:/mysql.dump.cloud_backup.sql .
----
. 백업을 네트워크의 안전한 위치에 복사합니다. 해당 위치에 대한 ONTAP 볼륨 백업을 생성하는 경우 로컬 StorageGRID 시스템을 사용할 수 있습니다.




=== 인덱싱된 카탈로그 파일을 백업합니다

인덱싱된 카탈로그는 검색 및 복원 기능에 사용됩니다. 이 문서에는 모든 볼륨과 모든 백업 파일에 대한 정보가 포함되어 있어 볼륨 데이터를 복원할 때 매우 빠르고 효율적으로 검색할 수 있습니다.

. Connector 호스트 시스템에서 디렉토리를 "/tmp"로 변경합니다.
. Index Catalog 폴더를 찾습니다. 문자열 * catalog * 로 시작합니다.
. 다음 명령을 입력하여 "catalog<_xxxxxx_>" 폴더를 압축합니다.
+
[source, cli]
----
zip -r catalogxxxxxx.zip catalogxxxxxx
----
. 압축된 백업을 네트워크의 안전한 위치에 복사합니다.




== Cloud Backup 데이터를 새 Connector로 복원합니다

온프레미스 커넥터에 심각한 장애가 발생할 경우 새 커넥터를 설치한 다음 Cloud Backup 데이터를 새 커넥터로 복원해야 합니다.

Cloud Backup 시스템을 작업 상태로 되돌리려면 다음 4가지 작업을 수행해야 합니다.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["새로운 온프레미스 Linux 호스트에 새 커넥터를 설치합니다"^]
* Cloud Backup 데이터베이스를 복원합니다
* 인덱싱된 카탈로그 파일을 복원합니다
* 모든 온프레미스 ONTAP 시스템을 BlueXP UI로 재검색합니다


시스템이 정상적으로 작동하는지 확인한 후에는 새 백업 파일을 생성하는 것이 좋습니다.



=== Cloud Backup 데이터베이스를 복원합니다

. 새 커넥터를 설치한 후 적절한 자격 증명을 사용하여 커넥터 호스트 시스템에 로그인합니다.
. MySQL 백업을 보안 위치에서 새 커넥터 호스트로 복사합니다.
. 다음 명령을 사용하여 MySQL Docker 컨테이너에 백업을 복사합니다.
+
[source, cli]
----
docker cp mysql.dump.cloud_backup.sql ds_mysql_1:/.
----
. 다음 명령을 사용하여 MySQL 컨테이너 셸을 입력합니다.
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. 컨테이너 셸에서 "env"를 배포합니다.
. MySQL DB 패스워드가 필요합니다. 따라서 "mysql_root_password" 키의 값을 복사합니다.
. 다음 명령을 사용하여 Cloud Backup MySQL DB를 복구합니다.
+
[source, cli]
----
mysql -u root -p cloud_backup < mysql.dump.cloud_backup.sql
----
. 다음 SQL 명령을 사용하여 Cloud Backup MySQL DB가 올바르게 복구되었는지 확인합니다.
+
[source, cli]
----
# mysql -u root -p cloud_backup
----
+
암호를 입력합니다.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
표시된 볼륨이 원래 환경에 있던 볼륨과 동일한지 확인합니다.





=== 인덱싱된 카탈로그 파일을 복원합니다

. 보안 위치에서 "/tmp" 폴더의 새 Connector 호스트로 인덱스 카탈로그 백업 zip 파일을 복사합니다.
. 다음 명령을 사용하여 "catalogxxxxxx.zip" 파일의 압축을 풉니다.
+
[source, cli]
----
unzip catalogxxxxxx.zip
----
. ls * 명령을 실행하여 하위 폴더 "changes" 및 "snapshots" 아래에 "catalogxxxxxx" 폴더가 생성되었는지 확인하십시오.




=== 클러스터를 검색하고 클라우드 백업 설정을 확인합니다

. https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#discovering-clusters-from-the-canvas-page["온프레미스 ONTAP 작업 환경을 모두 살펴보십시오"^] 이전 환경에서 사용할 수 있었습니다.
. 필요한 경우 https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID 시스템에 대해 알아보십시오"^].
. 각 ONTAP 작업 환경을 선택하고 오른쪽 패널의 백업 및 복구 서비스 옆에 있는 * 백업 보기 * 를 클릭합니다.
+
볼륨에 대해 생성된 모든 백업을 볼 수 있어야 합니다.

. 복원 대시보드의 검색 및 복원 섹션에서 * 인덱싱 설정 * 을 클릭합니다.
+
이전에 인덱싱된 카탈로그 기능이 활성화된 작업 환경이 활성화된 상태로 유지되는지 확인합니다.

. Search & Restore 페이지에서 몇 가지 카탈로그 검색을 실행하여 인덱싱된 카탈로그 복원이 성공적으로 완료되었는지 확인합니다.

