---
sidebar: sidebar 
permalink: task-restore-cloud-native-sql-data.html 
keywords: restore, SQL database, BlueXP 
summary: 클라우드에서 동일한 호스트로 SQL 데이터베이스를 복원할 수 있습니다. 
---
= Microsoft SQL Server 데이터베이스를 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Microsoft SQL Server 데이터베이스를 동일한 호스트에 복구할 수 있습니다. 먼저 데이터베이스 목록을 가져온 다음 데이터베이스를 복원해야 합니다.



== 데이터베이스 목록을 봅니다

이 API를 실행하여 데이터베이스 목록을 볼 수 있습니다.

'snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases' 다운로드하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Databases/GetMSSQLDatabasesRequest[]



=== 응답

API가 정상적으로 실행되면 응답 코드 200이 출력된다.

예:

[listing]
----
{
    "num_records": 3,
    "total_records": 3,
    "records": [
        {
            "id": "348901e5-aeaa-419f-88b1-80240de3b1fe",
            "name": "DB4",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "c79d33ab-7322-4ed6-92f5-51ad7a6944e0",
            "name": "DB5",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "40d6f35a-f4fb-48bc-8e0a-0ac93ddf0888",
            "name": "model",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.015625,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "System",
            "recovery_mode": "Full"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== MSSQL 데이터베이스를 복원 및 복구합니다

이 API를 실행하여 MSSQL 데이터베이스를 복원할 수 있습니다.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases/{id}/restore' 를 참조하십시오

여기서, _id_는 View 데이터베이스 API를 실행하여 얻은 MSSQL 데이터베이스 ID입니다. 자세한 내용은 을 참조하십시오 <<데이터베이스 목록을 봅니다>>.

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Database%20Restore/RestoreMSSQLDatabaseRequest[]

이 API를 사용하면 BlueXP UI의 * Job Monitor * 탭에서 추적할 수 있는 작업이 생성됩니다.



=== 매개 변수

|===
| 이름 | 유형 | 필수 요소입니다 


 a| 
backup_id입니다
 a| 
문자열
 a| 
참



 a| 
Overwrite_database(데이터베이스 덮어쓰기
 a| 
불입니다
 a| 
참



 a| 
retain_replication_settings를 선택합니다
 a| 
불입니다
 a| 
거짓



 a| 
recovery_mode(복구 모드
 a| 
문자열

지원되는 3개의 문자열은 _Operational_, _Nonoperational_ 및 _ReadOnly_입니다.
 a| 
참



 a| 
실행 취소_파일_디렉토리
 a| 
문자열
 a| 
참



 a| 
restore_type 을 선택합니다
 a| 
문자열
 a| 
참

|===


=== 응답

API가 정상적으로 실행되면 응답 코드 202가 출력된다.

예:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----