---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: BlueXP에서 VMware vSphere 호스트용 SnapCenter 플러그인을 등록합니다. 
---
= VMware vSphere 호스트용 SnapCenter 플러그인을 등록합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
표시할 데이터 저장소 및 가상 시스템에 대해 BlueXP의 VMware vSphere 호스트용 SnapCenter 플러그인을 등록해야 합니다. 관리 액세스 권한이 있는 사용자만 VMware vSphere 호스트용 SnapCenter 플러그인을 등록할 수 있습니다.

.단계
. BlueXP UI에서 * 보호 * > * 백업 및 복구 * > * 가상 머신 * 을 클릭합니다.
. 설정 * 드롭다운에서 * SnapCenter Plug-in for VMware vSphere * 를 클릭합니다.
. VMware vSphere * 용 SnapCenter 플러그인 등록 을 클릭합니다.
. 다음 세부 정보를 지정합니다.
+
.. VMware vSphere용 SnapCenter 플러그인 필드에서 VMware vSphere 호스트용 SnapCenter 플러그인의 FQDN 또는 IP 주소를 지정합니다.
.. 포트 필드에서 VMware vSphere 호스트용 SnapCenter 플러그인이 실행되고 있는 포트 번호를 지정합니다.
+
기본 8144 포트에서 실행 중인 온프레미스 SnapCenter Plug-in for VMware vSphere 호스트와 클라우드 공급자(Amazon Web Services, Microsoft Azure, Google Cloud Platform) 또는 온프레미스에서 실행 가능한 BlueXP Connector 인스턴스 간에 통신이 열려 있는지 확인해야 합니다.

.. 사용자 이름 및 암호 필드에서 관리자 역할을 가진 vCenter 사용자의 자격 증명을 지정합니다.


. Register * 를 클릭합니다.


* 완료 후 *

VMware vSphere 호스트용 등록된 SnapCenter 플러그인을 사용하여 보호되는 모든 데이터 저장소와 가상 머신을 보려면 * 백업 및 복구 * > * 가상 머신 * 을 클릭합니다.
