---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: SQL Server 데이터베이스를 클라우드에서 사내 SnapCenter 서버로 복원할 수 있습니다. 
---
= BlueXP 백업 및 복구를 사용하여 SQL Server 데이터베이스 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 백업 및 복구를 사용하면 SQL Server 데이터베이스를 원래 위치나 대체 위치로 복원할 수 있습니다.


NOTE: SFR(Single File Restore), 로그 백업 복구 및 가용성 그룹의 재시드는 지원되지 않습니다.

.단계
. BlueXP UI에서 * 보호 * > * 백업 및 복구 * > * 응용 프로그램 * 을 클릭합니다.
. 필터 기준 * 필드에서 필터 * 유형 * 을 선택하고 드롭다운에서 * SQL * 을 선택합니다.
. 사용 가능한 모든 백업을 보려면 * 세부 정보 보기 * 를 클릭합니다.
. 백업을 선택하고 * 복원 * 을 클릭합니다.
. 복원 옵션 페이지에서 데이터베이스 파일을 복원할 위치를 지정합니다.
+
|===
| 만약... | 수행할 작업... 


 a| 
원래 위치로 복구하려는 경우
 a| 
.. 원래 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 다음 * 을 클릭합니다.




 a| 
일시적으로 다른 저장소로 복구한 다음 복원된 파일을 원래 위치로 복사하려는 경우
 a| 
.. 원래 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 저장 위치 변경 * 을 선택합니다.
+
저장 위치 변경 * 을 선택하면 대상 볼륨에 접미사를 추가할 수 있습니다. 확인란을 선택하지 않은 경우 기본적으로 *_restore * 가 대상 볼륨에 추가됩니다.

.. 다음 * 을 클릭합니다.
.. 스토리지 매핑 페이지에서 오브젝트 저장소에서 복원된 데이터가 일시적으로 저장되는 대체 스토리지 위치 세부 정보를 지정합니다.
.. 다음 * 을 클릭합니다.




 a| 
대체 위치로 복구하려는 경우
 a| 
.. 대체 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 다음 * 을 클릭합니다.
.. 대상 호스트 페이지에서 호스트 이름을 선택하고 데이터베이스 이름(선택 사항)을 제공하며 인스턴스를 선택하고 복구 경로를 지정합니다.
+

NOTE: 대체 경로에 제공된 파일 확장자는 원본 데이터베이스 파일의 파일 확장명과 동일해야 합니다.

.. 다음 * 을 클릭합니다.




 a| 
일시적으로 다른 저장소로 복구한 다음 복원된 파일을 대체 위치로 복사하려는 경우
 a| 
.. 대체 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 저장 위치 변경 * 을 선택합니다.
+
저장 위치 변경 * 을 선택하면 대상 볼륨에 접미사를 추가할 수 있습니다. 확인란을 선택하지 않은 경우 기본적으로 *_restore * 가 대상 볼륨에 추가됩니다.

.. 다음 * 을 클릭합니다.
.. 스토리지 매핑 페이지에서 오브젝트 저장소에서 복원된 데이터가 일시적으로 저장되는 대체 스토리지 위치 세부 정보를 지정합니다.
.. 다음 * 을 클릭합니다.
.. 대상 호스트 페이지에서 호스트 이름을 선택하고 데이터베이스 이름(선택 사항)을 제공하며 인스턴스를 선택하고 복구 경로를 지정합니다.
+

NOTE: 대체 경로에 제공된 파일 확장자는 원본 데이터베이스 파일의 파일 확장명과 동일해야 합니다.

.. 다음 * 을 클릭합니다.


|===
. Pre-operations * 에서 다음 옵션 중 하나를 선택합니다.
+
** 같은 이름으로 데이터베이스를 복원하려면 * 복원 중에 같은 이름으로 데이터베이스 덮어쓰기 * 를 선택합니다.
** 데이터베이스를 복원하고 기존 복제 설정을 유지하려면 * SQL 데이터베이스 복제 설정 유지 * 를 선택합니다.


. 사후 작업 * 섹션에서 추가 트랜잭션 로그를 복원하기 위한 데이터베이스 상태를 지정하려면 다음 옵션 중 하나를 선택합니다.
+
** 지금 필요한 모든 백업을 복원하는 경우 * 작동 가능하나 * 를 선택합니다.
+
이는 기본 동작으로, 커밋되지 않은 트랜잭션을 롤백하여 데이터베이스를 사용할 수 있도록 합니다. 백업을 생성할 때까지 추가 트랜잭션 로그를 복원할 수 없습니다.

** 커밋되지 않은 트랜잭션을 롤백하지 않고 데이터베이스를 비작동 상태로 두려면 * 비작동, 사용 가능 * 을 선택합니다.
+
추가 트랜잭션 로그를 복원할 수 있습니다. 데이터베이스가 복구될 때까지 데이터베이스를 사용할 수 없습니다.

** 데이터베이스를 읽기 전용 모드로 전환하려면 * 읽기 전용 모드 및 사용 가능 * 을 선택합니다.
+
이 옵션은 커밋되지 않은 트랜잭션을 수행하지 않지만 복구 효과를 되돌릴 수 있도록 실행 취소된 작업을 대기 파일에 저장합니다.

+
Undo directory(디렉터리 실행 취소) 옵션이 활성화된 경우 더 많은 트랜잭션 로그가 복원됩니다. 트랜잭션 로그의 복원 작업이 실패한 경우 변경 내용을 롤백할 수 있습니다. 자세한 내용은 SQL Server 설명서를 참조하십시오.



. 다음 * 을 클릭합니다.
. 세부 정보를 검토하고 * Restore * 를 클릭합니다.



NOTE: 복원 작업이 완료되지 않으면 작업 모니터에 복구 작업이 실패했음을 표시할 때까지 복원 프로세스를 다시 시도하지 마십시오. 작업 모니터에 복구 작업이 실패했다고 표시되기 전에 복구 프로세스를 다시 시도하면 복구 작업이 다시 실패합니다. 작업 모니터 상태가 "실패"로 표시되면 복원 프로세스를 다시 시도할 수 있습니다.
