---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: 클라우드에서 사내 SnapCenter 서버로 Oracle 데이터베이스를 복원할 수 있습니다. 
---
= BlueXP 백업 및 복구를 사용하여 Oracle 데이터베이스 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 백업 및 복구를 사용하면 Oracle 데이터베이스를 원래 위치나 대체 위치로 복원할 수 있습니다. RAC 데이터베이스의 경우 데이터가 백업을 생성한 사내 노드로 복구됩니다.

제어 파일 복원이 있는 전체 데이터베이스만 지원됩니다. 아카이브 로그가 AFS에 없는 경우 복구에 필요한 아카이브 로그가 포함된 위치를 지정해야 합니다.


IMPORTANT: SFR(단일 파일 복원)은 지원되지 않습니다.

* 단계 *

. BlueXP UI에서 * 보호 * > * 백업 및 복구 * > * 응용 프로그램 * 을 클릭합니다.
. 필터 기준 * 필드에서 필터 * 유형 * 을 선택하고 드롭다운에서 * Oracle * 을 선택합니다.
. 복원하려는 데이터베이스에 해당하는 * View Details * 를 클릭하고 * Restore * 를 클릭합니다.
. 복원 옵션 페이지에서 데이터베이스 파일을 복원할 위치를 지정합니다.
+
|===
| 만약... | 수행할 작업... 


 a| 
원래 위치로 복구하려는 경우
 a| 
.. 원래 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 다음 * 을 클릭합니다.
.. 복구 및 복구 작업을 수행하는 데 필요한 상태로 데이터베이스의 상태를 변경하려면 * 데이터베이스 상태 * 를 선택합니다.
+
상위 데이터베이스에서 하위 데이터베이스까지의 다양한 상태는 열기, 마운트, 시작 및 종료입니다.

+
*** 데이터베이스가 더 높은 상태이지만 복원 작업을 수행하려면 상태를 더 낮은 상태로 변경해야 하는 경우 이 확인란을 선택해야 합니다.
*** 데이터베이스가 더 낮은 상태에 있지만 복원 작업을 수행하려면 상태를 더 높은 상태로 변경해야 하는 경우 확인란을 선택하지 않아도 데이터베이스 상태가 자동으로 변경됩니다.
*** 데이터베이스가 열려 있는 상태이고 복구를 위해 데이터베이스가 마운트된 상태여야 하는 경우 이 확인란을 선택한 경우에만 데이터베이스 상태가 변경됩니다.


.. 복구 범위를 지정합니다.
+
*** 마지막 트랜잭션으로 복구하려면 * All Logs * 를 선택합니다.
*** 특정 SCN으로 복구하려면 SCN(시스템 변경 번호) * 까지 * 를 선택합니다.
*** 특정 데이터와 시간으로 복구하려면 * 날짜 및 시간 * 을 선택합니다.
+
데이터베이스 호스트의 표준 시간대의 날짜 및 시간을 지정해야 합니다.

*** 복구하지 않으려면 * 복구 없음 * 을 선택합니다.


.. 아카이브 로그가 액티브 파일 시스템에 없는 경우 복구에 필요한 아카이브 로그를 포함하는 위치를 지정해야 합니다.
.. 복구 후 데이터베이스를 열려면 이 확인란을 선택합니다.
+
RAC 설정에서는 복구에 사용되는 RAC 인스턴스만 복구 후 열립니다.





 a| 
일시적으로 다른 저장소로 복구한 다음 복원된 파일을 원래 위치로 복사하려는 경우
 a| 
.. 원래 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 저장 위치 변경 * 을 선택합니다.
+
저장 위치 변경 * 을 선택하면 대상 볼륨에 접미사를 추가할 수 있습니다. 확인란을 선택하지 않은 경우 기본적으로 *_restore * 가 대상 볼륨에 추가됩니다.

.. 다음 * 을 클릭합니다.
.. 스토리지 매핑 페이지에서 오브젝트 저장소에서 복원된 데이터가 일시적으로 저장되는 대체 스토리지 위치 세부 정보를 지정합니다.
+
사내 ONTAP 시스템을 선택하고 오브젝트 스토리지에 대한 클러스터 연결을 구성하지 않은 경우 오브젝트 저장소에 대한 추가 정보를 묻는 메시지가 표시됩니다.

.. 다음 * 을 클릭합니다.
.. 복구 및 복구 작업을 수행하는 데 필요한 상태로 데이터베이스의 상태를 변경하려면 * 데이터베이스 상태 * 를 선택합니다.
+
상위 데이터베이스에서 하위 데이터베이스까지의 다양한 상태는 열기, 마운트, 시작 및 종료입니다.

+
*** 데이터베이스가 더 높은 상태이지만 복원 작업을 수행하려면 상태를 더 낮은 상태로 변경해야 하는 경우 이 확인란을 선택해야 합니다.
*** 데이터베이스가 더 낮은 상태에 있지만 복원 작업을 수행하려면 상태를 더 높은 상태로 변경해야 하는 경우 확인란을 선택하지 않아도 데이터베이스 상태가 자동으로 변경됩니다.
*** 데이터베이스가 열려 있는 상태이고 복구를 위해 데이터베이스가 마운트된 상태여야 하는 경우 이 확인란을 선택한 경우에만 데이터베이스 상태가 변경됩니다.


.. 복구 범위를 지정합니다.
+
*** 마지막 트랜잭션으로 복구하려면 * All Logs * 를 선택합니다.
*** 특정 SCN으로 복구하려면 SCN(시스템 변경 번호) * 까지 * 를 선택합니다.
*** 특정 데이터와 시간으로 복구하려면 * 날짜 및 시간 * 을 선택합니다.
+
데이터베이스 호스트의 표준 시간대의 날짜 및 시간을 지정해야 합니다.

*** 복구하지 않으려면 * 복구 없음 * 을 선택합니다.


.. 아카이브 로그가 액티브 파일 시스템에 없는 경우 복구에 필요한 아카이브 로그를 포함하는 위치를 지정해야 합니다.
.. 복구 후 데이터베이스를 열려면 이 확인란을 선택합니다.
+
RAC 설정에서는 복구에 사용되는 RAC 인스턴스만 복구 후 열립니다.





 a| 
대체 위치로 복구하려는 경우
 a| 
.. 대체 위치로 복원 * 을 선택합니다.
.. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
.. 대체 스토리지로 복구하려면 다음을 수행하십시오.
+
... 저장 위치 변경 * 을 선택합니다.
+
저장 위치 변경 * 을 선택하면 대상 볼륨에 접미사를 추가할 수 있습니다. 확인란을 선택하지 않은 경우 기본적으로 *_restore * 가 대상 볼륨에 추가됩니다.

... 다음 * 을 클릭합니다.
... 스토리지 매핑 페이지에서 오브젝트 저장소의 데이터를 복원해야 하는 대체 스토리지 위치 세부 정보를 지정합니다.


.. 다음 * 을 클릭합니다.
.. 대상 호스트 페이지에서 데이터베이스를 마운트할 호스트를 선택합니다.
+
... (선택 사항) NAS 환경의 경우 객체 저장소에서 복구된 볼륨을 내보낼 호스트의 FQDN 또는 IP 주소를 지정합니다.
... (선택 사항) SAN 환경의 경우 오브젝트 저장소에서 복원된 볼륨의 LUN을 매핑할 호스트의 이니시에이터를 지정합니다.


.. 다음 * 을 클릭합니다.


|===
. 세부 정보를 검토하고 * Restore * 를 클릭합니다.


.결과
Restore to alternate location * 옵션은 선택한 백업을 지정된 호스트에 마운트합니다. 데이터베이스를 수동으로 불러와야 합니다.

백업을 마운트한 후에는 마운트 해제될 때까지 다시 마운트할 수 없습니다. UI에서 * Unmount * 옵션을 사용하여 백업을 마운트 해제할 수 있습니다.

Oracle 데이터베이스를 가져오는 방법에 대한 자세한 내용은 을 참조하십시오. https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_bring_up_Oracle_Database_in_another_NFS_host_after_mounting_storage_from_backup_in_Cloud_Backup_for_Applications["기술 자료 문서"].


NOTE: 복원 작업이 완료되지 않으면 작업 모니터에 복구 작업이 실패했음을 표시할 때까지 복원 프로세스를 다시 시도하지 마십시오. 작업 모니터에 복구 작업이 실패했다고 표시되기 전에 복구 프로세스를 다시 시도하면 복구 작업이 다시 실패합니다. 작업 모니터 상태가 "실패"로 표시되면 복원 프로세스를 다시 시도할 수 있습니다.
