---
sidebar: sidebar 
permalink: task-discover-applications.html 
keywords: discover, admin role, service account, pre-canned policies 
summary: 정책을 할당하고 백업을 생성할 애플리케이션을 검색합니다. 
---
= 응용 프로그램을 검색합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
호스트에서 데이터베이스를 검색하여 정책을 할당하고 백업을 생성해야 합니다.

* 필요한 것 *

* ONTAP 작업 환경 및 커넥터용 FSx를 만들어야 합니다.
* 커넥터가 ONTAP 작업 환경 및 Oracle 데이터베이스 호스트용 FSx에 연결되어 있는지 확인합니다.
* Cloud Manager 사용자에게 "계정 관리자" 역할이 있는지 확인합니다.
* Oracle용 SnapCenter 플러그인을 구축해야 합니다. link:reference-prereq-protect-cloud-native-app-data.html#deploy-snapcenter-plug-in-for-oracle["자세한 정보"].


* 단계 *

. Cloud Manager UI에서 * 백업 및 복원 * > * 응용 프로그램 * 을 클릭합니다.
. 응용 프로그램 검색을 클릭합니다.
. Cloud Native * 를 선택하고 * Next * 를 클릭합니다.
+
이 계정의 모든 사용자에 대해 예약된 데이터 보호 작업을 수행하기 위해 _SnapCenter 시스템_역할이 있는 서비스 계정이 생성됩니다.

+
** 서비스 계정을 보려면 * 계정 * > * 계정 관리 * > * 회원 * 을 클릭합니다.
+

NOTE: 서비스 계정(_SnapCenter-account-<AccountID>_)은 예약된 백업 작업을 실행하는 데 사용됩니다. 서비스 계정을 삭제해서는 안 됩니다.



. 호스트 세부 정보 지정 페이지에서 Oracle 데이터베이스 호스트의 세부 정보를 입력하고 확인란을 선택하여 호스트에 플러그인이 설치되어 있는지 확인한 다음 * 검색 * 을 클릭합니다.
+
** 호스트의 모든 데이터베이스를 표시합니다. 데이터베이스에 대한 OS 인증이 비활성화된 경우 * 구성 * 을 클릭하여 데이터베이스 인증을 구성해야 합니다. 자세한 내용은 을 참조하십시오 <<Configure Oracle database credentials>>.
** 애플리케이션 관리 * 를 클릭하고 * 추가 * 를 선택하여 새 호스트를 추가하고 * 새로 고침 * 을 선택하여 새 데이터베이스를 검색하고 * 제거 * 를 선택하여 데이터베이스 호스트를 제거합니다.
** 설정 * 을 클릭하고 * 정책 * 을 선택하여 미리 구성된 정책을 봅니다. 사전 구성된 정책을 검토하여 요구 사항에 맞게 정책을 편집하거나 새 정책을 생성할 수 있습니다.






== Oracle 데이터베이스 자격 증명을 구성합니다

Oracle 데이터베이스에서 데이터 보호 작업을 수행하는 데 사용되는 자격 증명을 구성해야 합니다.

* 단계 *

. 데이터베이스에 대한 OS 인증이 비활성화된 경우 * 구성 * 을 클릭하여 데이터베이스 인증을 구성해야 합니다.
. 데이터베이스 설정 또는 ASM 설정 섹션에서 사용자 이름, 암호 및 포트 세부 정보를 지정합니다.
+
Oracle 사용자는 sysdba 권한을 가지고 ASM 사용자는 sysasm 권한을 가지고 있어야 합니다.

. 구성 * 을 클릭합니다.




== 정책을 생성합니다

사전 구성된 정책을 편집하지 않으려는 경우 정책을 생성할 수 있습니다.

* 단계 *

. 응용 프로그램 페이지의 설정 드롭다운 목록에서 * 정책 * 을 선택합니다.
. Create policy * 를 클릭합니다.
. 정책 이름을 지정합니다.
. (선택 사항) 백업 이름의 형식을 편집합니다.
. 스케줄 및 보존 세부 정보를 지정합니다.
. Create * 를 클릭합니다.

