---
sidebar: sidebar 
permalink: task-add-sqlhost-install-plugin-sql.html 
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for SQL, SQL, database, host, install, add host, discover 
summary: 각 SQL 데이터베이스 호스트에 SnapCenter Plug-in for SQL을 설치합니다. 
---
= SQL Server용 SnapCenter 플러그인 설치 및 데이터베이스 호스트 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
각 SQL 데이터베이스 호스트에 SnapCenter Plug-in for SQL Server를 설치하고, 데이터베이스 호스트를 추가하고, 데이터베이스 인스턴스를 검색하고, 데이터베이스 인스턴스에 대한 자격 증명을 구성해야 합니다.



== SQL Server용 SnapCenter 플러그인을 설치합니다

플러그인 * snapcenter_service_windows_host_plugin.exe * 를 다운로드한 다음 자동 설치 프로그램 명령을 실행하여 데이터베이스 호스트에 플러그인을 설치해야 합니다.

.시작하기 전에
* 다음 필수 구성 요소가 충족되는지 확인해야 합니다.
+
** Net 4.7.2가 설치되어 있습니다
** PowerShell 4.0이 설치되어 있습니다
** 최소 5GB의 디스크 공간을 사용할 수 있습니다
** 최소 RAM 크기 4GB 사용 가능


* API를 실행하여 고객 온보딩을 완료해야 합니다. 자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Tenant%20Registration/createTenant[]


.단계
. Connector 호스트에서 API를 실행하여 플러그인을 다운로드합니다.
`docker exec -it cloudmanager_scs_cloud curl 'http://127.0.0.1/api/v2/pluginpackage/windows'`
+
파일 위치는 _/var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/<agent_version>/sc-windows-host-plugin/snapcenter_service_windows_host_plugin.exe_입니다.

. SCP 또는 다른 방법을 사용하여 커넥터에서 각 MSSQL 서버 데이터베이스 호스트로 _snapcenter_service_windows_host_plugin.exe_를 복사합니다.
. 플러그인을 설치합니다.
'"C://<install_folder>/snapcenter_service_windows_host_plugin.exe" /silent/debuglog "C://<install_folder>/HA_Suite_Silent_Install_scsql_fresh.log" /log "C://install_folder/"BI_SNAPCENTENTENTPORT=8145 ISER 설치 = SCSQL'
. 자체 서명된 인증서를 _/var/lib/docker/volumes/service-manager-2_cloudmanager_SCS_cloud_volume/_data/client/certificate/certificate.pem_에서 MSSQL 서버 데이터베이스 호스트로 복사합니다.
+
기본 인증서를 사용하지 않는 경우 자체 서명된 인증서 또는 CA 서명된 인증서를 생성할 수도 있습니다.

. 커넥터 호스트에서 인증서를 .pem에서 .crt 형식으로 변환합니다.
'openssl x509-outform der-in certificate.pem-out certificate.crt'
. 인증서를 두 번 클릭하여 * 개인 * 및 * 신뢰할 수 있는 루트 인증 기관 * 저장소에 추가합니다.




== SQL Server 데이터베이스 호스트를 추가합니다

호스트 FQDN을 사용하여 MSSQL 데이터베이스 호스트를 추가해야 합니다.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts' 를 참조하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/AddHosts[]

이 API를 사용하면 BlueXP UI의 * Job Monitor * 탭에서 추적할 수 있는 작업이 생성됩니다.



=== 매개 변수

|===
| 이름 | 유형 | 필수 요소입니다 


 a| 
주소
 a| 
문자열
 a| 
참



 a| 
커넥터_ID
 a| 
문자열
 a| 
참



 a| 
플러그인_유형
 a| 
문자열
 a| 
참



 a| 
설치 방법
 a| 
문자열
 a| 
참



 a| 
plugin_port 를 선택합니다
 a| 
번호
 a| 
참



 a| 
사용자 이름
 a| 
문자열
 a| 
참

|===


=== 응답

API가 정상적으로 실행되면 응답 코드 202가 출력된다.

예:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 추가된 SQL Server 데이터베이스 호스트를 봅니다

이 API를 실행하여 추가된 모든 SQL Server 데이터베이스 호스트를 볼 수 있습니다.

'snapcenter.cloudmanager.cloud.netapp.com/api/v1/hosts' 다운로드하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/Host%20Management/GetHosts[]



=== 응답

API가 정상적으로 실행되면 응답 코드 200이 출력된다.

예:

[listing]
----
{
  "num_records": 1,
    "total_records": 1,
    "records": [
        {
            "id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "addr": "scspa2722211001.rtp.openenglab.netapp.com",
            "status": "Running",
            "connector_id": "fBf8Iwbp4BscBfD02qBwWm6I03gGAesRclients",
            "plugin_port": 8145,
            "plugins": [
                {
                    "type": "mssql"
                }
            ],
            "os_type": "windows",
            "platform": "onprem",
            "username": "administrator",
            "operating_mode": "production"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== 데이터베이스 인스턴스를 검색합니다

이 API를 실행하고 호스트 ID를 입력하여 모든 MSSQL 인스턴스를 검색할 수 있습니다.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/discovery' 를 참조하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/MSSQLInstancesDiscoveryRequest[]

이 API를 사용하면 BlueXP UI의 * Job Monitor * 탭에서 추적할 수 있는 작업이 생성됩니다.



=== 매개 변수

|===
| 이름 | 유형 | 필수 요소입니다 


 a| 
host_id입니다
 a| 
문자열
 a| 
참

|===


=== 응답

API가 정상적으로 실행되면 응답 코드 202가 출력된다.

예:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== 검색된 데이터베이스 인스턴스를 봅니다

이 API를 실행하여 검색된 모든 데이터베이스 인스턴스를 볼 수 있습니다.

'snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances' 다운로드하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/GetMSSQLInstancesRequest[]



=== 응답

API가 정상적으로 실행되면 응답 코드 200이 출력된다.

예:

[listing]
----
{
    "num_records": 2,
    "total_records": 2,
    "records": [
        {
            "id": "953e66de-10d9-4fd9-bdf2-bf4b0eaabfd7",
            "name": "scspa2722211001\\NAMEDINSTANCE1",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Running",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        },
        {
            "id": "18e1b586-4c89-45bd-99c8-26268def787c",
            "name": "scspa2722211001",
            "host_id": "85bd4603-08f7-45f4-ba8e-a0b1e2a0f4d0",
            "status": "Stopped",
            "auth_mode": 0,
            "version": "",
            "is_clustered": false,
            "is_credentials_configured": false,
            "protection_mode": ""
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== 데이터베이스 인스턴스 자격 증명을 구성합니다

이 API를 실행하여 데이터베이스 인스턴스의 자격 증명을 확인하고 설정할 수 있습니다.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql//api/mssql/credentials-configuration' 를 참조하십시오

자세한 내용은 다음을 참조하십시오. https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Instances/ConfigureCredentialRequest[]

이 API를 사용하면 BlueXP UI의 * Job Monitor * 탭에서 추적할 수 있는 작업이 생성됩니다.



=== 매개 변수

|===
| 이름 | 유형 | 필수 요소입니다 


 a| 
host_id입니다
 a| 
문자열
 a| 
참



 a| 
인스턴스_ID
 a| 
문자열
 a| 
참



 a| 
사용자 이름
 a| 
문자열
 a| 
참



 a| 
암호
 a| 
문자열
 a| 
참



 a| 
auth_mode(인증 모드
 a| 
문자열
 a| 
참

|===


=== 응답

API가 정상적으로 실행되면 응답 코드 202가 출력된다.

예:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----