---
sidebar: sidebar 
permalink: task-restore-hana-backup.html 
keywords: restore, mount application backups, SAP HANA database 
summary: SAP HANA 데이터베이스를 클라우드에서 사내 SnapCenter 서버로 복원할 수 있습니다. 
---
= SAP HANA 데이터베이스 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SAP HANA 데이터베이스를 동일한 호스트로 복원할 수 있습니다.

* 단계 *

. BlueXP UI에서 * 보호 * > * 백업 및 복구 * > * 응용 프로그램 * 을 클릭합니다.
. 필터 기준 * 필드에서 필터 * 유형 * 을 선택하고 드롭다운에서 * HANA * 를 선택합니다.
. 복원하려는 데이터베이스에 해당하는 * View Details * 를 클릭하고 * Restore * 를 클릭합니다.
. 복원 옵션 페이지에서 다음 중 하나를 지정합니다.
+
.. NAS 환경의 경우 객체 저장소에서 복구된 볼륨을 내보낼 호스트의 FQDN 또는 IP 주소를 지정합니다.
.. SAN 환경의 경우 오브젝트 저장소에서 복원된 볼륨의 LUN이 매핑될 호스트의 이니시에이터를 지정합니다.


. 스냅샷이 아카이브 스토리지에 있는 경우 아카이브 스토리지에서 데이터를 복원하는 우선 순위를 선택합니다.
+

NOTE: Amazon Web Services 또는 Microsoft Azure를 클라우드 공급자로 사용하는 경우에만 우선순위를 지정해야 합니다.

. 소스 스토리지에 공간이 충분하지 않거나 소스 스토리지가 다운된 경우 * 스토리지 위치 변경 * 을 선택합니다.
. 다음 * 을 클릭합니다.
. 스토리지 매핑 페이지에서 오브젝트 저장소에서 복원된 데이터가 저장될 대체 스토리지 위치 세부 정보를 지정합니다.
. 다음 * 을 클릭합니다.
. 세부 정보를 검토하고 * Restore * 를 클릭합니다.


이 작업은 지정된 호스트에서 선택한 백업의 스토리지 내보내기만 수행합니다. 파일 시스템을 수동으로 마운트하고 데이터베이스를 불러와야 합니다. 볼륨을 사용한 후에는 스토리지 관리자가 ONTAP 클러스터에서 볼륨을 삭제할 수 있습니다.

SAP HANA 데이터베이스를 가져오는 방법에 대한 자세한 내용은 다음을 참조하십시오. https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-overview-of-sap-system-copy-workflow-with-snapcenter.html["TR-4667: SnapCenter를 사용한 SAP 시스템 복사 워크플로우 개요"^] 및 https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-overview-of-sap-system-clone-workflow-with-snapcenter.html["TR-4667: SnapCenter를 사용한 SAP 시스템 클론 워크플로우 개요"^].
