---
sidebar: sidebar 
permalink: task-preview-enable.html 
keywords: cloud backup, bluexp backup and recovery, backup, restore, preview, enable, object storage, third-party, MinIO, S3-compatible 
summary: 사용자가 시작했거나 스케줄이 지정된 객체 스토리지 작업에 대한 로컬 스냅샷, 복제 및 백업의 상태를 모니터링하고 시작 또는 예약한 작업을 복구할 수 있습니다. 완료, 진행 중 또는 실패한 작업을 확인하여 문제를 진단하고 해결할 수 있습니다. BlueXP 알림 센터를 사용하면 전자 메일로 알림을 보내도록 설정할 수 있으므로 시스템에 로그인하지 않은 경우에도 중요한 시스템 작업을 알 수 있습니다. BlueXP 타임라인을 사용하면 UI 또는 API를 통해 시작된 모든 작업의 세부 정보를 볼 수 있습니다. 
---
= BlueXP  백업 및 복구의 미리 보기 기능을 활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  백업 및 복구 기능은 새로운 기능이 완전히 출시되기 전에 이를 테스트할 수 있는 사전 공개 기능을 제공합니다. 이러한 기능은 백업 및 복구 환경을 개선하도록 설계되었지만 완벽하게 지원되거나 안정적이지 않을 수 있습니다.


IMPORTANT: 이러한 기능은 미리 보기 모드이므로 프로덕션 환경에서 사용해서는 안 됩니다. 테스트 및 피드백 목적으로만 제공됩니다.



== 미리보기 기능 사용

BlueXP  백업 및 복구의 미리 보기 기능을 사용하려면 BlueXP  커넥터에 플래그를 설정해야 합니다. 이 플래그를 사용하면 서비스에서 사용할 수 있는 미리 보기 기능에 액세스하고 테스트할 수 있습니다.

.단계
. BlueXP  커넥터에 로그인합니다.
. 슈퍼유저로 전환합니다. 다음 명령을 실행합니다.
+
`sudo su`

. Docker 볼륨을 나열하고 CBS 볼륨을 식별합니다. 다음 명령을 실행합니다.
+
[listing]
----
podman volume ls | grep cbs
----
+
예상 출력:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. 볼륨을 검사하여 마운트 지점을 가져옵니다. 다음 명령을 실행합니다.
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
. 다음 명령을 실행합니다.
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
예상 출력:

+
[listing]
----
Mountpoint:
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Docker Volumes 디렉토리로 이동합니다. 이전 단계에서 얻은 마운트 지점으로 디렉토리를 변경합니다.
+
[listing]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config

----
. 파일을 찾아 `production-customer.json` 편집합니다.
. 올바른 디렉토리에 있고 파일이 있는지 `production-customer.json` 확인합니다.
.  `production-customer.json`기본 텍스트 편집기에서 파일을 열고 다음 JSON 스니펫을 추가하여 JSON 구조가 올바르게 유지되도록 합니다.
+
[listing]
----
{
   "feature-flags":
    {
        "volumes-dashboard-v2": true
     }
}
----
. 변경 내용을 파일에 저장합니다.
. BlueXP  백업 및 복구 Cloud Manager CBS 서비스를 다시 시작합니다. 다음 명령을 실행합니다.
+
[listing]
----
podman restart cloudmanager_cbs
----

