---
sidebar: sidebar 
permalink: task-licensing-cloud-backup.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: 'BlueXP 백업 및 복구는 클라우드 공급자로부터 용량제로(pay-as-you-go) 또는 연간 시장 가입 서비스를 구입하거나 NetApp에서 구입한 자체 라이센스를 구입하여 라이센스를 구입할 수 있습니다. 작업 환경에서 BlueXP 백업 및 복구를 활성화하고, 프로덕션 데이터의 백업을 만들고, 백업 데이터를 프로덕션 시스템으로 복원하려면 유효한 라이센스가 필요합니다.' 
---
= BlueXP 백업 및 복구에 대한 라이센스를 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클라우드 공급자로부터 * NetApp 지능형 서비스 * 에 대한 PAYGO(용량제) 또는 연간 마켓플레이스 구독 요금을 구매하거나 NetApp에서 BYOL(Bring Your Own License) 방식을 구입하여 BlueXP  백업 및 복구에 대한 라이센스를 획득할 수 있습니다. 작업 환경에서 BlueXP 백업 및 복구를 활성화하고, 프로덕션 데이터의 백업을 만들고, 백업 데이터를 프로덕션 시스템으로 복원하려면 유효한 라이센스가 필요합니다.

추가 내용을 읽기 전에 몇 가지 참고 사항을 확인하십시오.

* 클라우드 공급자의 Cloud Volumes ONTAP 시스템 마켓플레이스에서 PAYGO(Pay-as-you-Go) 구독을 이미 구독한 경우 BlueXP 백업 및 복구도 자동으로 구독됩니다. 다시 가입하지 않아도 됩니다.
* BlueXP  백업 및 복구 BYOL(Bring-Your-Own-License)은 BlueXP  조직 또는 계정과 연결된 모든 시스템에서 사용할 수 있는 부동 라이센스입니다. 따라서 기존 BYOL 라이센스에서 충분한 백업 용량을 제공하는 경우 다른 BYOL 라이센스를 구입할 필요가 없습니다.
* BYOL 라이센스를 사용하는 경우 PAYGO 구독을 등록하는 것이 좋습니다. BYOL 라이센스에서 허용하는 것보다 더 많은 데이터를 백업하거나 라이센스 기간이 만료되면 용량제 가입형 모델을 통해 백업이 계속 진행되므로 서비스가 중단되지 않습니다.
* 온프레미스 ONTAP 데이터를 StorageGRID에 백업할 경우 BYOL 라이센스가 필요하지만 클라우드 공급자의 스토리지 공간에는 비용이 들지 않습니다.


link:concept-ontap-backup-to-cloud.html#cost["BlueXP 백업 및 복구 사용과 관련된 비용에 대해 자세히 알아보십시오."]



== 30일 무료 평가판

BlueXP  백업 및 복구 30일 무료 평가판은 클라우드 공급자의 마켓플레이스에서 * NetApp 지능형 서비스 * 에 대한 선불 종량제 구독에 가입한 경우에 사용할 수 있습니다. 무료 평가판은 마켓플레이스 목록에 등록할 때 시작됩니다. Cloud Volumes ONTAP 시스템 구축 시 마켓플레이스 가입에 대한 요금을 지불하고 10일 후에 BlueXP 백업 및 복구 무료 평가판을 시작하면 20일 남짓으로 무료 평가판을 사용할 수 있습니다.

무료 평가판이 종료되면 중단 없이 자동으로 PAYGO 구독으로 전환됩니다. BlueXP 백업 및 복구를 계속 사용하지 않기로 결정한 경우에만 가능합니다 link:task-manage-backups-ontap.html#unregister-bluexp-backup-and-recovery-for-a-working-environment["작동 환경에서 BlueXP 백업 및 복구 등록을 취소합니다"] 평가판 사용 기간이 끝나기 전에는 요금이 부과되지 않습니다.



== BlueXP 백업 및 복구 PAYGO 구독을 사용합니다

사용한 만큼만 지불하는 용량제 방식을 사용하면 클라우드 공급업체에 오브젝트 스토리지 비용을 지불하고, NetApp 백업 라이센스 비용을 단일 정액제로 지불할 수 있습니다. 무료 평가판이 있거나 BYOL(Bring Your Own License)을 사용하는 경우에도 마켓플레이스에서 * NetApp Intelligent Services * 를 구독해야 합니다.

* 구독하면 무료 평가판이 종료된 후에도 서비스가 중단되지 않습니다. 평가판이 종료되면 백업하는 데이터의 양에 따라 매시간 요금이 부과됩니다.
* BYOL 라이센스에서 허용하는 것보다 많은 데이터를 백업하는 경우 용량제 구독을 통해 데이터 백업 및 복원 작업이 계속 수행됩니다. 예를 들어, 10TiB BYOL 라이센스가 있는 경우 PAYGO 구독을 통해 10TiB를 초과하는 모든 용량이 충전됩니다.


무료 평가판 사용 중 또는 BYOL 라이센스를 초과하지 않는 경우 용량제 구독을 통해 요금이 부과되지 않습니다.

BlueXP 백업 및 복구를 위한 몇 가지 PAYGO 계획이 있습니다.

* Cloud Volumes ONTAP 데이터와 사내 ONTAP 데이터를 백업할 수 있는 "클라우드 백업" 패키지
* Cloud Volumes ONTAP 및 BlueXP 백업 및 복구를 번들로 제공할 수 있는 "CVO Professional" 패키지입니다. 여기에는 라이센스를 사용하는 Cloud Volumes ONTAP 시스템에 대한 무제한 백업이 포함됩니다(백업 용량은 라이센스 용량에 포함되지 않음). 이 옵션을 사용하면 사내 ONTAP 데이터를 백업할 수 없습니다.
+
이 옵션을 사용하려면 백업 및 복구 PAYGO 가입도 필요하지만 적격 Cloud Volumes ONTAP 시스템에 대해서는 비용이 발생하지 않습니다.



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["이러한 용량 기반 라이센스 패키지에 대해 자세히 알아보십시오"].

다음 링크를 사용하여 클라우드 공급자 마켓플레이스에서 BlueXP 백업 및 복구를 구독하십시오.

ifdef::aws[]

* AWS https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["가격에 대한 자세한 내용은 NetApp 지능형 서비스 마켓플레이스 오퍼링을 참조하십시오"^]:


endif::aws[]

ifdef::azure[]

* Azure는 다음과 https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["가격에 대한 자세한 내용은 NetApp 지능형 서비스 마켓플레이스 오퍼링을 참조하십시오"^]같습니다.


endif::azure[]

ifdef::gcp[]

* Google 클라우드 https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["가격에 대한 자세한 내용은 NetApp 지능형 서비스 마켓플레이스 오퍼링을 참조하십시오"^]:


endif::gcp[]



== 연간 계약을 사용합니다

연간 계약을 구매하여 BlueXP 백업 및 복구에 대한 비용을 매년 지불합니다. 1년, 2년 또는 3년 기간으로 제공됩니다.

시장에서 연간 계약을 맺은 경우, 모든 BlueXP 백업 및 복구 소비에 대해 해당 계약에 대해 비용이 청구됩니다. BYOL은 연간 시장 계약을 혼합 및 일치시킬 수 없습니다.

ifdef::aws[]

AWS를 사용할 경우 에서 2개의 연간 계약을 얻을 수 있습니다 https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWS 마켓플레이스 페이지를 참조하십시오"^] Cloud Volumes ONTAP 및 온프레미스 ONTAP 시스템의 경우:

* Cloud Volumes ONTAP 데이터와 사내 ONTAP 데이터를 백업할 수 있는 '클라우드 백업' 계획
+
이 옵션을 사용하려면 마켓플레이스 페이지에서 구독을 설정한 다음 https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["가입 정보를 AWS 자격 증명과 연결합니다"^]. 또한 BlueXP에서 AWS 자격 증명에 활성 서브스크립션을 하나만 할당할 수 있으므로 이 연간 계약 가입을 통해 Cloud Volumes ONTAP 시스템에 대한 비용을 지불해야 합니다.

* Cloud Volumes ONTAP 및 BlueXP 백업 및 복구를 번들로 제공할 수 있는 "CVO Professional" 계획입니다. 여기에는 라이센스를 사용하는 Cloud Volumes ONTAP 시스템에 대한 무제한 백업이 포함됩니다(백업 용량은 라이센스 용량에 포함되지 않음). 이 옵션을 사용하면 사내 ONTAP 데이터를 백업할 수 없습니다.
+
를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이센스 항목을 참조하십시오"^] 이 라이센스 옵션에 대해 자세히 알아보십시오.

+
이 옵션을 사용하려면 Cloud Volumes ONTAP 작업 환경을 생성할 때 연간 계약을 설정하고 BlueXP에서 AWS 마켓플레이스에 가입하라는 메시지를 표시합니다.



endif::aws[]

ifdef::azure[]

Azure를 사용하는 경우 에서 두 개의 연간 계약을 사용할 수 있습니다 https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Azure 마켓플레이스 페이지"^] Cloud Volumes ONTAP 및 온프레미스 ONTAP 시스템의 경우:

* Cloud Volumes ONTAP 데이터와 사내 ONTAP 데이터를 백업할 수 있는 '클라우드 백업' 계획
+
이 옵션을 사용하려면 마켓플레이스 페이지에서 구독을 설정한 다음 https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html#subscribe["구독을 Azure 자격 증명에 연결합니다"^]. BlueXP에서 하나의 활성 구독만 Azure 자격 증명에 할당할 수 있으므로 이 연간 계약 구독을 사용하여 Cloud Volumes ONTAP 시스템에 대한 비용도 지불하셔야 합니다.

* Cloud Volumes ONTAP 및 BlueXP 백업 및 복구를 번들로 제공할 수 있는 "CVO Professional" 계획입니다. 여기에는 라이센스를 사용하는 Cloud Volumes ONTAP 시스템에 대한 무제한 백업이 포함됩니다(백업 용량은 라이센스 용량에 포함되지 않음). 이 옵션을 사용하면 사내 ONTAP 데이터를 백업할 수 없습니다.
+
를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이센스 항목을 참조하십시오"^] 이 라이센스 옵션에 대해 자세히 알아보십시오.

+
이 옵션을 사용하려면 Cloud Volumes ONTAP 작업 환경을 생성할 때 연간 계약을 설정하면 BlueXP가 Azure 마켓플레이스를 구독하라는 메시지를 표시합니다.



endif::azure[]

ifdef::gcp[]

GCP를 사용할 경우 NetApp 세일즈 담당자에게 연간 계약을 구매할 것을 문의하십시오. 이 계약은 Google Cloud Marketplace에서 프라이빗 오퍼로 제공됩니다.

NetApp이 프라이빗 오퍼를 공유하면 BlueXP 백업 및 복구 활성화 중에 Google Cloud 마켓플레이스를 구독할 때 연간 계획을 선택할 수 있습니다.

endif::gcp[]



== BlueXP 백업 및 복구 BYOL 라이센스 사용

NetApp에서 제공하는 자체 라이센스는 1년, 2년 또는 3년간 제공됩니다. 백업 중인 소스 ONTAP 볼륨의 논리적 사용 용량(_before_any 효율성)으로 계산되어 보호하는 데이터에 대해서만 비용을 지불하면 됩니다. 이 용량을 FETB(Front-End Terabytes)라고도 합니다.

BYOL BlueXP  백업 및 복구 라이센스는 부동 라이센스로, 총 용량이 BlueXP  조직 또는 계정과 연결된 모든 시스템에서 공유됩니다. ONTAP 시스템의 경우 백업하려는 볼륨에 대해 CLI 명령을 실행하여 필요한 용량을 대략적으로 예측할 수 `volume show -fields logical-used-by-afs` 있습니다.

BlueXP 백업 및 복구 BYOL 라이센스가 없는 경우 BlueXP 오른쪽 하단의 채팅 아이콘을 클릭하여 라이센스를 구입하십시오.

선택적으로 사용하지 않을 Cloud Volumes ONTAP에 대해 할당되지 않은 노드 기반 라이센스가 있는 경우 동일한 달러 당량 및 만료 날짜가 있는 BlueXP 백업 및 복구 라이센스로 전환할 수 있습니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["자세한 내용을 보려면 여기를 클릭하십시오"^].

BlueXP 디지털 지갑을 사용하여 BYOL 라이센스를 관리합니다. BlueXP 디지털 지갑에서 새 라이센스를 추가하고 기존 라이센스를 업데이트하고 라이센스 상태를 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["디지털 지갑을 사용하여 라이선스를 추가하는 방법에 대해 알아봅니다"^]..
