---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory, bluexp 
summary: BlueXP 백업 및 복구 보고서를 사용하면 조직의 정의된 정책에 따라 중요한 데이터를 보호하고 규정 준수 프로세스에 대한 감사를 효율적으로 지원할 수 있습니다. 백업 인벤토리 보고서를 사용하면 특정 계정, 작업 환경 또는 SVM 인벤토리에 대한 모든 백업을 볼 수 있습니다. 
---
= BlueXP 백업 및 복구를 통한 데이터 보호 범위에 대한 보고서
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 백업 및 복구 보고서를 사용하면 조직의 정의된 정책에 따라 중요 데이터가 보호되는지 확인하고 규정 준수 요구 사항에 대한 감사를 제공할 수 있습니다.

BlueXP 백업 및 복구 보고서를 통해 다음과 같은 작업을 수행할 수 있습니다.

* * 운영 가시성 *: 데이터 보호, 백업 성공률 및 비즈니스 요구에 따른 백업 윈도우 정렬과 관련된 서비스 수준 계약을 모니터링합니다.
* * 규정 준수 및 감사 *: 지속적인 규정 준수 모니터링을 위해 내부 및 외부 감사 프로세스에서 운영 및 인벤토리 보고서를 사용합니다.



NOTE: 보고서 활동은 모든 활동을 감사할 수 있도록 작업 모니터링 로그에서 모니터링됩니다. link:task-monitor-backup-jobs.html["작업 모니터링에 대해 자세히 알아보십시오"].



== 보고서 범위

BlueXP 백업 및 복구 보고서는 다음과 같은 측면에 대한 정보를 제공합니다.

* * 커넥터 위치 *: 사내 또는 클라우드
* * 소스 *: Cloud Volumes ONTAP 볼륨, 온프레미스 ONTAP 볼륨 또는 응용 프로그램
* * 대상 *: 클라우드 공급자, NetApp StorageGRID 또는 ONTAP S3
* * ONTAP 버전 *: 9.13.0




== 백업 인벤토리 보고서를 생성합니다

BlueXP 백업 및 복구 보고서 탭에서 백업 인벤토리 보고서를 생성하고 해당 내용을 필터링할 수 있습니다. Backup Inventory 보고서를 사용하면 특정 계정, 작업 환경 또는 SVM 인벤토리에 대한 모든 백업을 볼 수 있습니다.

백업 인벤토리 보고서는 다음 정보를 보여 줍니다.

* 고객, 작업 환경 및 SVM
* 보호 및 비보호 볼륨
* 백업 타겟
* 백업 정책이 적용되었습니다
* 암호화 스타일(공급자 관리 키 또는 사용자 관리 키)
* DataLock 및 랜섬웨어 보호 상태(거버넌스, 규정 준수 또는 없음)
* 아카이브 사용 상태입니다
* 백업 복사본 수입니다
* 백업 유형(예약된 백업 또는 사용자가 시작한 임시 백업)
* 스토리지 클래스
* 스냅샷 레이블



NOTE: 백업 인벤토리 보고서에는 만료 또는 실패한 백업 정보가 포함되지 않습니다.

보고서 상단에는 다음 정보를 보여주는 그래프가 있습니다.

* 하나 이상의 백업을 포함하는 범위의 볼륨 수입니다
* 총 비활성 볼륨 + 활성 볼륨


백업 인벤토리 보고서는 다음 차트를 보여 줍니다.

* * 볼륨 백업 상태 *: 선택한 범위에 대해 보호되지 않은 볼륨과 비교하여 보호된 볼륨이 표시됩니다.
* * Backup Count 별 볼륨 *: 이 볼륨에 대해 사용 가능한 백업 복제본 수를 기준으로 볼륨을 그룹합니다.


.단계
. 상단 메뉴에서 * Reports * 를 선택합니다.
. 백업 인벤토리 * 를 선택합니다.
. 보고서 작성 * 을 선택합니다.
. 계정, 작업 환경 및 SVM을 선택합니다.
+

TIP: 여러 작업 환경 및 SVM을 선택할 수 있습니다.

. 지난 24시간, 주 또는 월의 기간을 선택합니다.
. 보고서 선택에 따라 보고서 섹션(스냅샷 정책, 복제 정책 또는 백업 정책)을 검토합니다.
. (선택 사항) 작업 상태별로 결과를 필터링합니다.
. (선택 사항) * CSV 다운로드 * 를 선택하여 보고서 내용을 .csv 형식으로 내보냅니다.




== 데이터 보호 작업 활동 보고서를 생성합니다

사전 예방 모니터링을 통해 에코시스템의 모든 리소스를 모니터링하는 데 필요한 노력을 줄일 수 있습니다. ONTAP 9.13.0부터 데이터 보호 작업 활동 보고서는 SLA 모니터링과 백업 및 복구 속도를 추적하는 데 사용할 수 있는 스냅샷, 백업, 클론 및 복원 작업에 대한 정보를 제공합니다.

이 보고서는 Cloud Volumes ONTAP, 사내 및 애플리케이션 데이터에 대한 BlueXP  백업 및 복구 작업에 적용됩니다.

데이터 보호 작업 활동 보고서에는 다음과 같은 정보가 표시됩니다.

* 고객, 작업 환경 및 SVM
* 작업 유형(백업 또는 복원)
* 리소스 이름(볼륨 또는 애플리케이션)
* 작업 상태입니다
* 시작 및 종료 시간 및 기간
* 백업 작업에 대한 정책 이름입니다
* 백업 작업에 대한 스냅샷 레이블입니다


페이지 맨 위의 차트는 다음 정보를 표시합니다.

* 유형별 작업
+
** ONTAP 볼륨 백업 및 복원 작업의 수입니다
** 애플리케이션 백업 및 복원 작업의 수입니다
** 가상 머신 백업 및 복원 작업 수입니다


* 일일 작업 활동


.단계
. 상단 메뉴에서 * Reports * 를 선택합니다.
. 데이터 보호 작업 활동 * 을 선택합니다.
. 보고서 작성 * 을 선택합니다.
. 계정, 작업 환경 및 SVM을 선택합니다.
. 지난 24시간, 주 또는 월의 기간을 선택합니다.
. (선택 사항) 작업 상태, 작업 유형(백업 또는 복원) 및 리소스별로 결과를 필터링합니다.
. (선택 사항) * CSV 다운로드 * 를 선택하여 보고서 내용을 .csv 형식으로 내보냅니다.

