---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: Cloud Backup의 새로운 기능에 대해 알아보십시오. 
---
= 클라우드 백업의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup의 새로운 기능에 대해 알아보십시오.



== 2022년 9월 30일



=== 애플리케이션의 클라우드 백업 개선

* Google Cloud Provider(GCP) 및 StorageGRID를 지원하여 애플리케이션 정합성 보장 스냅샷을 백업합니다
* 사용자 지정 정책을 생성합니다
* 아카이브 스토리지 지원
* SAP HANA 애플리케이션 백업
* VMware 환경에 있는 Oracle 및 SQL 애플리케이션을 백업합니다
* 사내 2차 스토리지에서 애플리케이션을 백업합니다
* 백업을 비활성화합니다
* SnapCenter 서버 등록을 취소합니다




=== 가상 머신용 Cloud Backup의 향상된 기능

* 하나 이상의 데이터 저장소를 백업하기 위해 StorageGRID를 지원합니다
* 사용자 지정 정책을 생성합니다




== 2022년 9월 19일



=== StorageGRID 시스템의 백업 파일에 대해 DataLock 및 랜섬웨어 보호를 구성할 수 있습니다

마지막 릴리즈에서는 Amazon S3 버킷에 저장된 백업에 대해 _DataLock 및 랜섬웨어 보호_가 도입되었습니다. 이 릴리즈는 StorageGRID 시스템에 저장된 백업 파일에 대한 지원을 확장합니다. 클러스터가 ONTAP 9.11.1 이상을 사용하고 있고 StorageGRID 시스템에서 버전 11.6.0.3 이상을 실행 중인 경우 이 새로운 백업 정책 옵션을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].

버전 3.9.22 이상의 소프트웨어가 있는 커넥터를 실행해야 합니다. Connector는 구내에 설치해야 하며 인터넷에 접속하거나 접속하지 않은 사이트에 설치할 수 있습니다.



=== 이제 백업 파일에서 폴더 레벨 복구를 사용할 수 있습니다

이제 해당 폴더(디렉토리 또는 공유)의 모든 파일에 액세스해야 하는 경우 백업 파일에서 폴더를 복원할 수 있습니다. 폴더 복원은 전체 볼륨을 복원하는 것보다 훨씬 효율적입니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다. 현재 단일 폴더만 선택하고 복원할 수 있으며, 해당 폴더의 파일만 복원할 수 있습니다. 하위 폴더 또는 하위 폴더의 파일은 복원되지 않습니다.



=== 이제 아카이브 스토리지로 이동한 백업에서 파일 레벨 복구를 사용할 수 있습니다

과거에는 아카이브 스토리지(AWS 및 Azure만 해당)로 이동한 백업 파일의 볼륨만 복원할 수 있었습니다. 이제 이러한 아카이빙된 백업 파일에서 개별 파일을 복원할 수 있습니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 이제 파일 레벨 복구를 통해 원본 소스 파일을 덮어쓸 수 있습니다

이전에는 원래 볼륨으로 복구된 파일이 항상 "Restore_<file_name>"이라는 접두사가 붙은 새 파일로 복원되었습니다. 이제 파일을 볼륨의 원래 위치로 복구할 때 원본 소스 파일을 덮어쓰도록 선택할 수 있습니다. 이 기능은 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 끌어서 놓기를 통해 클라우드 백업을 StorageGRID 시스템에 사용할 수 있습니다

를 누릅니다 https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 백업 대상은 Canvas에 작업 환경으로 있으며, 온프레미스 ONTAP 작업 환경을 대상으로 끌어서 클라우드 백업 설정 마법사를 시작할 수 있습니다.



== 2022년 8월 18일



=== 클라우드 네이티브 애플리케이션 데이터를 보호하기 위해 지원이 추가되었습니다

Cloud Backup for Applications는 NetApp 클라우드 스토리지에서 실행되는 애플리케이션에 데이터 보호 기능을 제공하는 SaaS 기반 서비스입니다. Cloud Manager 내에서 지원되는 Cloud Backup for Applications는 NetApp ONTAP용 Amazon FSx에 상주하는 Oracle 데이터베이스의 효율적이고 애플리케이션 정합성이 보장된 정책 기반 백업 및 복원을 제공합니다.https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html["자세한 정보"^].



=== 검색 및 복원은 이제 Azure Blob의 백업 파일에서 지원됩니다

이제 Azure Blob 저장소에 백업 파일을 저장하는 사용자가 볼륨 및 파일을 복원하는 검색 및 복원 방법을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["검색 및 amp;Restore를 사용하여 볼륨 및 파일을 복원하는 방법을 확인하십시오"^].

이 기능을 사용하려면 커넥터 역할에 추가 권한이 필요합니다. 버전 3.9.21 소프트웨어(2022년 8월)를 사용하여 배포된 커넥터에는 이러한 권한이 포함됩니다. 이전 릴리스를 사용하여 Connector를 배포한 경우 사용 권한을 수동으로 추가해야 합니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["필요한 경우 이러한 사용 권한을 추가하는 방법을 알아봅니다"^].



=== NetApp은 백업 파일이 삭제 및 랜섬웨어 공격으로부터 보호할 수 있는 기능을 추가했습니다

Cloud Backup은 이제 랜섬웨어 세이프 백업에 대한 오브젝트 잠금을 지원합니다. 클러스터가 ONTAP 9.11.1 이상을 사용하고 있고 백업 대상이 Amazon S3인 경우, _DataLock 및 랜섬웨어 보호_라는 새로운 백업 정책 옵션을 사용할 수 있습니다. DataLock은 백업 파일의 수정 또는 삭제를 방지하고, 랜섬웨어 방지 기능은 백업 파일을 검사하여 백업 파일에 대한 랜섬웨어 공격의 증거를 찾습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].

이 기능을 사용하려면 커넥터 역할에 추가 권한이 필요합니다. 버전 3.9.21 소프트웨어를 사용하여 배포된 Connector에는 이러한 권한이 포함되어 있습니다. 이전 릴리스를 사용하여 Connector를 배포한 경우 사용 권한을 수동으로 추가해야 합니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions["필요한 경우 이러한 사용 권한을 추가하는 방법을 알아봅니다"^].



=== 이제 Cloud Backup은 사용자 지정 SnapMirror 레이블을 사용하여 생성된 정책을 지원합니다

이전에는 Cloud Backup이 매시간, 매일, 매주, 시간별, 연도별 등의 미리 정의된 SnapMirror 레이블만 지원했습니다. 이제 Cloud Backup은 System Manager 또는 CLI를 사용하여 만든 사용자 지정 SnapMirror 레이블이 있는 SnapMirror 정책을 검색할 수 있습니다. 이러한 새 레이블은 Cloud Backup UI에 표시되므로 선택한 SnapMirror 레이블을 사용하여 볼륨을 클라우드에 백업할 수 있습니다.



=== ONTAP 시스템에 대한 추가 백업 정책 개선 사항

일부 백업 정책 페이지는 각 ONTAP 클러스터의 볼륨에 사용할 수 있는 모든 백업 정책을 보다 쉽게 볼 수 있도록 재설계되었습니다. 따라서 사용 가능한 정책의 세부 정보를 더 쉽게 볼 수 있으므로 볼륨에 최상의 정책을 적용할 수 있습니다.



=== 끌어서 놓기를 통해 Cloud Backup을 Azure Blob 및 Google Cloud Storage로 이동할 수 있습니다

를 누릅니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html["Azure Blob"^] 또는 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html["Google 클라우드 스토리지"^] 백업 대상이 Canvas에 작업 환경으로 존재합니다. 온프레미스 ONTAP 또는 Cloud Volumes ONTAP 작업 환경(Azure 또는 GCP에 설치됨)을 대상으로 끌어서 백업 설정 마법사를 시작할 수 있습니다.

이 기능은 Amazon S3 버킷에 이미 존재합니다.



== 2022년 7월 13일



=== SnapLock 엔터프라이즈 볼륨을 백업하는 데 지원이 추가되었습니다

이제 클라우드 백업을 사용하여 SnapLock 엔터프라이즈 볼륨을 퍼블릭 및 프라이빗 클라우드에 백업할 수 있습니다. 이 기능을 사용하려면 ONTAP 시스템에서 ONTAP 9.11.1 이상을 실행해야 합니다. 그러나 SnapLock 규정 준수 볼륨은 현재 지원되지 않습니다.



=== 이제 온-프레미스 Connector를 사용할 때 퍼블릭 클라우드에서 백업 파일을 만들 수 있습니다

이전에는 백업 파일을 생성하던 위치와 동일한 클라우드 공급자에 Connector를 구축해야 했습니다. 이제 사내에 구축된 Connector를 사용하여 온프레미스 ONTAP 시스템에서 Amazon S3, Azure Blob 및 Google Cloud Storage로 백업 파일을 생성할 수 있습니다. (StorageGRID 시스템에서 백업 파일을 생성할 때는 항상 내부 커넥터가 필요했습니다.)



=== ONTAP 시스템에 대한 백업 정책을 생성할 때 추가 기능을 사용할 수 있습니다

* 이제 연간 일정에 대한 백업을 사용할 수 있습니다. 기본 보존 값은 연간 백업의 경우 1이지만 이전 해 백업 파일을 여러 개 액세스하려는 경우 이 값을 변경할 수 있습니다.
* 백업 정책의 이름을 지정하여 보다 자세한 설명이 포함된 텍스트를 사용하여 정책을 식별할 수 있습니다.




== 2022년 6월 14일



=== 인터넷에 연결되지 않은 사이트에서 사내 ONTAP 클러스터 데이터를 백업하는 데 지원이 추가되었습니다

사내 ONTAP 클러스터가 인터넷 액세스가 연결되지 않은 사이트에 있는 경우, 다크 사이트 또는 오프라인 사이트라고도 합니다. 이제 Cloud Backup을 사용하여 볼륨 데이터를 동일한 사이트에 있는 NetApp StorageGRID 시스템에 백업할 수 있습니다. 이 기능을 사용하려면 Cloud Manager Connector(버전 3.9.19 이상)도 오프라인 사이트에 배포해야 합니다.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["오프라인 사이트에 커넥터를 설치하는 방법을 알아봅니다"].https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html["오프라인 사이트에서 ONTAP 데이터를 StorageGRID에 백업하는 방법을 알아봅니다"].



=== Cloud Backup for Virtual Machines 1.1.0이 현재 GA로 제공됩니다

SnapCenter Plug-in for VMware vSphere를 Cloud Manager와 통합하면 가상 머신의 데이터를 보호할 수 있습니다. 데이터 저장소를 클라우드에 백업하고 VMware vSphere용 사내 SnapCenter 플러그인으로 가상 머신을 간편하게 복원할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html["가상 시스템을 클라우드로 보호하는 방법에 대해 자세히 알아보십시오"].



=== ONTAP 찾아보기 및 복원 기능에는 클라우드 복원 인스턴스가 필요하지 않습니다

S3 및 Blob 스토리지에서 파일 레벨 찾아보기 및 복원 작업에 사용되는 별도의 클라우드 복원 인스턴스/가상 머신. 이 인스턴스는 사용하지 않을 때 종료되지만 파일을 복원할 때 약간의 시간과 비용이 추가되었습니다. 이 기능은 필요 시 Connector에 배포되는 무료 컨테이너로 대체되었습니다. 다음과 같은 이점을 제공합니다.

* 파일 레벨 복구 작업에 대한 추가 비용 없음
* 파일 레벨 복구 작업 속도 향상
* Connector가 사내에 설치된 경우 클라우드에서 파일에 대한 찾아보기 및 복원 작업 지원


이전에 클라우드 복원 인스턴스/VM을 사용한 경우 자동으로 제거됩니다. Cloud Backup 프로세스는 모든 이전 Cloud Restore 인스턴스를 삭제하기 위해 하루에 한 번 실행됩니다. 이 변경 사항은 완전히 투명하게 나타납니다. 데이터에는 영향을 주지 않으며 백업 또는 복원 작업이 변경되지 않습니다.



=== Google Cloud 및 StorageGRID 스토리지에서 파일에 대한 찾아보기 및 복원 지원

위에서 설명한 대로 Browse & Restore 작업에 대한 컨테이너가 추가되어 Google Cloud 및 StorageGRID 시스템에 저장된 백업 파일에서 파일 복원 작업을 수행할 수 있습니다. 이제 Browse & Restore를 사용하여 모든 퍼블릭 클라우드 공급자 및 StorageGRID에서 파일을 복원할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["ONTAP 백업에서 볼륨 및 파일을 복원하기 위해 Browse  amp; Restore를 사용하는 방법을 확인하십시오"].



=== 끌어서 놓기를 통해 Cloud Backup을 S3 스토리지로 설정합니다

백업에 대한 Amazon S3 대상이 Canvas의 작업 환경으로 존재하는 경우, 온프레미스 ONTAP 클러스터 또는 Cloud Volumes ONTAP 시스템(AWS에 설치됨)을 Amazon S3 작업 환경으로 끌어서 설정 마법사를 시작할 수 있습니다.



=== Kubernetes 클러스터에서 새로 생성된 볼륨에 백업 정책을 자동으로 적용합니다

Cloud Backup을 활성화한 후 Kubernetes 클러스터에 새로운 영구 볼륨을 추가한 경우에는 이전에 해당 볼륨에 대한 백업을 구성해야 했습니다. 이제 새로 생성된 볼륨에 자동으로 적용되는 정책을 선택할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["백업 설정 페이지에서"] 이미 Cloud Backup을 활성화한 클러스터의 경우



=== 이제 Cloud Backup API를 사용하여 백업 및 복원 작업을 관리할 수 있습니다

API는 에서 사용할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html[]. 을 참조하십시오 link:api-backup-restore.html["이 페이지"] API에 대한 개요입니다.



== 2022년 5월 2일



=== 검색 및 복원은 이제 Google Cloud Storage의 백업 파일에서 지원됩니다

4월에 AWS에 백업 파일을 저장한 사용자를 위해 볼륨 및 파일 복원 검색 및 복원 방법이 도입되었습니다. 이제 Google Cloud Storage에 백업 파일을 저장하는 사용자가 이 기능을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["검색 및 amp;Restore를 사용하여 볼륨 및 파일을 복원하는 방법을 확인하십시오"].



=== Kubernetes 클러스터에서 새로 생성된 볼륨에 자동으로 적용할 백업 정책을 구성합니다

Cloud Backup을 활성화한 후 Kubernetes 클러스터에 새로운 영구 볼륨을 추가한 경우에는 이전에 해당 볼륨에 대한 백업을 구성해야 했습니다. 이제 새로 생성된 볼륨에 자동으로 적용되는 정책을 선택할 수 있습니다. 이 옵션은 새 Kubernetes 클러스터에 대한 Cloud Backup을 활성화할 때 설정 마법사에서 사용할 수 있습니다.



=== 이제 작업 환경에서 Cloud Backup을 활성화하려면 라이센스가 필요합니다

Cloud Backup에서 라이센스를 구축하는 방법은 다음과 같이 몇 가지 변경되었습니다.

* Cloud Backup을 활성화하려면 먼저 클라우드 공급자로부터 PAYGO Marketplace 구독에 가입하거나 NetApp에서 BYOL 라이센스를 구입해야 합니다.
* 30일 무료 평가판은 클라우드 공급자가 PAYGO 구독을 사용하는 경우에만 사용할 수 있으며 BYOL 라이센스를 사용하는 경우에는 사용할 수 없습니다.
* 무료 평가판은 마켓플레이스 가입이 시작되는 날부터 시작됩니다. 예를 들어, Cloud Volumes ONTAP 시스템에 대해 30일 동안 Marketplace 구독을 사용한 후 무료 평가판을 활성화하면 클라우드 백업 평가판을 사용할 수 없습니다.


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html["사용 가능한 라이센스 모델에 대해 자세히 알아보십시오"].



== 2022년 4월 4일



=== SnapCenter에 기반을 둔 애플리케이션 클라우드 백업 1.1.0 이 현재 GA입니다

새로운 Cloud Backup for Applications 기능을 사용하면 Oracle 및 Microsoft SQL에 대한 기존 애플리케이션 정합성 보장 스냅샷(백업)을 사내 운영 스토리지에서 Amazon S3 또는 Azure Blob의 클라우드 오브젝트 스토리지로 오프로드할 수 있습니다.

필요한 경우 클라우드에서 사내로 데이터를 복원할 수 있습니다.

link:concept-protect-app-data-to-cloud.html["사내 애플리케이션 데이터를 클라우드로 보호하는 방법에 대해 자세히 알아보십시오"].



=== 모든 ONTAP 백업 파일에서 볼륨 또는 파일을 검색하는 새로운 검색 및 복원 기능

이제 일부 또는 전체 볼륨 이름, 일부 또는 전체 파일 이름, 크기 범위 및 추가 검색 필터를 통해 * 모든 ONTAP 백업 파일 * 에서 볼륨 또는 파일을 검색할 수 있습니다. 이 방법은 어떤 클러스터나 볼륨이 데이터의 소스인지 잘 모르면 복원하려는 데이터를 찾을 수 있는 새로운 방법입니다. link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["검색 및 amp;Restore 사용 방법에 대해 알아봅니다"].



== 2022년 3월 3일



=== GKE Kubernetes 클러스터에서 Google Cloud 스토리지로 영구 볼륨을 백업하는 기능

GKE 클러스터에 NetApp Astra Trident가 설치되어 있고 Cloud Volumes ONTAP for GCP를 클러스터의 백엔드 스토리지로 사용하는 경우, Google Cloud 스토리지와 영구 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-gcp.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== Cloud Data Sense를 사용하여 Cloud Backup 파일을 검사하는 베타 기능은 이 릴리즈에서 더 이상 제공되지 않습니다



== 2022년 2월 14일



=== 이제 단일 클러스터의 개별 볼륨에 백업 정책을 할당할 수 있습니다

과거에는 클러스터의 모든 볼륨에 단일 백업 정책만 할당할 수 있었습니다. 이제 단일 클러스터에 대해 여러 백업 정책을 생성하고 여러 볼륨에 서로 다른 정책을 적용할 수 있습니다. link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["클러스터에 대한 새 백업 정책을 생성하고 이를 선택한 볼륨에 할당하는 방법을 알아보십시오"].



=== 새 옵션을 사용하면 새로 생성된 볼륨에 기본 백업 정책을 자동으로 적용할 수 있습니다

과거에는 Cloud Backup을 활성화한 후 작업 환경에서 생성된 새 볼륨을 수동으로 백업 정책을 적용해야 했습니다. 이제 Cloud Manager, System Manager, CLI 또는 API에서 볼륨이 생성되었는지에 관계없이 Cloud Backup은 볼륨을 검색하고 선택한 백업 정책을 기본 정책으로 적용합니다.

이 옵션은 새 작업 환경에서 백업을 설정하거나 기존 작업 환경의 _Manage Volumes_페이지에서 백업을 설정할 때 사용할 수 있습니다.



=== 새 작업 모니터를 사용하여 모든 백업 및 복원 작업의 진행 상태를 확인할 수 있습니다

백업 정책 변경 또는 백업 삭제와 같이 여러 볼륨에 대해 작업을 시작한 경우 작업 모니터를 사용하면 모든 볼륨에서 작업이 완료된 시점을 확인할 수 있습니다. link:task-monitor-backup-jobs.html["작업 모니터 사용 방법을 참조하십시오"].



== 2022년 1월 2일



=== AKS Kubernetes 클러스터에서 Azure Blob 스토리지로 영구 볼륨을 백업할 수 있습니다

AKS 클러스터에 NetApp Astra Trident가 설치되어 있고 Azure용 Cloud Volumes ONTAP를 클러스터용 백엔드 스토리지로 사용하는 경우, Azure Blob 스토리지간에 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-azure.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== 업계 표준에 더욱 부합하도록 이번 릴리스에서 Cloud Backup Service 요금이 변경되었습니다

백업 파일의 크기에 따라 NetApp의 용량을 지불하는 대신, 현재 백업 중인 소스 ONTAP 볼륨의 논리적 사용 용량(ONTAP 효율성 이전)을 기준으로 계산한, 보호하는 데이터에 대해서만 비용을 지불하면 됩니다. 이 용량을 FETB(Front-End Terabytes)라고도 합니다.



== 2021년 11월 28일



=== EKS Kubernetes 클러스터에서 Amazon S3로 영구 볼륨을 백업하는 기능

EKS 클러스터에 NetApp Astra Trident가 설치되어 있고 Cloud Volumes ONTAP for AWS를 클러스터의 백엔드 스토리지로 사용하는 경우 Amazon S3로 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-s3.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== DP 볼륨을 백업하는 향상된 기능

Cloud Backup은 이제 SVM-DR 관계의 타겟 ONTAP 시스템에 있는 DP 볼륨의 백업을 생성할 수 있도록 지원합니다. 몇 가지 제한 사항이 있습니다. 을 참조하십시오 link:concept-ontap-backup-to-cloud.html#limitations["제한 사항"] 를 참조하십시오.



== 2021년 11월 5일



=== 온프레미스 ONTAP 시스템으로 볼륨을 복원할 때 개인 엔드포인트를 선택할 수 있습니다

Amazon S3 또는 Azure Blob에 있는 백업 파일에서 온프레미스 ONTAP 시스템으로 볼륨을 복원할 때 온프레미스 시스템에 안전하게 비공개로 연결하는 프라이빗 끝점을 선택할 수 있습니다.



=== 이제 며칠 후 오래된 백업 파일을 아카이브 스토리지에 계층화하여 비용을 절감할 수 있습니다

클러스터에서 ONTAP 9.10.1 이상이 실행 중이고 AWS 또는 Azure 클라우드 스토리지를 사용 중인 경우 백업을 아카이브 스토리지에 계층화할 수 있습니다. 에 대한 자세한 내용을 참조하십시오 link:reference-aws-backup-tiers.html["AWS S3 아카이빙 스토리지 클래스"] 및 link:reference-azure-backup-tiers.html["Azure Blob 아카이브 액세스 계층"].



=== Cloud Backup BYOL 라이센스는 Digital Wallet의 Data Services Licenses 탭으로 이동했습니다

Cloud Backup에 대한 BYOL 라이센스는 Cloud Backup Licenses 탭에서 Cloud Manager Digital Wallet의 Data Services Licenses 탭으로 이동했습니다.



== 2021년 10월 4일



=== 이제 볼륨 또는 파일 복원을 수행할 때 백업 페이지에서 백업 파일 크기를 사용할 수 있습니다

불필요한 대용량 백업 파일을 삭제하거나 백업 파일 크기를 비교하여 악성 소프트웨어 공격으로 인해 발생할 수 있는 비정상적인 백업 파일을 확인할 수 있는 경우에 유용합니다.



=== TCO 계산기를 사용하여 클라우드 백업 비용을 비교할 수 있습니다

총 소유 비용 계산기는 Cloud Backup의 총 소유 비용을 파악하고 이러한 비용을 기존 백업 솔루션과 비교하고 잠재적인 절감 효과를 추정하는 데 도움이 됩니다. 확인해 보십시오https://cloud.netapp.com/cloud-backup-service-tco-calculator["여기"^].



=== 작업 환경의 클라우드 백업 등록을 취소하는 기능입니다

이제 손쉽게 할 수 있습니다 link:task_manage_backups.html#unregistering-cloud-backup-for-a-working-environment["작업 환경의 클라우드 백업 등록을 취소합니다"] 해당 작업 환경에 더 이상 백업 기능을 사용하지 않거나 비용이 청구되지 않는 경우



== 2021년 9월 2일



=== 볼륨의 필요 시 백업을 생성하는 기능입니다

이제 언제든지 주문형 백업을 생성하여 볼륨의 현재 상태를 캡처할 수 있습니다. 이 기능은 볼륨에 중요한 변경 사항이 있고 예약된 다음 백업이 해당 데이터를 보호할 때까지 기다리지 않으려는 경우에 유용합니다.

link:task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time["필요 시 백업을 생성하는 방법을 확인하십시오"].



=== Amazon S3에 대한 보안 백업을 위해 전용 인터페이스 연결을 정의하는 기능

온-프레미스 ONTAP 시스템에서 Amazon S3로 백업을 구성할 때 이제 활성화 마법사에서 전용 인터페이스 끝점에 대한 연결을 정의할 수 있습니다. 이를 통해 사내 시스템을 AWS PrivateLink 기반의 서비스에 안전하게 비공개로 연결하는 네트워크 인터페이스를 사용할 수 있습니다. link:task-backup-onprem-to-aws.html#preparing-amazon-s3-for-backups["이 옵션에 대한 자세한 내용을 참조하십시오"].



=== 이제 데이터를 Amazon S3에 백업할 때 데이터 암호화에 대해 자체 고객 관리 키를 선택할 수 있습니다

추가 보안 및 제어를 위해 기본 Amazon S3 암호화 키를 사용하는 대신 활성화 마법사에서 데이터 암호화에 대해 고객이 관리하는 키를 직접 선택할 수 있습니다. 이 기능은 사내 ONTAP 시스템 또는 AWS의 Cloud Volumes ONTAP 시스템에서 백업을 구성할 때 사용할 수 있습니다.



=== 이제 30,000개 이상의 파일이 있는 디렉토리에서 파일을 복원할 수 있습니다
