---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: Cloud Backup의 새로운 기능에 대해 알아보십시오. 
---
= 클라우드 백업의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup의 새로운 기능에 대해 알아보십시오.



== 2023년 1월 9일



=== StorageGRID 시스템에서 이전 백업 파일을 AWS S3 아카이브 스토리지로 이동 가능

이제 StorageGRID 시스템의 이전 백업 파일을 AWS S3의 아카이브 스토리지로 계층화할 수 있습니다. 이를 통해 StorageGRID 시스템의 공간을 절약하고, 이전 백업 파일에 저렴한 스토리지 클래스를 사용하여 비용을 절감할 수 있습니다. AWS S3 Glacier 또는 S3 Glacier Deep Archive 스토리지에 백업을 계층화하도록 선택할 수 있습니다.

이 기능은 클러스터에서 ONTAP 9.12.1 이상을 사용하고 StorageGRID 시스템에서 11.3 이상을 사용하는 경우 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["자세히 알아보기"].



=== Google Cloud에서 데이터 암호화를 위한 자체 고객 관리 키를 선택할 수 있습니다

ONTAP 시스템에서 Google 클라우드 스토리지로 데이터를 백업할 때 이제 Google에서 관리하는 기본 암호화 키를 사용하는 대신 활성화 마법사에서 데이터 암호화에 대해 고객이 관리하는 키를 직접 선택할 수 있습니다. 먼저 고객이 관리하는 암호화 키를 설정한 다음 Cloud Backup을 활성화할 때 세부 정보를 입력합니다.



=== Google Cloud Storage에서 백업을 생성하는 서비스 계정에 더 이상 "스토리지 관리자" 역할이 필요하지 않습니다

이전 릴리즈에서는 Cloud Backup이 Google Cloud Storage 버킷에 액세스할 수 있도록 서비스 계정에 "Storage Admin" 역할이 필요했습니다. 이제 서비스 계정에 할당할 수 있는 권한이 축소된 사용자 지정 역할을 만들 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["백업을 위해 Google Cloud Storage를 준비하는 방법을 알아보십시오"].



=== 인터넷 액세스 없이 사이트에서 검색 및 복원을 사용하여 데이터를 복원할 수 있도록 지원이 추가되었습니다

인터넷에 액세스할 수 없는 사이트의 ONTAP 클러스터 데이터를 StorageGRID으로 백업하는 경우(다크 사이트 또는 오프라인 사이트라고도 함), 이제 검색 및 복원 옵션을 사용하여 필요한 경우 데이터를 복원할 수 있습니다. 이 기능을 사용하려면 BlueXP 커넥터(버전 3.9.25 이상)가 오프라인 사이트에 배포되어야 합니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["검색 및 amp; 복원을 사용하여 ONTAP 데이터를 복원하는 방법을 확인하십시오"].https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["오프라인 사이트에 커넥터를 설치하는 방법을 알아봅니다"].



=== 작업 모니터링 결과 페이지를 .csv 보고서로 다운로드할 수 있습니다

작업 모니터링 페이지를 필터링하여 관심 있는 작업 및 작업을 표시한 후에는 해당 데이터의 .csv 파일을 생성하고 다운로드할 수 있습니다. 그런 다음 정보를 분석하거나 조직의 다른 사용자에게 보고서를 보낼 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["작업 모니터링 보고서를 생성하는 방법을 참조하십시오"].



== 2022년 12월 19일



=== 애플리케이션의 클라우드 백업 개선

* SAP HANA 데이터베이스
+
** Azure NetApp Files(ANF)에 상주하는 SAP HANA 데이터베이스의 정책 기반 백업 및 복원 지원
** 사용자 지정 정책을 지원합니다


* Oracle 데이터베이스
+
** 호스트를 추가하고 플러그인을 자동으로 구축합니다
** 사용자 지정 정책을 지원합니다
** Cloud Volumes ONTAP에 상주하는 Oracle 데이터베이스의 정책 기반 백업, 복원 및 복제를 지원합니다
** NetApp ONTAP용 Amazon FSx에 상주하는 Oracle 데이터베이스의 정책 기반 백업 및 복원을 지원합니다
** 연결 및 복사 방법을 사용하여 Oracle 데이터베이스 복원을 지원합니다
** Oracle 21c를 지원합니다
** 클라우드 네이티브 Oracle 데이터베이스의 클론 복제 지원






=== 가상 머신용 Cloud Backup의 향상된 기능

* 가상 머신
+
** 사내 보조 스토리지에서 가상 머신 백업
** 사용자 지정 정책을 지원합니다
** 하나 이상의 데이터 저장소를 백업하기 위해 Google Cloud Platform(GCP) 지원
** Glacier, Deep Glacier 및 Azure Archive와 같은 저비용 클라우드 스토리지를 지원합니다






== 2022년 12월 6일



=== 필요한 커넥터 아웃바운드 인터넷 액세스 엔드포인트 변경

Cloud Backup의 변경으로 인해 Cloud Backup 작업을 성공적으로 수행하려면 다음 Connector 엔드포인트를 변경해야 합니다.

[cols="50,50"]
|===
| 이전 끝점 | 새 끝점 


| https://cloudmanager.cloud.netapp.com 으로 문의하십시오 | https://api.bluexp.netapp.com 으로 문의하십시오 


| https://*.cloudmanager.cloud.netapp.com 으로 문의하십시오 | https://*.api.bluexp.netapp.com 으로 문의하십시오 
|===
의 전체 끝점 목록을 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html#outbound-internet-access["설치하고"^], https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html#outbound-internet-access["Google 클라우드"^], 또는 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html#outbound-internet-access["Azure를 지원합니다"^] 설명합니다.



=== UI에서 Google Archival Storage 클래스를 선택할 수 있습니다

백업 파일은 처음에 Google Standard 스토리지 클래스에서 생성됩니다. 이제 Cloud Backup UI를 사용하여 추가 비용 최적화를 위해 일정 일 후에 이전 백업을 Google Archive 스토리지에 계층화할 수 있습니다.

이 기능은 현재 ONTAP 9.12.1 이상을 사용하는 온프레미스 ONTAP 클러스터에 지원됩니다. 현재 Cloud Volumes ONTAP 시스템에서는 사용할 수 없습니다.



=== FlexGroup 볼륨 지원

Cloud Backup은 이제 FlexGroup 볼륨 백업 및 복원을 지원합니다. ONTAP 9.12.1 이상을 사용하는 경우 FlexGroup 볼륨을 퍼블릭 및 프라이빗 클라우드 스토리지에 백업할 수 있습니다. FlexVol 및 FlexGroup 볼륨이 포함된 작업 환경이 있는 경우 ONTAP 소프트웨어를 업데이트하면 해당 시스템의 FlexGroup 볼륨을 백업할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html#supported-volumes["지원되는 볼륨 유형의 전체 목록을 참조하십시오"].



=== Cloud Volumes ONTAP 시스템의 백업에서 특정 애그리게이트로 데이터를 복원하는 기능

이전 릴리즈에서는 데이터를 사내 ONTAP 시스템으로 복원할 때만 애그리게이트를 선택할 수 있었습니다. 이제 이 기능은 데이터를 Cloud Volumes ONTAP 시스템으로 복원할 때 작동합니다.



== 2022년 11월 2일



=== 이전 Snapshot 복사본을 기본 백업 파일로 내보낼 수 있습니다

작업 환경에 백업 일정 레이블(예: 일별, 주별 등)과 일치하는 볼륨의 로컬 스냅샷 복사본이 있는 경우 이러한 기존 스냅샷을 백업 파일로 오브젝트 스토리지로 내보낼 수 있습니다. 이전 Snapshot 복사본을 기본 백업 복사본으로 이동하여 클라우드에서 백업을 초기화할 수 있습니다.

이 옵션은 작업 환경에서 Cloud Backup을 활성화할 때 사용할 수 있습니다. 나중에 에서 이 설정을 변경할 수도 있습니다 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html["고급 설정 페이지"].



=== 이제 소스 시스템에서 더 이상 필요하지 않은 볼륨을 아카이빙하는 데 Cloud Backup을 사용할 수 있습니다

이제 볼륨에 대한 백업 관계를 삭제할 수 있습니다. 이렇게 하면 새 백업 파일 생성을 중지하고 소스 볼륨을 삭제하지만 기존의 모든 백업 파일은 보존하려는 경우에 아카이빙 메커니즘이 제공됩니다. 따라서 나중에 필요할 경우 백업 파일에서 볼륨을 복원하는 동시에 소스 스토리지 시스템의 공간을 지울 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html#deleting-volume-backup-relationships["자세히 알아보기"].



=== 이메일 및 알림 센터에서 Cloud Backup 경고를 받도록 지원이 추가되었습니다

Cloud Backup이 BlueXP 알림 서비스에 통합되었습니다. BlueXP 메뉴 표시줄에서 알림 표시를 클릭하여 Cloud Backup 알림을 표시할 수 있습니다. 또한 시스템에 로그인하지 않은 경우에도 중요한 시스템 작업을 알 수 있도록 이메일로 알림을 보내도록 BlueXP를 구성할 수 있습니다. 이 이메일은 백업 및 복원 작업을 알아야 하는 모든 수신자에게 보낼 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["자세히 알아보기"].



=== 새로운 고급 설정 페이지에서는 클러스터 레벨 백업 설정을 변경할 수 있습니다

이 새 페이지에서는 각 ONTAP 시스템에 대한 클라우드 백업을 활성화할 때 설정하는 여러 클러스터 레벨 백업 설정을 변경할 수 있습니다. "기본" 백업 설정으로 적용되는 일부 설정을 수정할 수도 있습니다. 변경할 수 있는 전체 백업 설정은 다음과 같습니다.

* ONTAP 시스템에서 오브젝트 스토리지에 액세스할 수 있는 권한을 제공하는 스토리지 키입니다
* 백업을 객체 저장소에 업로드하기 위해 할당된 네트워크 대역폭입니다
* 이후 볼륨에 대한 자동 백업 설정(및 정책
* 아카이브 스토리지 클래스(AWS만 해당)
* 초기 기본 백업 파일에 기간별 스냅샷 복사본이 포함되어 있는지 여부
* 소스 시스템에서 "연간" 스냅샷을 제거할지 여부를 나타냅니다
* 오브젝트 스토리지에 연결된 ONTAP IPspace(활성화 중에 잘못 선택한 경우)


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html["클러스터 레벨 백업 설정 관리에 대해 자세히 알아보십시오"].



=== 이제 온-프레미스 Connector를 사용할 때 검색 및 복원을 사용하여 백업 파일을 복원할 수 있습니다

이전 릴리즈에서는 Connector가 사내에 구축될 때 퍼블릭 클라우드에 백업 파일을 생성하기 위한 지원이 추가되었습니다. 이 릴리즈에서는 검색 및 복원을 사용하여 Connector가 사내에 구축된 Amazon S3 또는 Azure Blob에서 백업을 복원할 수 있도록 지원이 계속 제공됩니다. 또한 검색 및 복원 기능은 StorageGRID 시스템에서 온-프레미스 ONTAP 시스템으로 지금 백업을 복원할 수 있도록 지원합니다.

현재 Google Cloud Storage에서 백업을 복원하려면 검색 및 복원을 사용할 때 Google Cloud Platform에 Connector를 구축해야 합니다.



=== 작업 모니터링 페이지가 업데이트되었습니다

다음 업데이트가 에 업데이트되었습니다 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html["작업 모니터링 페이지"]:

* "워크로드" 열을 사용할 수 있으므로 이 페이지를 필터링하여 볼륨, 애플리케이션, 가상 머신 및 Kubernetes의 백업 서비스에 대한 작업을 볼 수 있습니다.
* 특정 백업 작업에 대한 세부 정보를 보려면 "사용자 이름" 및 "작업 유형"에 대한 새 열을 추가할 수 있습니다.
* 작업 세부 정보 페이지에는 기본 작업을 완료하기 위해 실행 중인 모든 하위 작업이 표시됩니다.
* 이 페이지는 15분마다 자동으로 새로 고쳐져 항상 가장 최근의 작업 상태 결과를 볼 수 있습니다. 새로 고침 * 버튼을 클릭하여 페이지를 즉시 업데이트할 수 있습니다.




=== AWS 교차 계정 백업 기능이 향상되었습니다

소스 볼륨에 사용 중인 것과 다른 Cloud Volumes ONTAP 계정을 백업에 사용하려면 BlueXP에서 대상 AWS 계정 자격 증명을 추가해야 하며, BlueXP에 사용 권한을 제공하는 IAM 역할에 "S3:PutBucketPolicy" 및 "S3:PutnerOwshipControls" 권한을 추가해야 합니다. 이전에는 AWS 콘솔에서 여러 설정을 구성해야 했습니다. 이제는 더 이상 그렇게 할 필요가 없습니다.



== 2022년 9월 28일



=== 애플리케이션의 클라우드 백업 개선

* Google Cloud Platform(GCP) 및 StorageGRID를 지원하여 애플리케이션 정합성 보장 스냅샷을 백업합니다
* 사용자 지정 정책을 생성합니다
* 아카이브 스토리지 지원
* SAP HANA 애플리케이션 백업
* VMware 환경에 있는 Oracle 및 SQL 애플리케이션을 백업합니다
* 사내 2차 스토리지에서 애플리케이션을 백업합니다
* 백업을 비활성화합니다
* SnapCenter 서버 등록을 취소합니다




=== 가상 머신용 Cloud Backup의 향상된 기능

* 하나 이상의 데이터 저장소를 백업하기 위해 StorageGRID를 지원합니다
* 사용자 지정 정책을 생성합니다




== 2022년 9월 19일



=== StorageGRID 시스템의 백업 파일에 대해 DataLock 및 랜섬웨어 보호를 구성할 수 있습니다

마지막 릴리즈에서는 Amazon S3 버킷에 저장된 백업에 대해 _DataLock 및 랜섬웨어 보호_가 도입되었습니다. 이 릴리즈는 StorageGRID 시스템에 저장된 백업 파일에 대한 지원을 확장합니다. 클러스터가 ONTAP 9.11.1 이상을 사용하고 있고 StorageGRID 시스템에서 버전 11.6.0.3 이상을 실행 중인 경우 이 새로운 백업 정책 옵션을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].

버전 3.9.22 이상의 소프트웨어가 있는 커넥터를 실행해야 합니다. Connector는 구내에 설치해야 하며 인터넷에 접속하거나 접속하지 않은 사이트에 설치할 수 있습니다.



=== 이제 백업 파일에서 폴더 레벨 복구를 사용할 수 있습니다

이제 해당 폴더(디렉토리 또는 공유)의 모든 파일에 액세스해야 하는 경우 백업 파일에서 폴더를 복원할 수 있습니다. 폴더 복원은 전체 볼륨을 복원하는 것보다 훨씬 효율적입니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다. 현재 단일 폴더만 선택하고 복원할 수 있으며, 해당 폴더의 파일만 복원할 수 있습니다. 하위 폴더 또는 하위 폴더의 파일은 복원되지 않습니다.



=== 이제 아카이브 스토리지로 이동한 백업에서 파일 레벨 복구를 사용할 수 있습니다

과거에는 아카이브 스토리지(AWS 및 Azure만 해당)로 이동한 백업 파일의 볼륨만 복원할 수 있었습니다. 이제 이러한 아카이빙된 백업 파일에서 개별 파일을 복원할 수 있습니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 이제 파일 레벨 복구를 통해 원본 소스 파일을 덮어쓸 수 있습니다

이전에는 원래 볼륨으로 복구된 파일이 항상 "Restore_<file_name>"이라는 접두사가 붙은 새 파일로 복원되었습니다. 이제 파일을 볼륨의 원래 위치로 복구할 때 원본 소스 파일을 덮어쓰도록 선택할 수 있습니다. 이 기능은 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 끌어서 놓기를 통해 클라우드 백업을 StorageGRID 시스템에 사용할 수 있습니다

를 누릅니다 https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 백업 대상은 Canvas에 작업 환경으로 있으며, 온프레미스 ONTAP 작업 환경을 대상으로 끌어서 클라우드 백업 설정 마법사를 시작할 수 있습니다.



== 2022년 8월 18일



=== 클라우드 네이티브 애플리케이션 데이터를 보호하기 위해 지원이 추가되었습니다

Cloud Backup for Applications는 NetApp 클라우드 스토리지에서 실행되는 애플리케이션에 데이터 보호 기능을 제공하는 SaaS 기반 서비스입니다. BlueXP에서 활성화된 애플리케이션용 클라우드 백업은 NetApp ONTAP용 Amazon FSx에 상주하는 Oracle 데이터베이스의 효율적이고 애플리케이션 정합성이 보장되는 정책 기반 백업 및 복원을 제공합니다.https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html["자세한 정보"^].



=== 검색 및 복원은 이제 Azure Blob의 백업 파일에서 지원됩니다

이제 Azure Blob 저장소에 백업 파일을 저장하는 사용자가 볼륨 및 파일을 복원하는 검색 및 복원 방법을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["검색 및 amp;Restore를 사용하여 볼륨 및 파일을 복원하는 방법을 확인하십시오"^].

이 기능을 사용하려면 커넥터 역할에 추가 권한이 필요합니다. 버전 3.9.21 소프트웨어(2022년 8월)를 사용하여 배포된 커넥터에는 이러한 권한이 포함됩니다. 이전 릴리스를 사용하여 Connector를 배포한 경우 사용 권한을 수동으로 추가해야 합니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["필요한 경우 이러한 사용 권한을 추가하는 방법을 알아봅니다"^].



=== 백업 파일이 삭제 및 랜섬웨어 공격으로부터 보호할 수 있는 기능이 추가되었습니다

Cloud Backup은 이제 랜섬웨어 세이프 백업에 대한 오브젝트 잠금을 지원합니다. 클러스터가 ONTAP 9.11.1 이상을 사용하고 있고 백업 대상이 Amazon S3인 경우, _DataLock 및 랜섬웨어 보호_라는 새로운 백업 정책 옵션을 사용할 수 있습니다. DataLock은 백업 파일의 수정 또는 삭제를 방지하고, 랜섬웨어 방지 기능은 백업 파일을 검사하여 백업 파일에 대한 랜섬웨어 공격의 증거를 찾습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].

이 기능을 사용하려면 커넥터 역할에 추가 권한이 필요합니다. 버전 3.9.21 소프트웨어를 사용하여 배포된 Connector에는 이러한 권한이 포함되어 있습니다. 이전 릴리스를 사용하여 Connector를 배포한 경우 사용 권한을 수동으로 추가해야 합니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions["필요한 경우 이러한 사용 권한을 추가하는 방법을 알아봅니다"^].



=== 이제 Cloud Backup은 사용자 지정 SnapMirror 레이블을 사용하여 생성된 정책을 지원합니다

이전에는 Cloud Backup이 매시간, 매일, 매주, 시간별, 연도별 등의 미리 정의된 SnapMirror 레이블만 지원했습니다. 이제 Cloud Backup은 System Manager 또는 CLI를 사용하여 만든 사용자 지정 SnapMirror 레이블이 있는 SnapMirror 정책을 검색할 수 있습니다. 이러한 새 레이블은 Cloud Backup UI에 표시되므로 선택한 SnapMirror 레이블을 사용하여 볼륨을 클라우드에 백업할 수 있습니다.



=== ONTAP 시스템에 대한 추가 백업 정책 개선 사항

일부 백업 정책 페이지는 각 ONTAP 클러스터의 볼륨에 사용할 수 있는 모든 백업 정책을 보다 쉽게 볼 수 있도록 재설계되었습니다. 따라서 사용 가능한 정책의 세부 정보를 더 쉽게 볼 수 있으므로 볼륨에 최상의 정책을 적용할 수 있습니다.



=== 끌어서 놓기를 통해 Cloud Backup을 Azure Blob 및 Google Cloud Storage로 이동할 수 있습니다

를 누릅니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html["Azure Blob"^] 또는 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html["Google 클라우드 스토리지"^] 백업 대상이 Canvas에 작업 환경으로 존재합니다. 온프레미스 ONTAP 또는 Cloud Volumes ONTAP 작업 환경(Azure 또는 GCP에 설치됨)을 대상으로 끌어서 백업 설정 마법사를 시작할 수 있습니다.

이 기능은 Amazon S3 버킷에 이미 존재합니다.



== 2022년 7월 13일



=== SnapLock 엔터프라이즈 볼륨을 백업하는 데 지원이 추가되었습니다

이제 클라우드 백업을 사용하여 SnapLock 엔터프라이즈 볼륨을 퍼블릭 및 프라이빗 클라우드에 백업할 수 있습니다. 이 기능을 사용하려면 ONTAP 시스템에서 ONTAP 9.11.1 이상을 실행해야 합니다. 그러나 SnapLock Compliance 볼륨은 현재 지원되지 않습니다.



=== 이제 온-프레미스 Connector를 사용할 때 퍼블릭 클라우드에서 백업 파일을 만들 수 있습니다

이전에는 백업 파일을 생성하던 위치와 동일한 클라우드 공급자에 Connector를 구축해야 했습니다. 이제 사내에 구축된 Connector를 사용하여 온프레미스 ONTAP 시스템에서 Amazon S3, Azure Blob 및 Google Cloud Storage로 백업 파일을 생성할 수 있습니다. (StorageGRID 시스템에서 백업 파일을 생성할 때는 항상 내부 커넥터가 필요했습니다.)



=== ONTAP 시스템에 대한 백업 정책을 생성할 때 추가 기능을 사용할 수 있습니다

* 이제 연간 일정에 대한 백업을 사용할 수 있습니다. 기본 보존 값은 연간 백업의 경우 1이지만 이전 해 백업 파일을 여러 개 액세스하려는 경우 이 값을 변경할 수 있습니다.
* 백업 정책의 이름을 지정하여 보다 자세한 설명이 포함된 텍스트를 사용하여 정책을 식별할 수 있습니다.




== 2022년 6월 14일



=== 인터넷에 연결되지 않은 사이트에서 사내 ONTAP 클러스터 데이터를 백업하는 데 지원이 추가되었습니다

사내 ONTAP 클러스터가 인터넷 액세스가 연결되지 않은 사이트에 있는 경우, 다크 사이트 또는 오프라인 사이트라고도 합니다. 이제 Cloud Backup을 사용하여 볼륨 데이터를 동일한 사이트에 있는 NetApp StorageGRID 시스템에 백업할 수 있습니다. 이 기능을 사용하려면 BlueXP 커넥터(버전 3.9.19 이상)도 오프라인 사이트에 배포해야 합니다.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["오프라인 사이트에 커넥터를 설치하는 방법을 알아봅니다"].https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html["오프라인 사이트에서 ONTAP 데이터를 StorageGRID에 백업하는 방법을 알아봅니다"].



=== Cloud Backup for Virtual Machines 1.1.0이 현재 GA로 제공됩니다

VMware vSphere용 SnapCenter 플러그인을 BlueXP와 통합하여 가상 시스템의 데이터를 보호할 수 있습니다. 데이터 저장소를 클라우드에 백업하고 VMware vSphere용 사내 SnapCenter 플러그인으로 가상 머신을 간편하게 복원할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html["가상 시스템을 클라우드로 보호하는 방법에 대해 자세히 알아보십시오"].



=== ONTAP 찾아보기 및 복원 기능에는 클라우드 복원 인스턴스가 필요하지 않습니다

S3 및 Blob 스토리지에서 파일 레벨 찾아보기 및 복원 작업에 사용되는 별도의 클라우드 복원 인스턴스/가상 머신. 이 인스턴스는 사용하지 않을 때 종료되지만 파일을 복원할 때 약간의 시간과 비용이 추가되었습니다. 이 기능은 필요 시 Connector에 배포되는 무료 컨테이너로 대체되었습니다. 다음과 같은 이점을 제공합니다.

* 파일 레벨 복구 작업에 대한 추가 비용 없음
* 파일 레벨 복구 작업 속도 향상
* Connector가 사내에 설치된 경우 클라우드에서 파일에 대한 찾아보기 및 복원 작업 지원


이전에 클라우드 복원 인스턴스/VM을 사용한 경우 자동으로 제거됩니다. Cloud Backup 프로세스는 모든 이전 Cloud Restore 인스턴스를 삭제하기 위해 하루에 한 번 실행됩니다. 이 변경 사항은 완전히 투명하게 나타납니다. 데이터에는 영향을 주지 않으며 백업 또는 복원 작업이 변경되지 않습니다.



=== Google Cloud 및 StorageGRID 스토리지에서 파일에 대한 찾아보기 및 복원 지원

위에서 설명한 대로 Browse & Restore 작업에 대한 컨테이너가 추가되어 Google Cloud 및 StorageGRID 시스템에 저장된 백업 파일에서 파일 복원 작업을 수행할 수 있습니다. 이제 Browse & Restore를 사용하여 모든 퍼블릭 클라우드 공급자 및 StorageGRID에서 파일을 복원할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["ONTAP 백업에서 볼륨 및 파일을 복원하기 위해 Browse  amp; Restore를 사용하는 방법을 확인하십시오"].



=== 끌어서 놓기를 통해 Cloud Backup을 S3 스토리지로 설정합니다

백업에 대한 Amazon S3 대상이 Canvas의 작업 환경으로 존재하는 경우, 온프레미스 ONTAP 클러스터 또는 Cloud Volumes ONTAP 시스템(AWS에 설치됨)을 Amazon S3 작업 환경으로 끌어서 설정 마법사를 시작할 수 있습니다.



=== Kubernetes 클러스터에서 새로 생성된 볼륨에 백업 정책을 자동으로 적용합니다

Cloud Backup을 활성화한 후 Kubernetes 클러스터에 새로운 영구 볼륨을 추가한 경우에는 이전에 해당 볼륨에 대한 백업을 구성해야 했습니다. 이제 새로 생성된 볼륨에 자동으로 적용되는 정책을 선택할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["백업 설정 페이지에서"] 이미 Cloud Backup을 활성화한 클러스터의 경우



=== 이제 Cloud Backup API를 사용하여 백업 및 복원 작업을 관리할 수 있습니다

API는 에서 사용할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html[]. 을 참조하십시오 link:api-backup-restore.html["이 페이지"] API에 대한 개요입니다.



== 2022년 5월 2일



=== 검색 및 복원은 이제 Google Cloud Storage의 백업 파일에서 지원됩니다

4월에 AWS에 백업 파일을 저장한 사용자를 위해 볼륨 및 파일 복원 검색 및 복원 방법이 도입되었습니다. 이제 Google Cloud Storage에 백업 파일을 저장하는 사용자가 이 기능을 사용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["검색 및 amp;Restore를 사용하여 볼륨 및 파일을 복원하는 방법을 확인하십시오"].



=== Kubernetes 클러스터에서 새로 생성된 볼륨에 자동으로 적용할 백업 정책을 구성합니다

Cloud Backup을 활성화한 후 Kubernetes 클러스터에 새로운 영구 볼륨을 추가한 경우에는 이전에 해당 볼륨에 대한 백업을 구성해야 했습니다. 이제 새로 생성된 볼륨에 자동으로 적용되는 정책을 선택할 수 있습니다. 이 옵션은 새 Kubernetes 클러스터에 대한 Cloud Backup을 활성화할 때 설정 마법사에서 사용할 수 있습니다.



=== 이제 작업 환경에서 Cloud Backup을 활성화하려면 라이센스가 필요합니다

Cloud Backup에서 라이센스를 구축하는 방법은 다음과 같이 몇 가지 변경되었습니다.

* Cloud Backup을 활성화하려면 먼저 클라우드 공급자로부터 PAYGO Marketplace 구독에 가입하거나 NetApp에서 BYOL 라이센스를 구입해야 합니다.
* 30일 무료 평가판은 클라우드 공급자가 PAYGO 구독을 사용하는 경우에만 사용할 수 있으며 BYOL 라이센스를 사용하는 경우에는 사용할 수 없습니다.
* 무료 평가판은 마켓플레이스 가입이 시작되는 날부터 시작됩니다. 예를 들어, Cloud Volumes ONTAP 시스템에 대해 30일 동안 Marketplace 구독을 사용한 후 무료 평가판을 활성화하면 클라우드 백업 평가판을 사용할 수 없습니다.


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html["사용 가능한 라이센스 모델에 대해 자세히 알아보십시오"].



== 2022년 4월 4일



=== SnapCenter에 기반을 둔 애플리케이션 클라우드 백업 1.1.0 이 현재 GA입니다

새로운 Cloud Backup for Applications 기능을 사용하면 Oracle 및 Microsoft SQL에 대한 기존 애플리케이션 정합성 보장 스냅샷(백업)을 사내 운영 스토리지에서 Amazon S3 또는 Azure Blob의 클라우드 오브젝트 스토리지로 오프로드할 수 있습니다.

필요한 경우 클라우드에서 사내로 데이터를 복원할 수 있습니다.

link:concept-protect-app-data-to-cloud.html["사내 애플리케이션 데이터를 클라우드로 보호하는 방법에 대해 자세히 알아보십시오"].



=== 모든 ONTAP 백업 파일에서 볼륨 또는 파일을 검색하는 새로운 검색 및 복원 기능

이제 일부 또는 전체 볼륨 이름, 일부 또는 전체 파일 이름, 크기 범위 및 추가 검색 필터를 통해 * 모든 ONTAP 백업 파일 * 에서 볼륨 또는 파일을 검색할 수 있습니다. 이 방법은 어떤 클러스터나 볼륨이 데이터의 소스인지 잘 모르면 복원하려는 데이터를 찾을 수 있는 새로운 방법입니다. link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["검색 및 amp;Restore 사용 방법에 대해 알아봅니다"].



== 2022년 3월 3일



=== GKE Kubernetes 클러스터에서 Google Cloud 스토리지로 영구 볼륨을 백업하는 기능

GKE 클러스터에 NetApp Astra Trident가 설치되어 있고 Cloud Volumes ONTAP for GCP를 클러스터의 백엔드 스토리지로 사용하는 경우, Google Cloud 스토리지와 영구 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-gcp.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== Cloud Data Sense를 사용하여 Cloud Backup 파일을 검사하는 베타 기능은 이 릴리즈에서 더 이상 제공되지 않습니다



== 2022년 2월 14일



=== 이제 단일 클러스터의 개별 볼륨에 백업 정책을 할당할 수 있습니다

과거에는 클러스터의 모든 볼륨에 단일 백업 정책만 할당할 수 있었습니다. 이제 단일 클러스터에 대해 여러 백업 정책을 생성하고 여러 볼륨에 서로 다른 정책을 적용할 수 있습니다. link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["클러스터에 대한 새 백업 정책을 생성하고 이를 선택한 볼륨에 할당하는 방법을 알아보십시오"].



=== 새 옵션을 사용하면 새로 생성된 볼륨에 기본 백업 정책을 자동으로 적용할 수 있습니다

과거에는 Cloud Backup을 활성화한 후 작업 환경에서 생성된 새 볼륨을 수동으로 백업 정책을 적용해야 했습니다. 이제 볼륨이 BlueXP, System Manager, CLI 또는 API에서 생성되었는지에 관계없이 Cloud Backup은 볼륨을 검색하고 기본 정책으로 선택한 백업 정책을 적용합니다.

이 옵션은 새 작업 환경에서 백업을 설정하거나 기존 작업 환경의 _Manage Volumes_페이지에서 백업을 설정할 때 사용할 수 있습니다.



=== 새 작업 모니터를 사용하여 모든 백업 및 복원 작업의 진행 상태를 확인할 수 있습니다

백업 정책 변경 또는 백업 삭제와 같이 여러 볼륨에 대해 작업을 시작한 경우 작업 모니터를 사용하면 모든 볼륨에서 작업이 완료된 시점을 확인할 수 있습니다. link:task-monitor-backup-jobs.html["작업 모니터 사용 방법을 참조하십시오"].
