---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: BlueXP 백업 및 복구의 새로운 기능에 대해 알아보십시오. 
---
= BlueXP 백업 및 복구의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 백업 및 복구의 새로운 기능에 대해 알아보십시오.



== 2025년 4월 16일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



=== UI 개선

이 릴리스는 인터페이스를 단순화함으로써 사용자 경험을 향상시킵니다.

* 볼륨 테이블에서 애그리게이트 열을 제거하고 V2 대시보드의 볼륨 테이블에서 스냅샷 정책, 백업 정책 및 복제 정책 열을 제거하면 레이아웃이 보다 간소화됩니다.
* 드롭다운 목록에서 활성화되지 않은 작업 환경을 제외하면 인터페이스가 덜 복잡해지고 탐색이 더 효율적으로 수행되며 로딩 속도가 빨라집니다.
* 태그 열에서 정렬을 사용할 수 없지만 중요한 정보에 쉽게 액세스할 수 있도록 태그를 계속 볼 수 있습니다.
* 보호 아이콘의 라벨을 제거하면 더 깔끔한 외관을 연출하고 로딩 시간을 줄일 수 있습니다.
* 작업 환경 활성화 프로세스 중에 대화 상자에 로드 아이콘이 표시되어 검색 프로세스가 완료될 때까지 피드백을 제공하여 시스템 운영에 대한 투명성과 신뢰도를 높입니다.




=== 향상된 볼륨 대시보드(미리 보기)

이제 볼륨 대시보드가 10초 이내에 로드되므로 훨씬 빠르고 효율적인 인터페이스를 제공합니다. 이 Preview 버전은 일부 고객에게 제공되며 이러한 개선 사항을 조기에 확인할 수 있습니다.



=== 타사 Wasabi 개체 저장소 지원(Preview)

BlueXP  백업 및 복구는 이제 Wasabi에 중점을 두고 타사 오브젝트 스토어까지 지원을 확장하고 있습니다. 이 새로운 미리 보기 기능을 사용하면 백업 및 복구 요구에 S3 호환 오브젝트 저장소를 활용할 수 있습니다.



==== Wasabi 시작하기

타사 스토리지를 개체 저장소로 사용하려면 BlueXP  커넥터 내에서 플래그를 설정해야 합니다. 그런 다음 타사 오브젝트 저장소에 대한 연결 정보를 입력하고 백업 및 복구 워크플로에 통합할 수 있습니다.

.단계
. SSH를 사용하여 커넥터에 연결합니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너로 이동합니다.
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. VIM 또는 다른 편집기를 통해 폴더 내에서 파일을 `config` 엽니다 `default.json`.
+
[listing]
----
vi default.json
----
. modify `allow-s3-compatible`:false to:true로 `allow-s3-compatible` 변경합니다.
. 변경 사항을 저장합니다.
. 컨테이너에서 나갑니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너를 다시 시작합니다.


.결과
컨테이너가 다시 켜지면 BlueXP  백업 및 복구 UI를 엽니다. 백업을 시작하거나 백업 전략을 편집하면 AWS, Microsoft Azure, Google Cloud, StorageGRID 및 ONTAP S3의 다른 백업 공급자와 함께 새로운 공급업체 "S3 호환"이 표시됩니다.



==== 미리보기 모드 제한

이 기능이 미리 보기에 있는 동안 다음 제한 사항을 고려하십시오.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 사용하도록 설정할 수 없습니다.
* 정책에서 아카이브 모드를 사용하도록 설정하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster는 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


이 미리 보기를 진행하는 동안 이 새로운 기능을 살펴보고 전체 기능이 배포되기 전에 타사 개체 저장소와의 통합에 대한 피드백을 제공하는 것이 좋습니다.



== 2025년 3월 17일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



=== SMB 스냅샷 탐색

이 BlueXP  백업 및 복구 업데이트는 고객이 SMB 환경에서 로컬 스냅샷을 찾을 수 없는 문제를 해결했습니다.



=== AWS GovCloud 환경 업데이트

이 BlueXP  백업 및 복구 업데이트는 TLS 인증서 오류로 인해 UI가 AWS GovCloud 환경에 연결되지 않는 문제를 해결했습니다. IP 주소 대신 BlueXP  커넥터 호스트 이름을 사용하여 문제를 해결했습니다.



=== 백업 정책 보존 제한

이전에는 BlueXP  백업 및 복구 UI에서 백업을 999개로 제한했지만 CLI에서는 백업을 더 허용했습니다. 이제 최대 4,000개의 볼륨을 백업 정책에 연결할 수 있으며 백업 정책에 연결되지 않은 1,018개의 볼륨을 포함할 수 있습니다. 이 업데이트에는 이러한 제한을 초과하지 않는 추가 유효성 검사가 포함되어 있습니다.



=== SnapMirror Cloud 재동기화

이 업데이트는 SnapMirror 관계가 삭제된 후에 지원되지 않는 ONTAP 버전에 대한 BlueXP  백업 및 복구에서 SnapMirror Cloud 재동기화를 시작할 수 없도록 합니다.



== 2025년 2월 21일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



=== 고성능 인덱싱

BlueXP  백업 및 복구에는 소스 작업 환경에서 데이터를 보다 효율적으로 인덱싱할 수 있는 업데이트된 인덱싱 기능이 도입되었습니다. 새로운 인덱싱 기능에는 UI 업데이트, 데이터 복원 검색 및 복원 방법의 향상된 성능, 글로벌 검색 기능으로 업그레이드 및 향상된 확장성 등이 포함됩니다.

개선된 사항은 다음과 같습니다.

* * 폴더 통합 *: 업데이트된 버전은 특정 식별자가 포함된 이름을 사용하여 폴더를 그룹화하여 인덱싱 프로세스를 원활하게 합니다.
* * Parquet 파일 압축 *: 업데이트된 버전은 각 볼륨을 인덱싱하는 데 사용되는 파일 수를 줄여 프로세스를 단순화하고 추가 데이터베이스가 필요하지 않습니다.
* * 더 많은 세션으로 스케일 아웃 *: 새로운 버전은 인덱싱 작업을 처리하기 위해 더 많은 세션을 추가하여 프로세스 속도를 높입니다.
* * 다중 인덱스 컨테이너 지원 * : 새 버전은 인덱싱 작업을 더 잘 관리하고 배포하기 위해 여러 컨테이너를 사용합니다.
* * 분할 색인 워크플로 * : 새 버전은 인덱싱 프로세스를 두 부분으로 분할하여 효율성을 향상시킵니다.
* * 향상된 동시성 * : 새로운 버전을 사용하면 동시에 디렉토리를 삭제하거나 이동할 수 있으므로 인덱싱 프로세스가 빨라집니다.


.이 기능의 이점은 누구입니까?
새로운 인덱싱 기능은 모든 신규 고객이 사용할 수 있습니다.

.인덱싱을 활성화하려면 어떻게 해야 합니까?
데이터를 복원하는 검색 및 복원 방법을 사용하려면 먼저 볼륨 또는 파일을 복원하려는 각 소스 작업 환경에서 "인덱싱"을 활성화해야 합니다. 따라서 인덱스화된 카탈로그가 모든 볼륨과 모든 백업 파일을 추적할 수 있어 빠르고 효율적으로 검색할 수 있습니다.

검색 및 복원을 수행할 때 "인덱싱 사용" 옵션을 선택하여 소스 작업 환경에서 인덱싱을 활성화합니다.

자세한 내용은 설명서를 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["검색 및 복원 을 사용하여 ONTAP 데이터를 복원하는 방법"]참조하십시오.

.지원되는 배율
새 인덱싱 기능은 다음을 지원합니다.

* 3분 이내에 글로벌 검색 효율성 향상
* 최대 50억 개의 파일
* 클러스터당 최대 5000개의 볼륨
* 볼륨당 최대 100,000개의 스냅샷 지원
* 기준 색인에 대한 최대 시간은 7일 미만입니다. 실제 시간은 환경에 따라 다릅니다.




=== 글로벌 검색 성능 향상

이번 릴리스에는 글로벌 검색 성능 향상도 포함되어 있습니다. 이제 진행률 표시기 및 파일 수와 검색에 걸리는 시간을 포함하여 보다 자세한 검색 결과가 표시됩니다. 검색 및 색인화를 위한 전용 컨테이너를 통해 5분 이내에 글로벌 검색이 완료됩니다.

글로벌 검색과 관련된 고려 사항은 다음과 같습니다.

* 새 인덱스는 시간별 스냅샷으로 레이블이 지정된 스냅샷에 대해 수행되지 않습니다.
* 새로운 인덱싱 기능은 FlexVol의 스냅샷에만 작동하며, FlexGroups의 스냅샷에는 작동하지 않습니다.




== 2024년 11월 22일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



=== SnapLock Compliance 및 SnapLock Enterprise 보호 모드

BlueXP  백업 및 복구 기능은 이제 SnapLock Compliance 또는 SnapLock Enterprise 보호 모드를 사용하여 구성된 FlexVol 및 FlexGroup 온프레미스 볼륨을 모두 백업할 수 있습니다. 클러스터에서 ONTAP 9.14 이상을 실행해야 합니다. SnapLock 엔터프라이즈 모드를 사용한 FlexVol 볼륨 백업은 ONTAP 버전 9.11.1 이후로 지원됩니다. 이전 ONTAP 릴리즈에서는 SnapLock 보호 볼륨의 백업을 지원하지 않습니다.

에서 지원되는 볼륨의 전체 목록을 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["BlueXP 백업 및 복구에 대해 알아보십시오"] 참조하십시오.



=== 볼륨 페이지에서 검색 및 복원 프로세스를 위한 인덱싱

검색 및 복원을 사용하려면 볼륨 데이터를 복원할 각 소스 작업 환경에서 "인덱싱"을 활성화해야 합니다. 따라서 인덱스화된 카탈로그에서 모든 볼륨의 백업 파일을 추적할 수 있습니다. 이제 볼륨 페이지에 인덱싱 상태가 표시됩니다.

* 인덱싱됨: 볼륨이 인덱싱되었습니다.
* 진행 중
* 인덱싱되지 않았습니다
* 인덱싱이 일시 중지되었습니다
* 오류
* 활성화되지 않음




== 2024년 9월 27일

이 BlueXP  백업 및 복구 릴리스에는 다음 업데이트가 포함되어 있습니다.



=== Browse and Restore를 사용하여 RHEL 8 또는 9에서 Podman을 지원합니다

이제 BlueXP  백업 및 복구는 Podman 엔진을 사용하여 RHEL(Red Hat Enterprise Linux) 버전 8 및 9에서 파일 및 폴더 복원을 지원합니다. 이는 BlueXP  백업 및 복구 찾아보기 및 복원 방법에 적용됩니다.

BlueXP  커넥터 버전 3.9.40은 에 언급된 운영 체제 외에 위치에 관계없이 RHEL 8 또는 9 호스트에 커넥터 소프트웨어를 수동으로 설치할 수 있도록 특정 버전의 Red Hat Enterprise Linux 버전 8 및 9를 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["호스트 요구 사항"^] 지원합니다. 이러한 최신 RHEL 버전에는 Docker 엔진 대신 Podman 엔진이 필요합니다. 이전에는 BlueXP  백업 및 복구에 Podman 엔진을 사용할 때 두 가지 제한 사항이 있었습니다. 이러한 제한 사항은 제거되었습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["백업 파일에서 ONTAP 데이터를 복원하는 방법에 대해 자세히 알아보십시오"]..



=== 빠른 카탈로그 인덱싱으로 검색 및 복원 향상

이 릴리스에는 기본 인덱싱을 훨씬 빠르게 완료할 수 있는 향상된 카탈로그 인덱스가 포함되어 있습니다. 인덱싱 속도가 빨라지면 검색 및 복원 기능을 보다 빠르게 사용할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["백업 파일에서 ONTAP 데이터를 복원하는 방법에 대해 자세히 알아보십시오"]..



== 2024년 7월 22일



=== 1GB 미만의 볼륨을 복원합니다

이 릴리스에서는 이제 ONTAP에서 만든 1GB 미만의 볼륨을 복원할 수 있습니다. ONTAP를 사용하여 만들 수 있는 최소 볼륨 크기는 20MB입니다.



=== DataLock 비용을 줄이는 방법에 대한 팁

DataLock 기능은 지정된 기간 동안 백업 파일이 수정되거나 삭제되지 않도록 보호합니다. 이 기능은 랜섬웨어 공격으로부터 파일을 보호하는 데 도움이 됩니다.

DataLock에 대한 자세한 내용과 관련 비용을 줄이는 방법에 대한 팁은 을 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["오브젝트에 백업 정책 설정"]참조하십시오.



=== AWS IAM 역할 어디서나 통합

AWS(Amazon Web Services) ID 및 액세스 관리(IAM) 역할 Anywhere 서비스를 사용하면 AWS의 words_outside_of AWS에 대한 IAM 역할 및 단기 자격 증명을 사용하여 AWS API에 안전하게 액세스할 수 있으며, 이때 words_on_AWS에 IAM 역할을 사용하는 것과 같은 방법으로 AWS API에 안전하게 액세스할 수 있습니다. 어디서나 개인 키 인프라 및 AWS 토큰을 사용할 경우 장기 AWS 액세스 키와 비밀 키가 필요하지 않습니다. 이렇게 하면 자격 증명을 더 자주 순환할 수 있으므로 보안이 향상됩니다.

이 릴리스에서 AWS IAM 역할 Anywhere 서비스에 대한 지원은 기술 미리 보기입니다.

을 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP 백업 및 복구 2024년 7월 릴리즈 블로그"]참조하십시오.



=== 이제 FlexGroup 폴더 또는 디렉토리 복원을 사용할 수 있습니다

이전에는 FlexVol 볼륨을 복원할 수 있었지만 FlexGroup 폴더 또는 디렉토리를 복원할 수 없었습니다. ONTAP 9.15.1 P2에서는 찾아보기 및 복원 옵션을 사용하여 FlexGroup 폴더를 복원할 수 있습니다.

이 릴리스에서 FlexGroup 폴더 복원에 대한 지원은 기술 미리 보기입니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["찾아보기 및 amp; 복원을 사용하여 폴더와 파일을 복원합니다"]참조하십시오.

수동으로 활성화하는 방법에 대한 자세한 내용은 을 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP 백업 및 복구 2024년 7월 릴리즈 블로그"]참조하십시오.



== 2024년 5월 17일



=== 온프레미스 커넥터에 RHEL 8 및 RHEL 9를 사용할 때의 제한 사항

BlueXP Connector 버전 3.9.40은 에 언급된 운영 체제 및 위치와 관계없이 RHEL 8 또는 9 호스트에 Connector 소프트웨어를 수동으로 설치하는 데 특정 버전의 Red Hat Enterprise Linux 버전 8 및 9를 지원합니다 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["호스트 요구 사항"^]. 이러한 최신 RHEL 버전에는 Docker 엔진 대신 Podman 엔진이 필요합니다. 현재 BlueXP 백업 및 복구에는 Podman 엔진을 사용할 때 두 가지 제한 사항이 있습니다.

을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["백업 및 복원 제한 사항"] 를 참조하십시오.

다음 절차에는 새로운 Podman 지침이 포함되어 있습니다.

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["BlueXP 백업 및 복구를 다시 시작합니다"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["어두운 사이트에서 BlueXP 백업 및 복구 데이터를 복원합니다"]




== 2024년 4월 30일



=== 예약된 랜섬웨어 검사를 활성화 또는 비활성화합니다

이전에는 랜섬웨어 검사를 활성화 또는 비활성화할 수 있었지만 예약된 검사에 대해서는 그렇게 할 수 없었습니다.

이 릴리즈에서는 이제 고급 설정 페이지의 옵션을 사용하여 최신 스냅샷 복사본에 대해 예약된 랜섬웨어 검사를 사용하거나 사용하지 않도록 설정할 수 있습니다. 이 기능을 활성화하면 기본적으로 스캔이 매주 수행됩니다. 이 일정을 일 또는 주로 변경하거나 사용하지 않도록 설정하여 비용을 절감할 수 있습니다.

자세한 내용은 다음 정보를 참조하십시오.

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["백업 설정을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ONTAP 볼륨에 대한 정책을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["오브젝트에 백업 정책 설정"]




== 2024년 4월 4일



=== 랜섬웨어 검사를 활성화 또는 비활성화할 수 있습니다

이전에는 백업 정책에서 랜섬웨어 탐지를 활성화했을 때 첫 번째 백업이 생성될 때 그리고 백업을 복원할 때 검사가 자동으로 수행되었습니다. 이전에는 이 서비스에서 스냅샷 복사본을 모두 스캔했지만 사용자가 검사를 비활성화할 수 없었습니다.

이 릴리즈에서 고급 설정 페이지의 옵션을 사용하여 최신 스냅샷 복사본에 대한 랜섬웨어 검사를 사용하거나 사용하지 않도록 설정할 수 있습니다. 이 기능을 활성화하면 기본적으로 스캔이 매주 수행됩니다.

자세한 내용은 다음 정보를 참조하십시오.

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["백업 설정을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ONTAP 볼륨에 대한 정책을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["오브젝트에 백업 정책 설정"]


ifdef::aws[]

 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Cloud Volumes ONTAP 데이터를 Amazon S3에 백업"]및 을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Azure Blob에 Cloud Volumes ONTAP 데이터 백업"]참조하십시오.

endif::aws[]



== 2024년 3월 12일



=== 클라우드 백업에서 사내 ONTAP 볼륨으로 "빠른 복원"을 수행할 수 있습니다

이제 클라우드 스토리지에서 온프레미스 ONTAP 타겟 볼륨으로 _ 빠른 복원 _ 을(를) 수행할 수 있습니다. 이전에는 Cloud Volumes ONTAP 시스템에만 빠른 복원을 수행할 수 있었습니다. 빠른 복원은 가능한 한 빨리 볼륨에 대한 액세스를 제공해야 하는 재해 복구 상황에 이상적입니다. 빠른 복원은 전체 볼륨 복원보다 훨씬 빠르며 클라우드 스냅샷에서 ONTAP 타겟 볼륨으로 메타데이터를 복원합니다. 소스는 AWS S3, Azure Blob, Google Cloud Services 또는 NetApp StorageGRID에서 가져올 수 있습니다.

온프레미스 ONTAP 대상 시스템에서 ONTAP 버전 9.14.1 이상을 실행해야 합니다.

검색 및 복원 프로세스가 아닌 찾아보기 및 복원 프로세스를 사용하여 이 작업을 수행할 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["백업 파일에서 ONTAP 데이터를 복원합니다"].



=== 스냅샷 및 복제 복제본에서 파일 및 폴더를 복구하는 기능

이전에는 AWS, Azure 및 Google Cloud Services의 백업 사본에서만 파일과 폴더를 복원할 수 있었습니다. 이제 로컬 스냅샷 복사본 및 복제 복사본에서 파일과 폴더를 복원할 수 있습니다.

이 기능은 찾아보기 및 복원 프로세스를 사용하는 것이 아니라 검색 및 복원 프로세스를 사용하여 수행할 수 있습니다.



== 2024년 2월 1일



=== 가상 머신을 위한 BlueXP 백업 및 복구 기능 개선

* 가상 시스템을 대체 위치로 복구하는 기능을 지원합니다
* 데이터 저장소 보호 해제 지원




== 2023년 12월 15일



=== 로컬 스냅샷 및 복제 스냅샷 복사본에 대해 보고서 사용 가능

이전에는 백업 사본에 대한 보고서만 생성할 수 있었습니다. 이제 로컬 스냅샷 복사본과 복제 스냅샷 복사본에 대한 보고서를 생성할 수 있습니다.

이러한 보고서를 사용하여 다음을 수행할 수 있습니다.

* 조직 정책에 따라 중요 데이터를 보호합니다.
* 볼륨 그룹에 대한 백업이 원활하게 실행되는지 확인합니다.
* 운영 데이터에 대한 보호 증명을 제공합니다.


을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["데이터 보호 범위에 대한 보고"].



=== 정렬 및 필터링에 사용할 수 있는 사용자 지정 태그 지정

이제 ONTAP 9.13.1부터 시작하는 볼륨에 사용자 지정 태그를 추가하여 작업 환경 내부와 다른 작업 환경에서 볼륨을 함께 그룹화할 수 있습니다. 이렇게 하면 BlueXP 백업 및 복구 UI 페이지에서 볼륨을 정렬하고 보고서에서 필터링할 수 있습니다.



=== 카탈로그 백업을 30일 동안 보존합니다

이전에는 Catalog.zip 백업이 7일 동안 보존되었습니다. 지금은 30일 동안 보관됩니다.

을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["다크 사이트에서 BlueXP 백업 및 복구 데이터를 복원합니다"].



== 2023년 10월 23일



=== 백업 활성화 중 3-2-1 백업 정책 생성

이전에는 스냅샷, 복제 또는 백업을 시작하기 전에 사용자 지정 정책을 생성해야 했습니다. 이제 백업 활성화 프로세스 중에 BlueXP 백업 및 복구 UI를 사용하여 정책을 생성할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["정책에 대해 자세히 알아보십시오"].



=== ONTAP 볼륨의 온디맨드 빠른 복원 지원

BlueXP 백업 및 복구를 통해 클라우드 스토리지에서 Cloud Volumes ONTAP 시스템으로 볼륨을 "빠르게 복원"할 수 있습니다. 빠른 복원은 가능한 한 빨리 볼륨에 대한 액세스를 제공해야 하는 재해 복구 상황에 이상적입니다. 빠른 복원은 전체 백업 파일을 복원하는 대신 백업 파일의 메타데이터를 볼륨으로 복원합니다.

Cloud Volumes ONTAP 대상 시스템에서 ONTAP 버전 9.13.0 이상을 실행해야 합니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["데이터 복원에 대해 자세히 알아보십시오"].

BlueXP 백업 및 복구 작업 모니터에는 빠른 복원 작업의 진행률에 대한 정보도 표시됩니다.



=== 작업 모니터에서 예약된 작업을 지원합니다

BlueXP 백업 및 복구 작업 모니터는 이전에 모니터링된 예약된 볼륨-오브젝트 저장소 백업 및 복원 작업이지만 UI 또는 API를 통해 예약된 로컬 스냅샷, 복제, 백업 및 복원 작업은 모니터링하지 않습니다.

이제 BlueXP 백업 및 복구 작업 모니터에 로컬 스냅샷, 복제 및 오브젝트 스토리지로의 백업에 대해 예약된 작업이 포함됩니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["업데이트된 작업 모니터에 대해 자세히 알아보십시오"].



== 2023년 10월 13일



=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(클라우드 네이티브)

* Microsoft SQL Server 데이터베이스
+
** 에서는 Amazon FSx for NetApp ONTAP에 상주하는 Microsoft SQL Server 데이터베이스의 백업, 복원, 복구를 지원합니다
** 모든 작업은 REST API를 통해서만 지원됩니다.


* SAP HANA 시스템
+
** 시스템 새로 고침 중에 볼륨의 자동 마운트 및 마운트 해제는 스크립트 대신 워크플로우를 사용하여 수행됩니다
** 추가, 제거, 편집, 삭제, 유지 관리, UI를 사용하여 플러그인 호스트를 업그레이드합니다






=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(하이브리드)

* 데이터 잠금 및 랜섬웨어 보호를 지원합니다
* StorageGRID에서 아카이브 계층으로 백업을 이동할 수 있습니다
* 온프레미스 ONTAP 시스템에서 Amazon Web Services, Microsoft Azure, Google Cloud Platform 및 StorageGRID로의 MongoDB, MySQL 및 PostgreSQL 애플리케이션 데이터 백업을 지원합니다. 필요할 때 데이터를 복원할 수 있습니다.




=== 가상 머신을 위한 BlueXP 백업 및 복구 기능 개선

* 커넥터 프록시 구축 모델 지원




== 2023년 9월 11일



=== ONTAP 데이터에 대한 새로운 정책 관리

이 릴리즈에는 ONTAP 데이터용 오브젝트 스토리지에 백업하기 위한 사용자 지정 스냅샷 정책, 복제 정책 및 정책을 생성하는 기능이 포함되어 있습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["정책에 대해 자세히 알아보십시오"].



=== ONTAP S3 오브젝트 스토리지의 볼륨에서 파일 및 폴더 복원 지원

이전에는 볼륨을 ONTAP S3 오브젝트 스토리지에 백업할 때 "찾아보기 및 복원" 기능을 사용하여 파일과 폴더를 복원할 수 없었습니다. 이 릴리스에서는 이러한 제한이 제거됩니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["데이터 복원에 대해 자세히 알아보십시오"].



=== 백업 데이터를 표준 스토리지에 처음 쓰는 대신 즉시 아카이빙할 수 있습니다

이제 데이터를 표준 클라우드 스토리지에 기록하는 대신 백업 파일을 즉시 아카이브 스토리지로 보낼 수 있습니다. 이 기능은 클라우드 백업에서 데이터에 액세스할 필요가 거의 없는 사용자나 테이프 환경으로 백업을 교체하는 사용자에게 특히 유용합니다.



=== SnapLock 볼륨의 백업 및 복원을 위한 추가 지원

백업 및 복구 이제 SnapLock Enterprise 보호 모드를 사용하여 구성된 FlexVol 및 FlexGroup 볼륨을 모두 백업할 수 있습니다. 클러스터에서 ONTAP 9.14 이상을 실행해야 합니다. SnapLock 엔터프라이즈 모드를 사용한 FlexVol 볼륨 백업은 ONTAP 버전 9.11.1 이후로 지원됩니다. 이전 ONTAP 릴리즈에서는 SnapLock 보호 볼륨의 백업을 지원하지 않습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAP 데이터 보호에 대해 자세히 알아보십시오"].



== 2023년 8월 1일

[IMPORTANT]
====
* 중요한 보안 개선 사항으로 인해 이제 Connector는 공용 클라우드 환경 내에서 백업 및 복구 리소스를 관리하기 위해 추가 엔드포인트에 대한 아웃바운드 인터넷 액세스를 필요로 합니다. 이 끝점이 방화벽의 "허용" 목록에 추가되지 않은 경우 UI에 "서비스를 사용할 수 없음" 또는 "서비스 상태 확인 실패"에 대한 오류가 표시됩니다.
+
\https://netapp-cloud-account.auth0.com

* Cloud Volumes ONTAP 및 BlueXP 백업 및 복구를 번들로 제공할 수 있는 "CVO Professional" 패키지를 사용하는 경우 백업 및 복구 PAYGO 가입이 필요합니다. 과거에는 필요하지 않았습니다. 적격 Cloud Volumes ONTAP 시스템의 백업 및 복구 서브스크립션에는 비용이 청구되지 않지만 새 볼륨에 백업을 구성할 때 비용이 필요합니다.


====


=== S3 구성 ONTAP 시스템의 버킷에 볼륨을 백업하도록 지원이 추가되었습니다

이제 S3(Simple Storage Service)로 구성된 ONTAP 시스템을 사용하여 볼륨을 오브젝트 스토리지에 백업할 수 있습니다. 이는 온프레미스 ONTAP 시스템과 Cloud Volumes ONTAP 시스템 모두에서 지원됩니다. 이 구성은 인터넷 액세스가 없는 클라우드 배포 및 사내 위치("전용" 모드 배포)에서 지원됩니다.

ifdef::aws[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["자세한 정보"].

endif::aws[]



=== 이제 백업 파일에 보호된 볼륨의 기존 스냅샷을 포함할 수 있습니다

과거에는 최신 스냅샷 복사본으로 시작하는 것이 아니라, 초기 백업 파일에 읽기-쓰기 볼륨의 기존 Snapshot 복사본을 오브젝트 스토리지에 포함하는 기능이 있었습니다. 읽기 전용 볼륨(데이터 보호 볼륨)의 기존 스냅샷 복사본은 백업 파일에 포함되지 않았습니다. 이제 "DP" 볼륨의 백업 파일에 이전 Snapshot 복사본을 포함하도록 선택할 수 있습니다.

백업 마법사가 백업 단계 끝에 이러한 "기존 스냅샷"을 선택할 수 있는 프롬프트를 표시합니다.



=== BlueXP 백업 및 복구는 이후에 추가된 볼륨의 자동 백업을 더 이상 지원하지 않습니다

이전에는 백업 마법사에서 확인란을 선택하여 선택한 백업 정책을 클러스터에 추가되는 모든 볼륨에 적용할 수 있었습니다. 이 기능은 사용자 피드백 및 이 기능의 사용 부족을 기준으로 제거되었습니다. 클러스터에 추가된 새 볼륨에 대해 백업을 수동으로 활성화해야 합니다.



=== 작업 모니터링 페이지가 새로운 기능으로 업데이트되었습니다

이제 작업 모니터링 페이지에서 3-2-1 백업 전략과 관련된 자세한 정보를 확인할 수 있습니다. 이 서비스는 백업 전략과 관련된 추가 알림 알림도 제공합니다.

"백업 수명 주기" 유형 필터의 이름이 "보존"으로 변경되었습니다. 이 필터를 사용하여 백업 라이프사이클을 추적하고 모든 백업 복제본의 만료 날짜를 식별합니다. "보존" 작업 유형은 BlueXP 백업 및 복구로 보호되는 볼륨에서 시작된 모든 스냅샷 삭제 작업을 캡처합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["업데이트된 작업 모니터에 대해 자세히 알아보십시오"].



== 2023년 7월 6일



=== 이제 BlueXP 백업 및 복구에는 스냅샷 복사본 및 복제된 볼륨을 예약 및 생성하는 기능이 포함되어 있습니다

이제 BlueXP 백업 및 복구를 통해 3-2-1 전략을 구현할 수 있습니다. 이 전략을 통해 2개의 서로 다른 스토리지 시스템에 3개의 소스 데이터 복제본을 저장하고 1개의 복제본을 클라우드에 저장할 수 있습니다. 정품 인증 후 다음 사항이 있습니다.

* 소스 시스템에 있는 볼륨의 스냅샷 복제본입니다
* 다른 스토리지 시스템에 복제된 볼륨
* 오브젝트 스토리지에 있는 볼륨의 백업입니다


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["새로운 전체 스펙트럼 백업 및 복원 기능에 대해 자세히 알아보십시오"].

이 새로운 기능은 복구 작업에도 적용됩니다. 스냅샷 복사본, 복제된 볼륨 또는 클라우드의 백업 파일에서 복원 작업을 수행할 수 있습니다. 따라서 복구 비용과 속도를 비롯하여 복구 요구 사항에 맞는 백업 파일을 유연하게 선택할 수 있습니다.

이 새로운 기능과 사용자 인터페이스는 ONTAP 9.8 이상을 실행하는 클러스터에만 지원됩니다. 클러스터에 이전 버전의 소프트웨어가 있는 경우 이전 버전의 BlueXP 백업 및 복구를 계속 사용할 수 있습니다. 하지만 최신 기능을 사용하려면 지원되는 ONTAP 버전으로 업그레이드하는 것이 좋습니다. 이전 버전의 소프트웨어를 계속 사용하려면 다음 단계를 수행하십시오.

. 볼륨 * 탭에서 * 백업 설정 * 을 선택합니다.
. 백업 설정 페이지에서 * 이전 BlueXP 백업 및 복구 버전 표시 * 의 라디오 버튼을 클릭합니다.
+
그런 다음 이전 버전의 소프트웨어를 사용하여 이전 클러스터를 관리할 수 있습니다.





=== 오브젝트 스토리지로 백업할 스토리지 컨테이너를 생성하는 기능

오브젝트 스토리지에서 백업 파일을 생성할 때 기본적으로 백업 및 복구 서비스는 오브젝트 스토리지에 버킷을 생성합니다. 특정 이름을 사용하거나 특수 속성을 할당하려면 직접 버킷을 생성할 수 있습니다. 고유한 버킷을 생성하려면 활성화 마법사를 시작하기 전에 생성해야 합니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["오브젝트 스토리지 버킷을 생성하는 방법을 알아보십시오"].

StorageGRID 시스템에 백업 파일을 생성할 때 이 기능은 현재 지원되지 않습니다.



== 2023년 7월 4일



=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(클라우드 네이티브)

* SAP HANA 시스템
+
** Azure NetApp Files 2차 보호 기능이 있는 비 데이터 볼륨 및 글로벌 비 데이터 볼륨의 연결 및 복사본 복원을 지원합니다


* Oracle 데이터베이스
+
** Azure NetApp Files에서 Oracle 데이터베이스를 대체 위치로 복구할 수 있도록 지원합니다
** Azure NetApp Files에서 Oracle 데이터베이스 백업의 Oracle RMAN(Recovery Manager) 카탈로그 작성을 지원합니다
** 데이터베이스 호스트를 유지 관리 모드로 전환하여 유지 관리 작업을 수행할 수 있습니다






=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(하이브리드)

* 대체 위치로 복원을 지원합니다
* Oracle 데이터베이스 백업을 마운트할 수 있습니다
* GCP에서 아카이브 계층으로 백업 이동 지원




=== 가상 시스템의 BlueXP 백업 및 복구 기능 향상(하이브리드)

* NFS 및 VMFS 유형의 데이터 저장소 보호 지원
* VMware vSphere 호스트용 SnapCenter 플러그인의 등록을 취소할 수 있습니다
* 최신 데이터 저장소 및 백업의 업데이트 및 검색을 지원합니다




== 2023년 6월 5일



=== FlexGroup 볼륨은 DataLock 및 랜섬웨어 보호를 사용하여 백업 및 보호할 수 있습니다

FlexGroup 볼륨에 대한 백업 정책은 클러스터에서 ONTAP 9.13.1 이상을 실행할 때 DataLock 및 랜섬웨어 보호를 사용할 수 있습니다.



=== 새로운 보고 기능

이제 보고서 탭이 있으며 특정 계정, 작업 환경 또는 SVM 인벤토리에 대한 모든 백업이 포함된 백업 인벤토리 보고서를 생성할 수 있습니다. 또한 데이터 보호 작업 활동 보고서를 생성할 수 있습니다. 이 보고서는 서비스 수준 계약 모니터링에 도움이 되는 스냅샷, 백업, 클론 및 복원 작업에 대한 정보를 제공합니다. 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["데이터 보호 범위에 대한 보고"].



=== 작업 모니터 기능 향상

이제 Job Monitor 페이지에서 _backup lifeCycle_을 작업 유형으로 검토하여 전체 백업 주기를 추적할 수 있습니다. 또한 BlueXP 타임라인의 모든 작업에 대한 세부 정보를 볼 수 있습니다. 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["백업 및 복원 작업의 상태를 모니터링합니다"].



=== 불일치 정책 레이블에 대한 추가 알림 알림입니다

새 백업 경고가 추가되었습니다. "스냅샷 정책 레이블이 일치하지 않아 백업 파일이 생성되지 않았습니다." 백업 정책에 정의된 _label_이 스냅샷 정책에 matching_label_이 없는 경우 백업 파일이 생성되지 않습니다. 볼륨 스냅샷 정책에 누락 레이블을 추가하려면 시스템 관리자 또는 ONTAP CLI를 사용해야 합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["BlueXP 백업 및 복구가 전송할 수 있는 모든 경고를 검토합니다"].



=== 어두운 사이트에서 중요한 BlueXP 백업 및 복구 파일을 자동으로 백업합니다

"비공개 모드" 배포라고 하는 인터넷 액세스가 없는 사이트에서 BlueXP 백업 및 복구를 사용하는 경우 BlueXP 백업 및 복구 정보는 로컬 커넥터 시스템에만 저장됩니다. 이 새로운 기능은 중요한 BlueXP 백업 및 복구 데이터를 연결된 StorageGRID 시스템의 버킷에 자동으로 백업하므로 필요한 경우 이 데이터를 새 커넥터에 복원할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["자세한 정보"]



== 2023년 5월 8일



=== 이제 폴더 레벨 복구 작업은 아카이브 스토리지 및 잠긴 백업에서 지원됩니다

DataLock 및 랜섬웨어 보호를 사용하여 백업 파일을 구성했거나 백업 파일이 아카이브 스토리지에 있는 경우 클러스터에서 ONTAP 9.13.1 이상이 실행 중인 경우 폴더 레벨 복원 작업이 지원됩니다.



=== Google Cloud에 볼륨을 백업할 때 고객 관리 키를 지역 및 프로젝트 간 백업할 수 있습니다

이제 고객 관리 암호화 키(CMEK)의 프로젝트가 아닌 다른 프로젝트에 있는 버킷을 선택할 수 있습니다.

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["고객이 관리하는 암호화 키 설정에 대해 자세히 알아보십시오"]..

endif::gcp[]



=== AWS China 지역에서 백업 파일이 지원됩니다

클러스터가 ONTAP 9.12.1 이상을 실행 중인 경우 AWS China Beijing(cn-North-1) 및 Ningxia(cn-북서쪽-1) 지역이 백업 파일의 대상으로 지원됩니다.

BlueXP Connector에 할당된 IAM 정책은 all_Resource_sections의 AWS 리소스 이름 "arn"을 "AWS"에서 "AWS-cn"로 변경해야 합니다. 예를 들어 "arn:AWS-cn:S3::NetApp-backup- *"를 변경할 수 있습니다.

ifdef::aws[]

자세한 내용은 및 를 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Cloud Volumes ONTAP 데이터를 Amazon S3에 백업합니다"] https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["온프레미스 ONTAP 데이터를 Amazon S3에 백업합니다"] 참조하십시오.

endif::aws[]



=== 작업 모니터 기능 향상

ONTAP 9.13.1 이상을 실행하는 온-프레미스 ONTAP 시스템의 경우 * 작업 모니터링 * 탭에서 이러한 지속적인 백업 작업과 같은 시스템 시작 작업을 사용할 수 있습니다. 이전 ONTAP 버전은 사용자가 시작한 작업만 표시합니다.



== 2023년 4월 14일



=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(클라우드 네이티브)

* SAP HANA 데이터베이스
+
** 스크립트 기반 시스템 새로 고침을 지원합니다
** Azure NetApp Files 백업이 구성된 경우 단일 파일 스냅샷 복원 지원
** 플러그인 업그레이드를 지원합니다


* Oracle 데이터베이스
+
** 루트가 아닌 sudo 사용자 구성을 단순화하여 플러그인 배포를 개선했습니다
** 플러그인 업그레이드를 지원합니다
** Azure NetApp Files에서 Oracle 데이터베이스의 자동 검색 및 정책 기반 보호를 지원합니다
** 세분화된 복구를 통해 Oracle 데이터베이스를 원래 위치로 복구할 수 있습니다






=== 애플리케이션의 BlueXP 백업 및 복구 기능 향상(하이브리드)

* 애플리케이션(하이브리드)에 대한 BlueXP 백업 및 복구는 SaaS 제어 플레인에서 주도하고 있습니다
* 클라우드 네이티브 API에 맞춰 하이브리드 REST API 수정
* 이메일 알림을 지원합니다




== 2023년 4월 4일



=== "제한" 모드에서 Cloud Volumes ONTAP 시스템의 데이터를 클라우드로 백업하는 기능

이제 AWS, Azure 및 GCP 상업 지역에 설치된 Cloud Volumes ONTAP 시스템의 데이터를 "제한된 모드"로 백업할 수 있습니다. 이렇게 하려면 먼저 "제한된" 상업 지역에 커넥터를 설치해야 합니다. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드에 대해 자세히 알아보십시오"^]..

ifdef::aws[]

을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Cloud Volumes ONTAP 데이터를 Amazon S3에 백업"]

endif::aws[]

ifdef::azure[]

을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Azure Blob에 Cloud Volumes ONTAP 데이터 백업"]참조하십시오.

endif::azure[]



=== API를 사용하여 사내 ONTAP 볼륨을 ONTAP S3에 백업하는 기능

API의 새로운 기능을 사용하면 BlueXP 백업 및 복구를 사용하여 볼륨 스냅샷을 ONTAP S3에 백업할 수 있습니다. 이 기능은 현재 사내 ONTAP 시스템에서만 사용할 수 있습니다. 자세한 지침은 블로그를 참조하십시오 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["ONTAP S3와 타겟 통합"^].



=== Azure 저장소 계정의 영역 중복성 측면을 LRS에서 ZRS로 변경할 수 있습니다

Cloud Volumes ONTAP 시스템에서 Azure 스토리지로 백업을 생성할 때 기본적으로 BlueXP 백업 및 복구는 비용 최적화를 위해 LRS(Local Redundancy)를 사용하여 Blob 컨테이너를 프로비저닝합니다. 데이터를 다른 영역 간에 복제하려면 이 설정을 영역 중복(ZRS)으로 변경할 수 있습니다. 에 대한 Microsoft 지침을 참조하십시오 https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["스토리지 계정의 복제 방법을 변경합니다"^].



=== 작업 모니터 기능 향상

* 이제 BlueXP 백업 및 복구 UI 및 API에서 시작된 사용자 시작 백업 및 복원 작업과 이러한 진행 중인 백업 작업을 ONTAP 9.13.0 이상을 실행하는 Cloud Volumes ONTAP 시스템의 * 작업 모니터링 * 탭에서 사용할 수 있습니다. 이전 ONTAP 버전은 사용자가 시작한 작업만 표시합니다.
* 모든 작업에 대한 보고를 위해 CSV 파일을 다운로드할 수 있을 뿐만 아니라 단일 작업에 대한 JSON 파일을 다운로드하여 자세한 내용을 볼 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["자세한 정보"].
* 두 가지 새로운 백업 작업 경고가 추가되었습니다. "예약된 작업 실패" 및 "복원 작업이 완료되지만 경고가 있음" https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["BlueXP 백업 및 복구가 전송할 수 있는 모든 경고를 검토합니다"].




== 2023년 3월 9일



=== 이제 폴더 레벨 복구 작업에 모든 하위 폴더 및 파일이 포함됩니다

이전에는 폴더를 복원했을 때 해당 폴더의 파일만 복원되었고 하위 폴더 또는 하위 폴더의 파일은 복원되지 않았습니다. 이제 ONTAP 9.13.0 이상을 사용하는 경우 선택한 폴더에 있는 모든 하위 폴더와 파일이 복원됩니다. 따라서 최상위 폴더에 여러 개의 중첩된 폴더가 있는 경우 많은 시간과 비용을 절약할 수 있습니다.



=== 아웃바운드 연결이 제한된 사이트의 Cloud Volumes ONTAP 시스템 데이터를 백업하는 기능

이제 AWS 및 Azure 상업 지역에 설치된 Cloud Volumes ONTAP 시스템의 데이터를 Amazon S3 또는 Azure Blob으로 백업할 수 있습니다. 이렇게 하려면 커머셜 지역의 Linux 호스트에 커넥터를 "제한 모드"로 설치하고 Cloud Volumes ONTAP 시스템도 배포해야 합니다.

ifdef::aws[]

을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Cloud Volumes ONTAP 데이터를 Amazon S3에 백업"]참조하십시오.

endif::aws[]

ifdef::azure[]

을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Azure Blob에 Cloud Volumes ONTAP 데이터 백업"]참조하십시오.

endif::azure[]



=== 작업 모니터의 여러 가지 개선 사항

* 작업 모니터링 페이지에는 시간, 워크로드(볼륨, 애플리케이션 또는 가상 머신), 작업 유형, 상태, 작업 환경 및 스토리지 VM "application_3"과 같은 자원 검색을 위해 자유 텍스트를 입력할 수도 있습니다.  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["고급 필터 사용 방법을 확인하십시오"]..
* 이제 BlueXP 백업 및 복구 UI 및 API에서 시작된 사용자 시작 백업 및 복원 작업과 이러한 진행 중인 백업 작업을 ONTAP 9.13.0 이상을 실행하는 Cloud Volumes ONTAP 시스템의 * 작업 모니터링 * 탭에서 사용할 수 있습니다. 이전 버전의 Cloud Volumes ONTAP 시스템 및 온-프레미스 ONTAP 시스템은 현재 사용자가 시작한 작업만 표시합니다.




== 2023년 2월 6일



=== StorageGRID 시스템에서 이전 백업 파일을 Azure 아카이브 스토리지로 이동하는 기능입니다

이제 StorageGRID 시스템의 이전 백업 파일을 Azure의 아카이브 스토리지로 계층화할 수 있습니다. 이를 통해 StorageGRID 시스템의 공간을 절약하고, 이전 백업 파일에 저렴한 스토리지 클래스를 사용하여 비용을 절감할 수 있습니다.

이 기능은 온프레미스 클러스터가 ONTAP 9.12.1 이상을 사용하고 있고 StorageGRID 시스템에서 11.4 이상을 사용하는 경우 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["자세히 알아보기"^].



=== DataLock 및 랜섬웨어 보호는 Azure Blob의 백업 파일에 대해 구성할 수 있습니다

이제 DataLock 및 랜섬웨어 보호가 Azure Blob에 저장된 백업 파일에 지원됩니다. Cloud Volumes ONTAP 또는 온프레미스 ONTAP 시스템에서 ONTAP 9.12.1 이상을 실행하는 경우 백업 파일을 잠그고 스캔하여 잠재적인 랜섬웨어를 탐지할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].



=== 백업 및 복원 FlexGroup 볼륨 개선 사항

* 이제 FlexGroup 볼륨을 복원할 때 여러 Aggregate를 선택할 수 있습니다. 마지막 릴리즈에서는 단일 애그리게이트만 선택할 수 있었습니다.
* FlexGroup 볼륨 복원은 이제 Cloud Volumes ONTAP 시스템에서 지원됩니다. 마지막 릴리즈에서는 사내 ONTAP 시스템에만 복구할 수 있었습니다.




=== Cloud Volumes ONTAP 시스템은 이전 백업을 Google 아카이브 스토리지로 이동할 수 있습니다

백업 파일은 처음에 Google Standard 스토리지 클래스에서 생성됩니다. 이제 BlueXP 백업 및 복구를 사용하여 Google Archive 스토리지에 이전 백업을 계층화하여 비용을 추가로 최적화할 수 있습니다. 마지막 릴리즈에서는 사내 ONTAP 클러스터에서만 이 기능을 지원했으며, 이제 Google Cloud에 구축된 Cloud Volumes ONTAP 시스템도 지원됩니다.



=== 이제 볼륨 복원 작업을 통해 볼륨 데이터를 복원할 SVM을 선택할 수 있습니다

이제 볼륨 데이터를 ONTAP 클러스터의 다른 스토리지 VM으로 복원할 수 있습니다. 과거에는 스토리지 VM을 선택할 기능이 없었습니다.



=== MetroCluster 구성의 볼륨 지원 향상

ONTAP 9.12.1 GA 이상을 사용하는 경우 MetroCluster 구성에서 기본 시스템에 연결하면 백업이 지원됩니다. 전체 백업 구성이 보조 시스템으로 전송되므로 전환 후 클라우드 백업이 자동으로 계속됩니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["자세한 내용은 백업 제한 사항 을 참조하십시오"].



== 2023년 1월 9일



=== StorageGRID 시스템에서 이전 백업 파일을 AWS S3 아카이브 스토리지로 이동 가능

이제 StorageGRID 시스템의 이전 백업 파일을 AWS S3의 아카이브 스토리지로 계층화할 수 있습니다. 이를 통해 StorageGRID 시스템의 공간을 절약하고, 이전 백업 파일에 저렴한 스토리지 클래스를 사용하여 비용을 절감할 수 있습니다. AWS S3 Glacier 또는 S3 Glacier Deep Archive 스토리지에 백업을 계층화하도록 선택할 수 있습니다.

이 기능은 온프레미스 클러스터에서 ONTAP 9.12.1 이상을 사용하고 StorageGRID 시스템에서 11.3 이상을 사용하는 경우 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["자세히 알아보기"].



=== Google Cloud에서 데이터 암호화를 위한 자체 고객 관리 키를 선택할 수 있습니다

ONTAP 시스템에서 Google 클라우드 스토리지로 데이터를 백업할 때 이제 Google에서 관리하는 기본 암호화 키를 사용하는 대신 활성화 마법사에서 데이터 암호화에 대해 고객이 관리하는 키를 직접 선택할 수 있습니다. 먼저 Google에서 고객이 관리하는 암호화 키를 설정한 다음 BlueXP 백업 및 복구를 활성화할 때 세부 정보를 입력합니다.



=== Google Cloud Storage에서 백업을 생성하는 서비스 계정에 더 이상 "스토리지 관리자" 역할이 필요하지 않습니다

이전 릴리즈에서는 BlueXP 백업 및 복구를 통해 Google Cloud Storage 버킷에 액세스할 수 있도록 하는 서비스 계정에 "스토리지 관리자" 역할이 필요했습니다. 이제 서비스 계정에 할당할 수 있는 권한이 축소된 사용자 지정 역할을 만들 수 있습니다.

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["백업을 위해 Google Cloud Storage를 준비하는 방법을 알아보십시오"]..

endif::gcp[]



=== 인터넷 액세스 없이 사이트에서 검색 및 복원을 사용하여 데이터를 복원할 수 있도록 지원이 추가되었습니다

인터넷에 액세스할 수 없는 사이트의 ONTAP 클러스터 데이터를 StorageGRID으로 백업하는 경우(다크 사이트 또는 오프라인 사이트라고도 함) 이제 검색 및 복원 옵션을 사용하여 필요한 경우 데이터를 복원할 수 있습니다. 이 기능을 사용하려면 BlueXP 커넥터(버전 3.9.25 이상)가 오프라인 사이트에 배포되어야 합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["검색 및 amp; 복원을 사용하여 ONTAP 데이터를 복원하는 방법을 확인하십시오"].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["오프라인 사이트에 커넥터를 설치하는 방법을 알아봅니다"].



=== 작업 모니터링 결과 페이지를 .csv 보고서로 다운로드할 수 있습니다

작업 모니터링 페이지를 필터링하여 관심 있는 작업 및 작업을 표시한 후에는 해당 데이터의 .csv 파일을 생성하고 다운로드할 수 있습니다. 그런 다음 정보를 분석하거나 조직의 다른 사용자에게 보고서를 보낼 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["작업 모니터링 보고서를 생성하는 방법을 참조하십시오"].



== 2022년 12월 19일



=== 애플리케이션의 클라우드 백업 개선

* SAP HANA 데이터베이스
+
** Azure NetApp Files에 상주하는 SAP HANA 데이터베이스의 정책 기반 백업 및 복원을 지원합니다
** 사용자 지정 정책을 지원합니다


* Oracle 데이터베이스
+
** 호스트를 추가하고 플러그인을 자동으로 구축합니다
** 사용자 지정 정책을 지원합니다
** Cloud Volumes ONTAP에 상주하는 Oracle 데이터베이스의 정책 기반 백업, 복원 및 복제를 지원합니다
** NetApp ONTAP용 Amazon FSx에 상주하는 Oracle 데이터베이스의 정책 기반 백업 및 복원을 지원합니다
** 연결 및 복사 방법을 사용하여 Oracle 데이터베이스 복원을 지원합니다
** Oracle 21c를 지원합니다
** 클라우드 네이티브 Oracle 데이터베이스의 클론 복제 지원






=== 가상 머신용 Cloud Backup의 향상된 기능

* 가상 머신
+
** 사내 보조 스토리지에서 가상 머신 백업
** 사용자 지정 정책을 지원합니다
** 하나 이상의 데이터 저장소를 백업하기 위해 Google Cloud Platform(GCP) 지원
** Glacier, Deep Glacier 및 Azure Archive와 같은 저비용 클라우드 스토리지를 지원합니다






== 2022년 12월 6일



=== 필요한 커넥터 아웃바운드 인터넷 액세스 엔드포인트 변경

Cloud Backup의 변경으로 인해 Cloud Backup 작업을 성공적으로 수행하려면 다음 Connector 엔드포인트를 변경해야 합니다.

[cols="50,50"]
|===
| 이전 끝점 | 새 끝점 


| https://cloudmanager.cloud.netapp.com 으로 문의하십시오 | https://api.bluexp.netapp.com 으로 문의하십시오 


| https://*.cloudmanager.cloud.netapp.com 으로 문의하십시오 | https://*.api.bluexp.netapp.com 으로 문의하십시오 
|===
의 전체 끝점 목록을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["설치하고"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google 클라우드"^], 또는 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure를 지원합니다"^] 설명합니다.



=== UI에서 Google Archival Storage 클래스를 선택할 수 있습니다

백업 파일은 처음에 Google Standard 스토리지 클래스에서 생성됩니다. 이제 Cloud Backup UI를 사용하여 추가 비용 최적화를 위해 일정 일 후에 이전 백업을 Google Archive 스토리지에 계층화할 수 있습니다.

이 기능은 현재 ONTAP 9.12.1 이상을 사용하는 온프레미스 ONTAP 클러스터에 지원됩니다. 현재 Cloud Volumes ONTAP 시스템에서는 사용할 수 없습니다.



=== FlexGroup 볼륨 지원

Cloud Backup은 이제 FlexGroup 볼륨 백업 및 복원을 지원합니다. ONTAP 9.12.1 이상을 사용하는 경우 FlexGroup 볼륨을 퍼블릭 및 프라이빗 클라우드 스토리지에 백업할 수 있습니다. FlexVol 및 FlexGroup 볼륨이 포함된 작업 환경이 있는 경우 ONTAP 소프트웨어를 업데이트하면 해당 시스템의 FlexGroup 볼륨을 백업할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["지원되는 볼륨 유형의 전체 목록을 참조하십시오"].



=== Cloud Volumes ONTAP 시스템의 백업에서 특정 애그리게이트로 데이터를 복원하는 기능

이전 릴리즈에서는 데이터를 사내 ONTAP 시스템으로 복원할 때만 애그리게이트를 선택할 수 있었습니다. 이제 이 기능은 데이터를 Cloud Volumes ONTAP 시스템으로 복원할 때 작동합니다.



== 2022년 11월 2일



=== 이전 Snapshot 복사본을 기본 백업 파일로 내보낼 수 있습니다

작업 환경에 백업 일정 레이블(예: 일별, 주별 등)과 일치하는 볼륨의 로컬 스냅샷 복사본이 있는 경우 이러한 기존 스냅샷을 백업 파일로 오브젝트 스토리지로 내보낼 수 있습니다. 이전 Snapshot 복사본을 기본 백업 복사본으로 이동하여 클라우드에서 백업을 초기화할 수 있습니다.

이 옵션은 작업 환경에서 Cloud Backup을 활성화할 때 사용할 수 있습니다. 나중에 에서 이 설정을 변경할 수도 있습니다 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["고급 설정 페이지"].



=== 이제 소스 시스템에서 더 이상 필요하지 않은 볼륨을 아카이빙하는 데 Cloud Backup을 사용할 수 있습니다

이제 볼륨에 대한 백업 관계를 삭제할 수 있습니다. 이렇게 하면 새 백업 파일 생성을 중지하고 소스 볼륨을 삭제하지만 기존의 모든 백업 파일은 보존하려는 경우에 아카이빙 메커니즘이 제공됩니다. 따라서 나중에 필요할 경우 백업 파일에서 볼륨을 복원하는 동시에 소스 스토리지 시스템의 공간을 지울 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["자세히 알아보기"].



=== 이메일 및 알림 센터에서 Cloud Backup 경고를 받도록 지원이 추가되었습니다

Cloud Backup이 BlueXP 알림 서비스에 통합되었습니다. BlueXP 메뉴 표시줄에서 알림 표시를 클릭하여 Cloud Backup 알림을 표시할 수 있습니다. 또한 시스템에 로그인하지 않은 경우에도 중요한 시스템 작업을 알 수 있도록 이메일로 알림을 보내도록 BlueXP를 구성할 수 있습니다. 이 이메일은 백업 및 복원 작업을 알아야 하는 모든 수신자에게 보낼 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["자세히 알아보기"].



=== 새로운 고급 설정 페이지에서는 클러스터 레벨 백업 설정을 변경할 수 있습니다

이 새 페이지에서는 각 ONTAP 시스템에 대한 클라우드 백업을 활성화할 때 설정하는 여러 클러스터 레벨 백업 설정을 변경할 수 있습니다. "기본" 백업 설정으로 적용되는 일부 설정을 수정할 수도 있습니다. 변경할 수 있는 전체 백업 설정은 다음과 같습니다.

* ONTAP 시스템에서 오브젝트 스토리지에 액세스할 수 있는 권한을 제공하는 스토리지 키입니다
* 백업을 객체 저장소에 업로드하기 위해 할당된 네트워크 대역폭입니다
* 이후 볼륨에 대한 자동 백업 설정(및 정책
* 아카이브 스토리지 클래스(AWS만 해당)
* 초기 기본 백업 파일에 기간별 스냅샷 복사본이 포함되어 있는지 여부
* 소스 시스템에서 "연간" 스냅샷을 제거할지 여부를 나타냅니다
* 오브젝트 스토리지에 연결된 ONTAP IPspace(활성화 중에 잘못 선택한 경우)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["클러스터 레벨 백업 설정 관리에 대해 자세히 알아보십시오"].



=== 이제 온-프레미스 Connector를 사용할 때 검색 및 복원을 사용하여 백업 파일을 복원할 수 있습니다

이전 릴리즈에서는 Connector가 사내에 구축될 때 퍼블릭 클라우드에 백업 파일을 생성하기 위한 지원이 추가되었습니다. 이 릴리즈에서는 검색 및 복원을 사용하여 Connector가 사내에 구축된 Amazon S3 또는 Azure Blob에서 백업을 복원할 수 있도록 지원이 계속 제공됩니다. 또한 검색 및 복원 기능은 StorageGRID 시스템에서 온-프레미스 ONTAP 시스템으로 지금 백업을 복원할 수 있도록 지원합니다.

현재 Google Cloud Storage에서 백업을 복원하려면 검색 및 복원을 사용할 때 Google Cloud Platform에 Connector를 구축해야 합니다.



=== 작업 모니터링 페이지가 업데이트되었습니다

다음 업데이트가 에 업데이트되었습니다 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["작업 모니터링 페이지"]:

* "Workload" 열을 사용할 수 있으므로 페이지를 필터링하여 볼륨, 애플리케이션 및 가상 머신 등의 백업 서비스에 대한 작업을 볼 수 있습니다.
* 특정 백업 작업에 대한 세부 정보를 보려면 "사용자 이름" 및 "작업 유형"에 대한 새 열을 추가할 수 있습니다.
* 작업 세부 정보 페이지에는 기본 작업을 완료하기 위해 실행 중인 모든 하위 작업이 표시됩니다.
* 이 페이지는 15분마다 자동으로 새로 고쳐져 항상 가장 최근의 작업 상태 결과를 볼 수 있습니다. 새로 고침 * 버튼을 클릭하여 페이지를 즉시 업데이트할 수 있습니다.




=== AWS 교차 계정 백업 기능이 향상되었습니다

소스 볼륨에 사용 중인 것과 다른 Cloud Volumes ONTAP 계정을 백업에 사용하려면 BlueXP에서 대상 AWS 계정 자격 증명을 추가해야 하며, BlueXP에 사용 권한을 제공하는 IAM 역할에 "S3:PutBucketPolicy" 및 "S3:PutnerOwshipControls" 권한을 추가해야 합니다. 이전에는 AWS 콘솔에서 여러 설정을 구성해야 했습니다. 이제는 더 이상 그렇게 할 필요가 없습니다.



== 2022년 9월 28일



=== 애플리케이션의 클라우드 백업 개선

* Google Cloud Platform(GCP) 및 StorageGRID를 지원하여 애플리케이션 정합성 보장 스냅샷을 백업합니다
* 사용자 지정 정책을 생성합니다
* 아카이브 스토리지 지원
* SAP HANA 애플리케이션 백업
* VMware 환경에 있는 Oracle 및 SQL 애플리케이션을 백업합니다
* 사내 2차 스토리지에서 애플리케이션을 백업합니다
* 백업을 비활성화합니다
* SnapCenter 서버 등록을 취소합니다




=== 가상 머신용 Cloud Backup의 향상된 기능

* 하나 이상의 데이터 저장소를 백업하기 위해 StorageGRID를 지원합니다
* 사용자 지정 정책을 생성합니다




== 2022년 9월 19일



=== StorageGRID 시스템의 백업 파일에 대해 DataLock 및 랜섬웨어 보호를 구성할 수 있습니다

마지막 릴리즈에서는 Amazon S3 버킷에 저장된 백업에 대해 _DataLock 및 랜섬웨어 보호_가 도입되었습니다. 이 릴리즈는 StorageGRID 시스템에 저장된 백업 파일에 대한 지원을 확장합니다. 클러스터가 ONTAP 9.11.1 이상을 사용하고 있고 StorageGRID 시스템에서 버전 11.6.0.3 이상을 실행 중인 경우 이 새로운 백업 정책 옵션을 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLock 및 랜섬웨어 보호를 사용하여 백업을 보호하는 방법에 대해 자세히 알아보십시오"^].

버전 3.9.22 이상의 소프트웨어가 있는 커넥터를 실행해야 합니다. Connector는 구내에 설치해야 하며 인터넷에 접속하거나 접속하지 않은 사이트에 설치할 수 있습니다.



=== 이제 백업 파일에서 폴더 레벨 복구를 사용할 수 있습니다

이제 해당 폴더(디렉토리 또는 공유)의 모든 파일에 액세스해야 하는 경우 백업 파일에서 폴더를 복원할 수 있습니다. 폴더 복원은 전체 볼륨을 복원하는 것보다 훨씬 효율적입니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다. 현재 단일 폴더만 선택하고 복원할 수 있으며, 해당 폴더의 파일만 복원할 수 있습니다. 하위 폴더 또는 하위 폴더의 파일은 복원되지 않습니다.



=== 이제 아카이브 스토리지로 이동한 백업에서 파일 레벨 복구를 사용할 수 있습니다

과거에는 아카이브 스토리지(AWS 및 Azure만 해당)로 이동한 백업 파일의 볼륨만 복원할 수 있었습니다. 이제 이러한 아카이빙된 백업 파일에서 개별 파일을 복원할 수 있습니다. 이 기능은 ONTAP 9.11.1 이상을 사용하는 경우 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 이제 파일 레벨 복구를 통해 원본 소스 파일을 덮어쓸 수 있습니다

이전에는 원래 볼륨으로 복구된 파일이 항상 "Restore_<file_name>"이라는 접두사가 붙은 새 파일로 복원되었습니다. 이제 파일을 볼륨의 원래 위치로 복구할 때 원본 소스 파일을 덮어쓰도록 선택할 수 있습니다. 이 기능은 Browse & Restore 메서드와 Search & Restore 메서드를 모두 사용하여 복원 작업에 사용할 수 있습니다.



=== 끌어서 놓기를 통해 클라우드 백업을 StorageGRID 시스템에 사용할 수 있습니다

를 누릅니다 https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 백업 대상은 Canvas에 작업 환경으로 있으며, 온프레미스 ONTAP 작업 환경을 대상으로 끌어서 클라우드 백업 설정 마법사를 시작할 수 있습니다.
