= UI 개선
:allow-uri-read: 




=== UI 개선

이 릴리스는 인터페이스를 단순화함으로써 사용자 경험을 향상시킵니다.

* 볼륨 테이블에서 애그리게이트 열을 제거하고 V2 대시보드의 볼륨 테이블에서 스냅샷 정책, 백업 정책 및 복제 정책 열을 제거하면 레이아웃이 보다 간소화됩니다.
* 드롭다운 목록에서 활성화되지 않은 작업 환경을 제외하면 인터페이스가 덜 복잡해지고 탐색이 더 효율적으로 수행되며 로딩 속도가 빨라집니다.
* 태그 열에서 정렬을 사용할 수 없지만 중요한 정보에 쉽게 액세스할 수 있도록 태그를 계속 볼 수 있습니다.
* 보호 아이콘의 라벨을 제거하면 더 깔끔한 외관을 연출하고 로딩 시간을 줄일 수 있습니다.
* 작업 환경 활성화 프로세스 중에 대화 상자에 로드 아이콘이 표시되어 검색 프로세스가 완료될 때까지 피드백을 제공하여 시스템 운영에 대한 투명성과 신뢰도를 높입니다.




=== 향상된 볼륨 대시보드(미리 보기)

이제 볼륨 대시보드가 10초 이내에 로드되므로 훨씬 빠르고 효율적인 인터페이스를 제공합니다. 이 Preview 버전은 일부 고객에게 제공되며 이러한 개선 사항을 조기에 확인할 수 있습니다.



=== 타사 Wasabi 개체 저장소 지원(Preview)

BlueXP  백업 및 복구는 이제 Wasabi에 중점을 두고 타사 오브젝트 스토어까지 지원을 확장하고 있습니다. 이 새로운 미리 보기 기능을 사용하면 백업 및 복구 요구에 S3 호환 오브젝트 저장소를 활용할 수 있습니다.



==== Wasabi 시작하기

타사 스토리지를 개체 저장소로 사용하려면 BlueXP  커넥터 내에서 플래그를 설정해야 합니다. 그런 다음 타사 오브젝트 저장소에 대한 연결 정보를 입력하고 백업 및 복구 워크플로에 통합할 수 있습니다.

.단계
. SSH를 사용하여 커넥터에 연결합니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너로 이동합니다.
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. VIM 또는 다른 편집기를 통해 폴더 내에서 파일을 `config` 엽니다 `default.json`.
+
[listing]
----
vi default.json
----
. modify `allow-s3-compatible`:false to:true로 `allow-s3-compatible` 변경합니다.
. 변경 사항을 저장합니다.
. 컨테이너에서 나갑니다.
. BlueXP  백업 및 복구 CBS 서버 컨테이너를 다시 시작합니다.


.결과
컨테이너가 다시 켜지면 BlueXP  백업 및 복구 UI를 엽니다. 백업을 시작하거나 백업 전략을 편집하면 AWS, Microsoft Azure, Google Cloud, StorageGRID 및 ONTAP S3의 다른 백업 공급자와 함께 새로운 공급업체 "S3 호환"이 표시됩니다.



==== 미리보기 모드 제한

이 기능이 미리 보기에 있는 동안 다음 제한 사항을 고려하십시오.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 사용하도록 설정할 수 없습니다.
* 정책에서 아카이브 모드를 사용하도록 설정하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster는 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


이 미리 보기를 진행하는 동안 이 새로운 기능을 살펴보고 전체 기능이 배포되기 전에 타사 개체 저장소와의 통합에 대한 피드백을 제공하는 것이 좋습니다.
