= 고성능 인덱싱
:allow-uri-read: 




=== 고성능 인덱싱

BlueXP  백업 및 복구에는 소스 작업 환경에서 데이터를 보다 효율적으로 인덱싱할 수 있는 업데이트된 인덱싱 기능이 도입되었습니다. 새로운 인덱싱 기능에는 UI 업데이트, 데이터 복원 검색 및 복원 방법의 향상된 성능, 글로벌 검색 기능으로 업그레이드 및 향상된 확장성 등이 포함됩니다.

개선된 사항은 다음과 같습니다.

* * 폴더 통합 *: 업데이트된 버전은 특정 식별자가 포함된 이름을 사용하여 폴더를 그룹화하여 인덱싱 프로세스를 원활하게 합니다.
* * Parquet 파일 압축 *: 업데이트된 버전은 각 볼륨을 인덱싱하는 데 사용되는 파일 수를 줄여 프로세스를 단순화하고 추가 데이터베이스가 필요하지 않습니다.
* * 더 많은 세션으로 스케일 아웃 *: 새로운 버전은 인덱싱 작업을 처리하기 위해 더 많은 세션을 추가하여 프로세스 속도를 높입니다.
* * 다중 인덱스 컨테이너 지원 * : 새 버전은 인덱싱 작업을 더 잘 관리하고 배포하기 위해 여러 컨테이너를 사용합니다.
* * 분할 색인 워크플로 * : 새 버전은 인덱싱 프로세스를 두 부분으로 분할하여 효율성을 향상시킵니다.
* * 향상된 동시성 * : 새로운 버전을 사용하면 동시에 디렉토리를 삭제하거나 이동할 수 있으므로 인덱싱 프로세스가 빨라집니다.


.이 기능의 이점은 누구입니까?
새로운 인덱싱 기능은 모든 신규 고객이 사용할 수 있습니다.

.인덱싱을 활성화하려면 어떻게 해야 합니까?
데이터를 복원하는 검색 및 복원 방법을 사용하려면 먼저 볼륨 또는 파일을 복원하려는 각 소스 작업 환경에서 "인덱싱"을 활성화해야 합니다. 따라서 인덱스화된 카탈로그가 모든 볼륨과 모든 백업 파일을 추적할 수 있어 빠르고 효율적으로 검색할 수 있습니다.

검색 및 복원을 수행할 때 "인덱싱 사용" 옵션을 선택하여 소스 작업 환경에서 인덱싱을 활성화합니다.

자세한 내용은 설명서를 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["검색 및 복원 을 사용하여 ONTAP 데이터를 복원하는 방법"]참조하십시오.

.지원되는 배율
새 인덱싱 기능은 다음을 지원합니다.

* 3분 이내에 글로벌 검색 효율성 향상
* 최대 50억 개의 파일
* 클러스터당 최대 5000개의 볼륨
* 볼륨당 최대 100,000개의 스냅샷 지원
* 기준 색인에 대한 최대 시간은 7일 미만입니다. 실제 시간은 환경에 따라 다릅니다.




=== 글로벌 검색 성능 향상

이번 릴리스에는 글로벌 검색 성능 향상도 포함되어 있습니다. 이제 진행률 표시기 및 파일 수와 검색에 걸리는 시간을 포함하여 보다 자세한 검색 결과가 표시됩니다. 검색 및 색인화를 위한 전용 컨테이너를 통해 5분 이내에 글로벌 검색이 완료됩니다.

글로벌 검색과 관련된 고려 사항은 다음과 같습니다.

* 새 인덱스는 시간별 스냅샷으로 레이블이 지정된 스냅샷에 대해 수행되지 않습니다.
* 새로운 인덱싱 기능은 FlexVol의 스냅샷에만 작동하며, FlexGroups의 스냅샷에는 작동하지 않습니다.

