= 볼륨 마이그레이션을 위해 SnapMirror에서 클라우드로 재동기화
:allow-uri-read: 




=== 볼륨 마이그레이션을 위해 SnapMirror에서 클라우드로 재동기화

SnapMirror to Cloud 재동기화 기능은 NetApp 환경에서 볼륨을 마이그레이션하는 동안 데이터 보호 및 연속성을 간소화합니다. SnapMirror LRSE(논리적 복제)를 사용하여 온프레미스 NetApp 구축에서 다른 구축으로 또는 Cloud Volumes ONTAP 또는 Cloud Volumes Service와 같은 클라우드 기반 솔루션으로 볼륨을 마이그레이션한 경우, SnapMirror에서 클라우드 재동기화는 기존 클라우드 백업이 그대로 유지되고 작동되도록 보장합니다.

이 기능을 사용하면 시간이 오래 걸리고 리소스 소모가 많은 기준선 변경 작업이 필요하지 않으므로 백업 작업이 마이그레이션 후 작업을 계속할 수 있습니다. 이 기능은 워크로드 마이그레이션 시나리오에 유용하며 FlexVols와 FlexGroups를 모두 지원하며 ONTAP 버전 9.16.1부터 사용할 수 있습니다.

SnapMirror to Cloud Resync는 환경 간 백업 연속성을 유지함으로써 운영 효율성을 개선하고 하이브리드 및 멀티 클라우드 데이터 관리의 복잡성을 줄일 수 있습니다.

재동기화 작업을 수행하는 방법에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-migrate-resync.html["SnapMirror를 사용하여 볼륨을 클라우드 재동기화로 마이그레이션"].



=== 타사 MinIO 개체 저장소 지원(미리 보기)

이제 BlueXP  백업 및 복구는 MinIO에 중점을 두고 타사 오브젝트 저장소까지 지원을 확장합니다. 이 새로운 미리 보기 기능을 사용하면 백업 및 복구 요구에 S3 호환 오브젝트 저장소를 활용할 수 있습니다.

이 미리 보기 버전을 사용하면 전체 기능이 배포되기 전에 타사 개체 저장소와의 강력한 통합을 보장할 수 있습니다. 이 새로운 기능을 살펴보고 서비스 개선에 도움이 되는 피드백을 제공하는 것이 좋습니다.


IMPORTANT: 이 기능은 운영 환경에서 사용해서는 안 됩니다.

* 미리보기 모드 제한 *

이 기능이 미리보기에 있는 동안 몇 가지 제한 사항이 있습니다.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 활성화할 수 없습니다.
* 정책에서 아카이브 모드를 사용하도록 설정하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster는 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


* 시작하기 *

이 미리 보기 기능을 사용하려면 BlueXP  커넥터에서 플래그를 활성화해야 합니다. 그런 다음 백업 섹션에서 * 타사 호환 * 개체 저장소를 선택하여 보호 워크플로에 MinIO 타사 개체 저장소의 연결 세부 정보를 입력할 수 있습니다.
