= BlueXP에서 ONTAP 시스템을 검색합니다
:allow-uri-read: 


소스 사내 ONTAP 시스템과 보조 온프레미스 ONTAP 또는 Cloud Volumes ONTAP 시스템을 준비해야 합니다.

ONTAP 클러스터를 준비하려면 다음 단계를 수행해야 합니다.

* BlueXP에서 ONTAP 시스템을 검색합니다
* ONTAP 시스템 요구 사항을 확인합니다
* 오브젝트 스토리지에 데이터를 백업하기 위한 ONTAP 네트워킹 요구 사항을 확인합니다
* 볼륨 복제에 대한 ONTAP 네트워킹 요구 사항을 확인합니다




=== BlueXP에서 ONTAP 시스템을 검색합니다

BlueXP Canvas에서 소스 온-프레미스 ONTAP 시스템과 보조 온-프레미스 ONTAP 또는 Cloud Volumes ONTAP 시스템을 모두 사용할 수 있어야 합니다.

클러스터를 추가하려면 클러스터 관리 IP 주소와 admin 사용자 계정의 암호를 알아야 합니다.
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["클러스터를 검색하는 방법에 대해 알아보십시오"^].



=== ONTAP 시스템 요구 사항을 확인합니다

다음 ONTAP 요구 사항이 충족되는지 확인합니다.

* 최소 ONTAP 9.8, ONTAP 9.8P13 이상이 권장됩니다.
* SnapMirror 라이센스(프리미엄 번들 또는 데이터 보호 번들의 일부로 포함)
+
* 참고: * BlueXP 백업 및 복구를 사용할 때는 "하이브리드 클라우드 번들"이 필요하지 않습니다.

+
자세한 내용을 알아보십시오 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["클러스터 라이센스를 관리합니다"^].

* 시간 및 시간대가 올바르게 설정되었습니다. 자세한 내용을 알아보십시오 https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["클러스터 시간을 구성합니다"^].
* 데이터를 복제하려는 경우 데이터를 복제하기 전에 소스 볼륨과 타겟 볼륨에서 호환되는 ONTAP 버전이 실행되고 있는지 확인해야 합니다.
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror 관계에 대한 호환되는 ONTAP 버전을 봅니다"^].


